### ISSUE TITLE
Guía para contribuir no muestra su código.

### ISSUE THREAD

**Issue by iam-agf** [python/python-docs-es#1012]
Cuando se entra en la [Guía para contribuir](https://python-docs-es.readthedocs.io/es/3.8/CONTRIBUTING.html), en la barra lateral izquierda se encuentra el botón `Mostrar el código`, pero éste manda a un error. Es necesario corregir el hipervínculo.

**Comment by humitos** [comment]
Ese link funciona para todos los `.po`, pero para todos los `.rst` que creamos nosotros dentro de `.override` no.

Para arreglarlo, hay que poner un if en estas líneas de este template: https://github.com/python/python-docs-es/blob/9dd3143cff159dbb71fefb3db62a63f9d91d98b2/.overrides/tools/templates/customsourcelink.html#L7-L9

**Comment by iam-agf** [comment]
¿Lo intento o mejor lo dejo para otra persona?

**Comment by humitos** [comment]
@iam-agf como te sientas más a gusto :)

Si te vas a divertir tocando ese archivo para agregar el if, adelante. Si crees que te vas a estresar, hacé otra cosa :smile:

**Comment by iam-agf** [comment]
Lo preguntaba por si toco algo y lo rompo, pero ahora que me desocupe lo hago, asígnamelo :-)

**Comment by iam-agf** [comment]
Bueno, lo dejo en manos de gente más capacitada porque no he podido :-(

**Comment by aroquega** [comment]
@cmaureir tengo una idea de como hacerlo pero no estoy seguro 100% y tendría que hacer pruebas, pero no puedo compilar la documentación para probarlo. Pienso en dos alternativas: crear un proyecto en sphinx y desde ahí probar como funcionan las variables de sphinx, o mandar un pr al repositorio para que se construya la documentación ¿Qué opinas?

¿@iam-agf que problemas tuviste? Estas referencias te pueden ser útiles o no:
- https://jinja.palletsprojects.com/en/2.11.x/templates/#if
- https://www.sphinx-doc.org/en/master/templating.html#global-variables

**Comment by aroquega** [comment]
El problema es que en la documentación en inglés, ellos lo reemplazan con rst, ya que sus documentos están en rst, y nuestros documentos están en .po a excepción de la guía de contribución y eso. Hay que verificar si el sufijo es rst para no reemplazarlo con .po

**Comment by aroquega** [comment]
La pr #1108 está arreglando eso

**Comment by iam-agf** [comment]
> El problema es que en la documentación en inglés, ellos lo reemplazan con rst, ya que sus documentos están en rst, y nuestros documentos están en .po a excepción de la guía de contribución y eso. Hay que verificar si el sufijo es rst para no reemplazarlo con .po

Yo desconozco, así que opté por dejarlo en manos de conocedores, porque igual hacer algo que creo que va a fallar hubiera terminado siendo un PR inútil 😓 .
