### ISSUE TITLE
Actualizar pospell a próxima versión

### ISSUE THREAD

**Issue by mondeja** [python/python-docs-es#1061]
Tras la actualización a la versión 1.0.6 de pospell, muchos fallos que antes han escapado de ser cazados ahora están siendo correctamente marcados como error. Así que no viene mal actualizar a la nueva versión.

Me pongo a ello en una rama aparte, aunque no la marcaré como lista hasta el próximo lanzamiento de pospell que no sea de testeo (versión 1.0.6 ó 1.0.7), ahora mismo como tag git está lanzada la [v1.0.6a1](https://github.com/JulienPalard/pospell/releases/tag/v1.0.6a1).

**Comment by cmaureir** [comment]
Te dejé un comentario en  https://github.com/python/python-docs-es/pull/1060, puedes reproducir localmente el problema?
Ojo que tienes que agregar al Makefile `-l es_AR` para que sea como el de Travis.
