### ISSUE TITLE
Fixed a math error in Potodo 🎉

### ISSUE THREAD

**Issue by Seluj78** [python/python-docs-es#1079]
Hola a todos !

Sorry I won't write in spanish, it's my third language 👍 

A few months ago, @JulienPalard opened an issue in https://github.com/Seluj78/Potodo (https://github.com/Seluj78/Potodo/issues/53) Saying that there is a math error and it is finally fixed. You can find that latest version here:

https://github.com/Seluj78/Potodo/releases/tag/v0.17.3

As well a a bunch of new features ! Don't hesitate to let me know if you need anything !

Amablemente,
Jules

**Comment by cmaureir** [comment]
I'll be closing this issue @Seluj78 but are all very happy for the news since you posted it ;)
Thanks for your project! and we will certainly go back to you in case we need something :raised_hands:

**Comment by Seluj78** [comment]
Glad you liked it ! Please do let me know if you have feature requests and all
