### ISSUE TITLE
Migración de TravisCI

### ISSUE THREAD

**Issue by mondeja** [python/python-docs-es#1157]
TravisCI está dejando de ser gratuito para proyectos de código abierto. Esto está provocando que las construcciones se queden paradas durante horas. Creo que es momento de migrar y yo voto por Github Actions que por ahora es completamente gratuito para proyectos de código abierto.

**Comment by cmaureir** [comment]
+1 a usar Github actions.

**Comment by mikanchu** [comment]
+1 a github actions

**Comment by raulcd** [comment]
+1 a usar GitHub actions

**Comment by lazaromer97** [comment]
+1 a GitHub actions
