### ISSUE TITLE
Integración canal de Telegram con el servidor Discord "Python en Español"

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1222]
Hola gente :wave:,

Hace un tiempo que varias comunidades de habla hispana han estado empujando una nueva iniciativa llamada **Python en Español**, siendo el primer paso haber renombrado el canal más grande de telegram ("Python España") para utilizar el mismo nombre.
Ya que telegram no escala para poder tener más de 6000 personas hablando temas distintos, quisimos mirar otras plataformas que nos ayudaran a crear más espacios para que la comunidad pueda compartir, elegimos Discord por la experiencia de un par de eventos pasados, y por el tema de tener voz, video y muchos canales en un mismo lugar.

Para poder interactuar con distintas comunidades, pedir a la gente que abandone sus plataformas habituales sería bastante intrusivo, con lo que queremos comenzar a probar puentes entre las aplicaciones.

Esta **issue** para sugerir, y quizás comenzar una discusión, en si están de acuerdo en tener un nuevo bot  en el canal de telegram, que agregará todos los comentarios que el canal futuro canal `python-docs-es` en este nuevo servidor de Discord pueda obtener, y de la misma manera, que sus mensajes sean transmitidos a este nuevo canal.

Para ejemplificar un poco el tema, les adjunto una imagen que hice en un canal de telegram y un servidor de discord de prueba:
![discord-telegram](https://user-images.githubusercontent.com/177982/111921913-6ee30a80-8a97-11eb-842b-6b450bb74905.png)

¿Qué les parece?

(Si les interesa unirse al server, la invitación es esta: https://discord.gg/35E3Ph7Fez )

**Comment by cacrespo** [comment]
Me parece estupenda la idea! 🚀 🚀 🚀 
Agregaría algún mensaje en la bienvenida al grupo de Telegram para aclarar que se está reproduciendo el contenido en Discord y todo el mundo esté al tanto.

**Comment by josephLSalgado** [comment]
Interesante mientras estás en discord por todos los canales del server incluyendo uno para el de telegram :)

**Comment by alcides29** [comment]
Me parece buena la integración!

**Comment by raulcd** [comment]
Considero que es una buena idea. Puede ayudar a conocer el proyecto incluso a más gente.

**Comment by cmaureir** [comment]
Gracias por sus comentarios :)
A penas tenga la integración andando, les avisaré!

**Comment by framorac** [comment]
Me parece genial 👌

**Comment by eamanu** [comment]
Apoyo!!!

**Comment by eamanu** [comment]
+1  por una integración con IRC :D

**Comment by cmaureir** [comment]
Pues ya está funcionando, así que cerraré esta issue :man_dancing:
