### ISSUE TITLE
Using PyDocteur for python-docs-es ?

### ISSUE THREAD

**Issue by Seluj78** [python/python-docs-es#1228]
Holà a todos !

I'm one of the maintainers and translators of `python-docs-fr` and I also build tools that you might use for your translation such as `potodo`.

I have a new tool to present to you, that might interest you ?

It's called PyDocteur (PYthon DOCumentation and teur from the word `doctor` in french, doctEUR 😉)

What's it for ? Well if you contributed to `cpython`, you know they have a ton of bots that help them manage and sort PRs rapidly, backport them, merge them etc... PyDocteur does the same ! more or less...

As of right now, it will merge a PR if it is approved and the tests passes, and some other small stuff. Eventually we'd like it to be able to backport PRs !

Here's the source: https://github.com/AFPy/PyDocTeur

Feel free to reach out/ask questions! I'd love for PyDocteur to be used by not only the french Translation team ! i18n is possible for the bot too !

Espero que todas estén bien
Jules

**Comment by cacrespo** [comment]
Hi Jules! 
Merci beaucoup de nous avoir écrit!

I will forward the message to the telegram group to give it greater visibility.

**Comment by humitos** [comment]
Hi @Seluj78! Thanks for the suggestion of the bot. Can you expand about what are all the functionalities of the bot? I tried to find the documentation, but I wasn't able to 🙃

**Comment by Seluj78** [comment]
Of course ! It allows you to auto merge pull requests if they are valid, comment when new people arrive, comment if tests fail etc... I'd recommend you check out some PRs in the french repo !
