### ISSUE TITLE
orden alfabético roto en el glosario

### ISSUE THREAD

**Issue by cacrespo** [python/python-docs-es#1266]
Revisando la traducción de `glosary.po` me di cuenta que al traducir rompimos el orden alfabético (que sí tiene en la versión original). Y no me gusta nada ¿?
Es este [archivo](https://github.com/python/python-docs-es/blob/3.9/glossary.po).

¿Cómo dicen de encararlo? Creo que sería mejor agregar las palabras originales al comienzo de cada entrada traducida.

**Comment by cacrespo** [comment]
Hola @andresbermeoq! Te lo asigno.

**Comment by andresbermeoq** [comment]
Listo sin problema @cacrespo... podrías darme un poco de feedback acerca del issue, le ordeno o buscaría primero las palabras originales.

**Comment by cacrespo** [comment]
> Listo sin problema @cacrespo... podrías darme un poco de feedback acerca del issue, le ordeno o buscaría primero las palabras originales.

El orden debemos mantenerlo tal cuál está, eso no se puede cambiar. Y respecto a buscar la palabras, en realidad es más simple: es cuestión de ver el texto original en inglés y ya.

Si te resulta más práctico podemos conversar en Telegram o Discord.

**Comment by humitos** [comment]
*Creo* que no se puede arreglar el órden alfabético del glosario. Me imagino que tendríamos que hablar con gente *upstream* por esto ya que los .po lo único que hacen es "cambiar el texto original por el traducido" pero no pueden modificar la estructura del archivo original.

Para solucionar esto, tendríamos que buscar una solución coordinada con la comunidad, aunque lo veo un poco difícil.

**Comment by cacrespo** [comment]
Yep. Está bastante dificil de resolver y no veo que amerite hacer un mayor esfuerzo. 
@andresbermeoq lamento que hayas dedicado tiempo y no pudimos arribar a buen puerto. :disappointed: 
Cierro issue: el orden del documento no se puede alterar.
