### ISSUE TITLE
Translate 'library/io.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1281]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.9/library/io.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/io.po`:

* Fuzzy: 18
* Percent translated: 97.5%
* Entries: 233 / 239
* Untranslated: 6

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by carmandorh** [comment]
Quiero apoyar en traducir

**Comment by cacrespo** [comment]
Te asigno este issue @carmandorh. Escribe por cualquier duda que tengas.

**Comment by cmaureir** [comment]
tomando esta issue que lleva mucho tiempo desatendida
