### ISSUE TITLE
Translate 'library/ast.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1319]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.9/library/ast.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/ast.po`:

* Fuzzy: 0
* Percent translated: 30.7%
* Entries: 58 / 189
* Untranslated: 131

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by javoweb** [comment]
Hola! Puedo tomar esta si está libre.

**Comment by cacrespo** [comment]
@javoweb que lo disfrutes!
