### ISSUE TITLE
Translate 'whatsnew/changelog.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1325]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.9/whatsnew/changelog.html once translated.
Meanwhile, the English version is shown.

Current stats for `whatsnew/changelog.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 5106
* Untranslated: 5106

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by cmaureir** [comment]
Con este me jubilo

**Comment by xochozomatli** [comment]
I could give a hand with this one.

**Comment by cacrespo** [comment]
Hola @xochozomatli ! La verdad que este es un archivo super largo y aburrido que estamos tratando de traducir automáticamente. Tal vez es mucho más productivo si tomas algún otro archivo. 
Sin embargo, si no te importa y quieres trabajarlo igual: puedes ir avanzando sobre este PR #1328 

Cualquier duda que tengas, escribe sin problemas 😄

**Comment by xochozomatli** [comment]
Gracias, @cacrespo . Veamos cuánto me puedo poner al tanto con el PR  :woozy_face:
