### ISSUE TITLE
Ajustar detalles en 14 traducciones finalizadas

### ISSUE THREAD

**Issue by cacrespo** [python/python-docs-es#1372]
Cada uno de estos archivos tienen una entrada pendiente o a revisar:

~whatsnew/3.3.po~
~library/symbol.po~
~library/pdb.po~
~library/site.po~
~library/unittest.mock.po~
~library/smtpd.po~
~library/statistics.po~
~library/parser.po~
~library/pprint.po~
~library/shlex.po~
~library/poplib.po~
~library/threading.po~

library/decimal.po
library/struct.po

Por favor comenta si quieres tomar estos ajustes. 😄

No te olvides de seguir los pasos de la [Guia para contribuir](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by paaaron** [comment]
Yo puedo trabajar en esto

**Comment by cacrespo** [comment]
@paaaron Adelante!

**Comment by mhered** [comment]
Hola me gustaria colaboarar trabajando en el archivo library/pdb.po. Es posible, o solo puede haber un colaborador asignado?

**Comment by cmaureir** [comment]
Hola @mhered como esta tarea es bastante corta, seguimos la idea de 1 persona por Issue. Cuando hay issues muy grandes se suelen dividir. Te recomiendo mirar otra Issue abierta en las que puedas darnos una mano!

**Comment by paaaron** [comment]
Hola a todos, acualmente tengo el siguiente inconveniente: 
Cuando agrego el ";" el powrap falla
![image](https://user-images.githubusercontent.com/679293/139583589-9244aed9-e9c6-4bb9-aa19-f26cf157a7dc.png)
![image](https://user-images.githubusercontent.com/679293/139583626-02ad6bf2-f720-4ded-840d-ba80aa7145f5.png)
De antemano muchas gracias por el apoyo.

**Comment by cmaureir** [comment]
cómo falla? ahí no veo el error.
Quítale el '--check' y solo ejecuta `powrap library/pprint.po` y ya con eso se hará el wrap.

**Comment by paaaron** [comment]
Funciona perfecto. Muchas gracias.

**Comment by paaaron** [comment]
El test falla con ese error. Alguna idea?

![image](https://user-images.githubusercontent.com/679293/139596839-31dc887f-ac2e-4b42-bb10-1302b141f606.png)

**Comment by cacrespo** [comment]
Hola @paaaron! El problema está en el archivo `pprint.po`. En alguna linea del original tenés 
```
:mod:`pprint`
```
pero luego en la entrada traducida te falta eso. Es probable que se te haya cambiado ´ por ' o algo así...

**Comment by paaaron** [comment]
> Hola @paaaron! El problema está en el archivo `pprint.po`. En alguna linea del original tenés
> 
> ```
> :mod:`pprint`
> ```
> 
> pero luego en la entrada traducida te falta eso. Es probable que se te haya cambiado ´ por ' o algo así...

Efectivamente ya lo solucioné. Muhcas gracias!

**Comment by paaaron** [comment]
Hola,

Actualmente tengo este error:

![image](https://user-images.githubusercontent.com/679293/139681967-6c048495-2931-4623-b503-06c49efb932f.png)

**Comment by cmaureir** [comment]
Ten cuidado @paaaron, actualizaste el submodulo `cpython` y eso hará que se rompa todo. Si te parece mejor, puedes siempre comenzar con una issue que tenga un solo archivo que traducir.
Es muy probable que todo eso venga porque agregaste el submodulo, pues es de un archivo que no has modificado.

**Comment by cmaureir** [comment]
Hice el merge temporal que tenías @paaaron y marqué los archivos que ya están listos acá en esta issue.

@cacrespo recuerda que como la generación de issues es automática, nos pisamos los talones cuando hice el nuevo batch de issues, con lo que para quien tome archivos faltantes, no olvide poner una clausula `closes #xxxx` de las siguientes issues:

https://github.com/python/python-docs-es/issues/1448
https://github.com/python/python-docs-es/issues/1431
https://github.com/python/python-docs-es/issues/1426

**Comment by cmaureir** [comment]
tomando esta issue para acabarla
