### ISSUE TITLE
Translate 'using/unix.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1392]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.10/using/unix.html once translated.
Meanwhile, the English version is shown.

Current stats for `using/unix.po`:

* Fuzzy: 1
* Percent translated: 88.9%
* Entries: 40 / 45
* Untranslated: 5

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by macagua** [comment]
Please assign me :)

**Comment by cmaureir** [comment]
todo tuyo :tada:

**Comment by cmaureir** [comment]
@macagua te puedo ayudar con algo?

**Comment by cmaureir** [comment]
tomando esta issue por inactividad, recuerda que puedes buscar issues abiertas sin problema cuando tengas tiempo!
