### ISSUE TITLE
Translate `faq/programming.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#141]
This needs to reach 100% translated.

Current stats for `faq/programming.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 348
- Untranslated: 348

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by kikocorreoso** [comment]
I will start working on this.

Thanks.

**Comment by cmaureir** [comment]
Muchas gracias @kikocorreoso  :)

**Comment by kikocorreoso** [comment]
25%...

Madre mía, ¿me he cogido el más largo? :office_worker:

**Comment by humitos** [comment]
> Untranslated: 348

Es largo este, sí :smile: --348 párrafos.

Igual, puedes hacer la PR con lo que tienes y podemos ir mergeando y revisando cosas más pequeñas. Hacer review de un archivo completo así de largo va a ser tedioso también.

**Comment by kikocorreoso** [comment]
De momento sigo. A ver si llego al 50% esta mañana...
