### ISSUE TITLE
Translate 'reference/expressions.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1414]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.10/reference/expressions.html once translated.
Meanwhile, the English version is shown.

Current stats for `reference/expressions.po`:

* Fuzzy: 7
* Percent translated: 97.0%
* Entries: 319 / 329
* Untranslated: 10

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by erickisos** [comment]
Podrían asignarme este?

**Comment by cmaureir** [comment]
todo tuyo!

**Comment by cmaureir** [comment]
Te podemos ayudar con algo @erickisos ?

**Comment by erickisos** [comment]
@cmaureir todo bien, perdón por el retraso pero me cargué un poco de trabajo esta semana

**Comment by cacrespo** [comment]
Hola @erickisos ¿cómo estás? Oye, quieres que te ayude y traduzca algunas partes del archivo?

**Comment by cmaureir** [comment]
Ha pasado casi un mes, por lo general dábamos un par de semanas, como el archivo no es largo, lo tomo por inactividad.

**Comment by erickisos** [comment]
Bueno, por lo que entiendo igual ya quedó resuelto, cierto?
Muchas gracias por la ayuda y una disculpa por el retraso, gracias por la oferta @cacrespo
