### ISSUE TITLE
Translate 'reference/compound_stmts.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1418]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.10/reference/compound_stmts.html once translated.
Meanwhile, the English version is shown.

Current stats for `reference/compound_stmts.po`:

* Fuzzy: 4
* Percent translated: 39.9%
* Entries: 118 / 296
* Untranslated: 178

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by marcorichetta** [comment]
Me interesaría trabajar en este issue. 
Vi los demás issues abiertos y tienen muy pocas cadenas para traducir. Entiendo que son útiles para gente que contribuye por primera vez al proyecto, por eso es que solicito este.

Gracias :)

**Comment by cmaureir** [comment]
vale, mucho éxito y paciencia!
