### ISSUE TITLE
Translate 'library/parser.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1485]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.10/library/parser.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/parser.po`:

* Fuzzy: 0
* Percent translated: 98.0%
* Entries: 49 / 50
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by hector-sab** [comment]
Hola, yo puedo trabajar en este issue.

**Comment by cmaureir** [comment]
te lo dejamos también :tada:

**Comment by hector-sab** [comment]
@cmaureir listo el PR

**Comment by hector-sab** [comment]
Por cierto @cmaureir  ¿Algo mas en lo que pueda ayudar? Veo que la mayoria de issues abiertos son `good first issue` y no sé si planeen dejarlos ahí para personas queriendo empezar a contribuir o si puedo ir pidiendolos para ir cerrandolos.

**Comment by cmaureir** [comment]
no te preocupes, como son archivos con pocas entradas, por eso solo quedan de esos...pero hay que terminarlos en algún momento, asi que adelante :)
