### ISSUE TITLE
Translate 'library/tkinter.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1497]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.10/library/tkinter.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/tkinter.po`:

* Fuzzy: 18
* Percent translated: 76.9%
* Entries: 277 / 360
* Untranslated: 83

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by TiaIvonne** [comment]
Hola @cmaureir puedes asignarme esto? gracias

**Comment by cmaureir** [comment]
83 entradas pendientes y 18 fuzzy :O
Mucho éxito! se viene bastante trabajo.

Recuerda volver a la rama 3.10 y verificar que no hay commits tuyos en tu repositorio antes de crear una nueva rama para esta traducción. Mucho éxito

**Comment by TiaIvonne** [comment]
Hola @cmaureir tengo una pregunta en el archivo a traducir aparece una tabla de comandos seguidos de un valor, es necesario traducir esos elementos? ej %h height no se si es conveniente traducirlo a : %h altura. Gracias

**Comment by cmaureir** [comment]
Viendo el archivo con `poedit` esos elementos no necesitan ser traducidos.

**Comment by cmaureir** [comment]
te podemos ayudar en algo @TiaIvonne ?

**Comment by cmaureir** [comment]
tomando esta issue por inactividad
