### ISSUE TITLE
Translate 'faq/windows.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1513]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.10/faq/windows.html once translated.
Meanwhile, the English version is shown.

Current stats for `faq/windows.po`:

* Fuzzy: 0
* Percent translated: 97.9%
* Entries: 47 / 48
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by gmmonsalve** [comment]
Me gustaría trabajar en este archivo también! 📝

**Comment by cmaureir** [comment]
@gmmonsalve te asigné otras 2 issues, veamos si se une otra persona que esté comenzando para que haga este archivo que solo tiene una entrada.

**Comment by hector-sab** [comment]
Hola @cmaureir, yo puedo tomar este issue.

**Comment by cmaureir** [comment]
todo tuyo @hector-sab !
