### ISSUE TITLE
Translate 'c-api/typehints.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1517]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.10/c-api/typehints.html once translated.
Meanwhile, the English version is shown.

Current stats for `c-api/typehints.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 6
* Untranslated: 6

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by erickisos** [comment]
Can I start working on this?

**Comment by cmaureir** [comment]
te asigné otros @erickisos , cuando los acabes podemos seguir con este ;)

**Comment by erickisos** [comment]
LIsto, podemos seguir con este?

**Comment by cmaureir** [comment]
todo tuyo
