### ISSUE TITLE
Translate 'c-api/type.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1520]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.10/c-api/type.html once translated.
Meanwhile, the English version is shown.

Current stats for `c-api/type.po`:

* Fuzzy: 2
* Percent translated: 92.8%
* Entries: 64 / 69
* Untranslated: 5

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by fragalcer** [comment]
I would like to work on this issue

**Comment by cmaureir** [comment]
todo tuyo!

**Comment by cmaureir** [comment]
tomando este issue por inactividad. Te invitamos a tomar otro issue de los que quedan abiertos :)
