### ISSUE TITLE
Translate `library/array.po`

### ISSUE THREAD

**Issue by albertcalv** [python/python-docs-es#157]
I will take care of this file

**Comment by humitos** [comment]
Great! Thanks!

**Comment by humitos** [comment]
Hola @albertcalv! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by humitos** [comment]
Ya encontré tu PR :smile:
