### ISSUE TITLE
Translate `distributing/index.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#158]
This needs to reach 100% translated.

Current stats for `distributing/index.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 40
- Untranslated: 40

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by iris9112** [comment]
Please assign me this issue @humitos

**Comment by humitos** [comment]
Hola @iris9112! ¿Cómo vienes con este archivo? ¿Has tenido la oportunidad de avanzar en la traducción? ¿Tienes alguna duda?

**Comment by iris9112** [comment]
Hola @humitos no voy tan rápido como quisiera. Lo siento por eso. He avanzado algo, mañana en la tarde espero estar haciendo el PR. Gracias por la paciencia :)

**Comment by humitos** [comment]
@iris9112 no hay problema con los tiempos! Simplemente voy chequeando cada tanto que la gente no esté bloqueada por algo. Gracias por tu tiempo y trabajo :)

**Comment by cmaureir** [comment]
@iris9112  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by iris9112** [comment]
Hola @cmaureir  tienes toda la razón, creo que lo mejor es liberar el issue. Solo que no sé como :(

**Comment by cmaureir** [comment]
Siempre iremos generando más archivos, así que espero puedas igual volver y colaborar con esta iniciativa cuando tengas más tiempo, Gracias :)

**Comment by FedericoJurio** [comment]
@humitos Me gustaría trabajar en esta traducción!

**Comment by cmaureir** [comment]
Ya lo tienes @FedericoJurio éxito con la traducción! Recuerda mencionar este issue con un "Closes #158" cuando crees tu Pull request.

**Comment by FedericoJurio** [comment]
El PR está listo para ser revisado
