### ISSUE TITLE
Cadena sin traducir en la versión 3.10 del tutorial

### ISSUE THREAD

**Issue by astrojuanlu** [python/python-docs-es#1633]
https://docs.python.org/es/3/tutorial/

![Screenshot 2021-11-11 at 13-13-45 Tutorial de Python — documentación de Python - 3 10 0](https://user-images.githubusercontent.com/316517/141296207-233eeaaa-6032-4231-8735-1869f5f3e437.png)

En la versión 3.9 está correcto.

**Comment by erickisos** [comment]
Creo que aparece así porque está marcado como _fuzzy_ en los archivos, however, acabo de crear un PR para tratar de corregir esto, also aproveché para cambiar un poco el texto en algunas partes por si quieres revisarlo y dejar alguna sugerencia está en #1641
