### ISSUE TITLE
Translate 'library/zipfile.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1758]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.10/library/zipfile.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/zipfile.po`:

* Fuzzy: 0
* Percent translated: 99.4%
* Entries: 177 / 178
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by aroquega** [comment]
Puedo hacer este? y porqué les agregas hacktoberfest y luego lo quitas?

**Comment by cmaureir** [comment]
> Puedo hacer este? y porqué les agregas hacktoberfest y luego lo quitas?

porque las issues las creo automáticamente con un script, y tenía la configuración que use para el Hacktoberfest, pero como ya pasó, no es necesario tenerlas, así que se las he quitado.
