### ISSUE TITLE
Translate 'library/asyncio-eventloop.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1793]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.10/library/asyncio-eventloop.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/asyncio-eventloop.po`:

* Fuzzy: 5
* Percent translated: 99.1%
* Entries: 348 / 351
* Untranslated: 3

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by sumit-158** [comment]
can i work on this?

**Comment by rtobar** [comment]
Todo tuyo!

**Comment by mmmarcos** [comment]
¡Hola! tomo este issue para completar lo que falta :)

**Comment by mmmarcos** [comment]
@rtobar ya lo tengo traducido, espero el assign por las dudas 😅
