### ISSUE TITLE
Arreglar entradas fuzzy de archivos que no tienen entradas pendientes para traducir

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1798]
El script utilizado para crear las issues estaba basado en entradas pendientes de traducción, no archivos que solo tuvieran entradas fuzzy.

**Comment by cmaureir** [comment]
@cacrespo  este era el problema que notaste, los archivos con SOLO entradas fuzzy no eran considerados :+1:

**Comment by cacrespo** [comment]
Genial! ¿Modificaste el script también?

**Comment by cmaureir** [comment]
no, porque uso otro, no el del repo :O
