### ISSUE TITLE
I want to translate this directory

### ISSUE THREAD

**Issue by PySemos** [python/python-docs-es#1823]
I want to translate some files of the directory whatsnew/.

**Comment by marcorichetta** [comment]
Hi!

What files do you want to translate? 
I'm asking because the translation was completed a few months ago (https://twitter.com/cmaureir/status/1480224763108892681)

**Comment by cmaureir** [comment]
El proyecto está actualmente 100% traducido en 3.10.0
Cuando sea el lanzamiento de 3.11.0 abriremos muchas más issues de archivos para traducir @PySemos que podrás elegir :D 
Te recomiendo que te unas al grupo de telegram para poner atención en ello

**Comment by humitos** [comment]
Hola @PySemos. Ya tenemos un montón de issues nuevos creados para poder traducir. Elije el que quieras y adelante!
