### ISSUE TITLE
python  doesn't work

### ISSUE THREAD

**Issue by Luciana1982** [python/python-docs-es#1826]
Good morning!
 
Please, I had qgis 3.8 installed and I uninstalled it, also in regedit, but now when I install qgis 3.22 I don't see anything in the plugins menu, nor the python console...

Here send a imagen of my qgis installed, please if anyone has the same thing, I hope answers

Thanks!!

![qgis1](https://user-images.githubusercontent.com/106097954/169854706-342af7ba-0710-4377-ae1a-067dd94de476.jpg)

**Comment by cacrespo** [comment]
Hi @Luciana1982!
This repository is for the Spanish translation of the Python documentation. I think you should ask this question in some qgis group or forum :sweat_smile: .

Regards
