### ISSUE TITLE
Translate 'using/cmdline.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1850]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.10/using/cmdline.html once translated.
Meanwhile, the English version is shown.

Current stats for `using/cmdline.po`:

* Fuzzy: 8
* Percent translated: 92.1%
* Entries: 197 / 214
* Untranslated: 17

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by AndreaGriffiths11** [comment]
Vengo animada de Cristian y el evento de presente :) si todavía necesitas ayuda con esta traducción, count me in!

**Comment by cmaureir** [comment]
Genial @AndreaGriffiths11 :tada: muchas gracias, y cualquier duda acá estamos

**Comment by cmaureir** [comment]
te podemos ayudar con algo? si no tienes tiempo nos dices para asignar este issue a otra persona :+1:
