### ISSUE TITLE
Translate 'library/select.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1866]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.10/library/select.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/select.po`:

* Fuzzy: 4
* Percent translated: 99.5%
* Entries: 203 / 204
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by BlackeyeB** [comment]
Hola, disculpa pero no entiendo que es lo que falta por hacer para llegar al 100% desde el 99'5%. Me gustaría colaborar pero no veo en qué

**Comment by rtobar** [comment]
@BlackeyeB como dice la descripción de este issue hay aún una entrada sin traducir, y cuatro entradas que están marcadas como "fuzzy" (o sea, que la traducción necesita ajustes). Si abres el archivo con un editor de archivos `.po` como `poedir` te vas a dar cuenta rápidamente cuáles son las entradas que necesitan trabajo.

Cuéntanos cómo te va explorando el archivo, y si estás interesado te asigno el issue :)

**Comment by cmaureir** [comment]
Quiero traducir este issue (tutorial de discord)
