### ISSUE TITLE
Translate 'library/security_warnings.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1875]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.10/library/security_warnings.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/security_warnings.po`:

* Fuzzy: 1
* Percent translated: 94.1%
* Entries: 16 / 17
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by aandrea** [comment]
Hola, quiero tomar este ticket!

**Comment by cmaureir** [comment]
por favor espera que los issues se te asignen antes de hacer la traducción. En casos donde pueden haber conflictos de más de una persona, se podría descartar tu trabajo.

**Comment by aandrea** [comment]
Hola, lo siento. Vi tu comentario tarde. Lo tengo en cuenta para la próxima.
