### ISSUE TITLE
Translate `library/os.path.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#188]
This needs to reach 100% translated.

Current stats for `library/os.path.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 61
- Untranslated: 61

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by albertcalv** [comment]
Here to translate :)

**Comment by raulcd** [comment]
Gracias asignada a @albertcalv

**Comment by humitos** [comment]
Hola @albertcalv! ¿Cómo vienes con este archivo? ¿Has tenido la oportunidad de avanzar en la traducción? ¿Tienes alguna duda?

**Comment by cmaureir** [comment]
@albertcalv te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by albertcalv** [comment]
Hola, deje libre el Issue

**Comment by cmaureir** [comment]
Gracias @albertcalv, ojalá podamos tener tu ayuda en futuros archivos a traducir!

**Comment by mxarc** [comment]
Hola, me gustaría continuar con este issue

**Comment by cmaureir** [comment]
Hecho @mxarc ! Mucho éxito! :tada:
