### ISSUE TITLE
Investigar cómo integrar Transifex o crowding

### ISSUE THREAD

**Issue by gilgamezh** [python/python-docs-es#19]
Un recurso que puede servir es https://translate.djangogirls.org/

**Comment by gilgamezh** [comment]
la version de Brazil está usandolo http://rgth.co/blog/python-ptbr-como-traduzir

**Comment by gilgamezh** [comment]
https://www.transifex.com/python-doc/python-newest/announcements/8917/

![image](https://user-images.githubusercontent.com/1496486/80839607-dc761600-8bfb-11ea-9b91-e985d2513154.png)

**Comment by clacri** [comment]
Muchas gracias por los recursos. Yo ya me he creado la cuenta en Transifex y he solicitado acceso al proyecto de Python para ver un poco como va el proceso. Al registrarte te da opciones de varios Spanish, sospecho que el que no tiene nada entre paréntesis debe ser el neutro. 
<img width="1217" alt="Screenshot 2020-05-02 at 10 08 51" src="https://user-images.githubusercontent.com/10925572/80858925-2c38f980-8c5d-11ea-8359-0643e7a9b41e.png">
Sigo investigando :) tambien estoy mirando lo de crowdin de django girls.

**Comment by clacri** [comment]
Vale, he encontrado esto:https://docs.transifex.com/transifex-github-integrations/github-tx-ui  
Aunque no tengo muy claro que tengamos que crear algo nuevo en transifex, sino linkarnos a algo ya existente, ya que el proyecto como tal existe en transifex y lo usan muchas versiones de traduccion, no solo brasil sino china, japon, etc. Creo que cuando tengamos el repositorio asociado a la PSF lo podríamos linkar directamente con transifex (o meter los cambios en el repositorio si es que ya existe).

**Comment by silvinabt87** [comment]
Hola! Me interesa este ticket para colaborar con @clacri

**Comment by humitos** [comment]
Me acaban de comentar de esta otra plataforma que puede ser interesante pegarle una mirada también: https://weblate.org/es/

**Comment by clacri** [comment]
Al final hemos acordado dejar el flujo de trabajo como lo llevamos no? Esta issue debe seguir abierta?

**Comment by humitos** [comment]
Sí. Lo cerramos por ahora. Luego vemos de reabrirlo si necesitamos. Gracias!
