### ISSUE TITLE
Translate 'library/profile.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1912]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/profile.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/profile.po`:

* Fuzzy: 0
* Percent translated: 99.4%
* Entries: 155 / 156
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by jmaxter** [comment]
Disculpar, olvidé esperar la asignación e hice el PR. Creo que igual marcará error por un tema de formato de porcentajes y marcador de posición % o % d.....
