### ISSUE TITLE
Translate 'library/operator.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1919]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/operator.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/operator.po`:

* Fuzzy: 0
* Percent translated: 98.9%
* Entries: 178 / 180
* Untranslated: 2

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by sanbancan** [comment]
Please assign this issue as I would like to work on it.

**Comment by cmaureir** [comment]
¿Hablas un poco de español @sanbancan ?
Es posible que si no, y utilizas algún traductor, algunos detalles de las entradas necesiten discusión luego de que envies el cambio. Si no tienes problema con ello, nos dices!

**Comment by sanbancan** [comment]
I can't speak Spanish. However, I can use a translator for chats. If discussion is involved, I need a translator from your end.

**Comment by sanbancan** [comment]
No puedo hablar español. Sin embargo, puedo usar un traductor para los chats. Si se trata de una discusión, necesito un traductor de su parte.

**Comment by cmaureir** [comment]
Gracias por tu interés @sanbancan, quizás es mejor que puedas ayudar a otros proyectos de traducciones, pues a veces los traductores no funcionan bien.

Puedes encontrar una lista a otros proyectos en: https://devguide.python.org/documentation/translating/

**Comment by jmaxter** [comment]
Favor asignar ese issue.
