### ISSUE TITLE
Translate `library/glob.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#192]
This needs to reach 100% translated.

Current stats for `library/glob.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 16
- Untranslated: 16

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by kikocorreoso** [comment]
Me lo llevo.

**Comment by raulcd** [comment]
Asignada a @kikocorreoso

**Comment by humitos** [comment]
Hola @kikocorreoso! Has podido avanzar con la traducción de este archivo? Puedes abrir una PR en modo Draft si quieres con el trabajo que tengas hasta este momento, aunque no esté completa.

**Comment by kikocorreoso** [comment]
Está traducido de hace mucho. Lo tengo que revisar y hacer PR. A ver si esta semana lo puedo hacer...

**Comment by humitos** [comment]
Gracias! 👍💪

**Comment by cmaureir** [comment]
@kikocorreoso te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by kikocorreoso** [comment]
Desde que lo traduje hasta ahora ha habido actualizaciones en la versión en inglés por lo que lo he vuelto a traducir y revisar. Está en #720 al 100%.
