### ISSUE TITLE
Translate 'library/_thread.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1948]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/_thread.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/_thread.po`:

* Fuzzy: 3
* Percent translated: 97.6%
* Entries: 41 / 42
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by tanmay-haldar0** [comment]
I want to work on this issue. Please assign this issue.

**Comment by cmaureir** [comment]
¡Hola! Solo para confirmar, hablas español ¿cierto?
Te lo pregunto porque respondiste en inglés y buscamos a personas que sean nativas, o que al menos hablen  Español, pues intentamos evitar las traducciones automatizadas.

**Comment by cmaureir** [comment]
@jmaxter entendemos tu motivación, pero mejor ir haciendo de a pocos archivos y luego asignamos más, si te los asignamos todos a la misma vez puede que otras personas que quieran comenzar se queden sin issues :P

**Comment by oscar-garzon** [comment]
Hola! Pueden asignarme este issue?

**Comment by cmaureir** [comment]
todo tuyo @oscar-garzon :+1:
