### ISSUE TITLE
Translate `library/typing.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#195]
This needs to reach 100% translated.

Current stats for `library/typing.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 208
- Untranslated: 208

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by hectorcanto** [comment]
por favor, asignenmela

**Comment by hectorcanto** [comment]
draft PR en https://github.com/PyCampES/python-docs-es/pull/221
