### ISSUE TITLE
Translate `library/webbrowser.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#196]
This needs to reach 100% translated.

Current stats for `library/webbrowser.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 82
- Untranslated: 82

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by damiansire** [comment]
Please assign me :D

**Comment by humitos** [comment]
Yaaaay! Enjoy translating this file :partying_face:

**Comment by damiansire** [comment]
Thanks! I work in this!

**Comment by humitos** [comment]
Hola @damiansire ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by cmaureir** [comment]
@damiansire  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by damiansire** [comment]
Recuerdo haber terminado esto el mismo día que me lo asignaron, probablemente hice algo mal ene l proceso de subida. (Era mi primer aportación) Les pido disculpas y está noche lo reviso. Muchas gracias por avisar

**Comment by cmaureir** [comment]
No veo ningún PR cerrado con este contenido :O así que quizás te quedó en alguna rama local. Avisame si te puedo ayudar con algo :)

**Comment by mondeja** [comment]
Hola @damiansire, ¿podrías confirmar si tienes una rama en local sobre esta traducción? Si no es así y pudieras liberar este issue te lo agradecería ya que me gustaría continuarlo ;)

**Comment by cmaureir** [comment]
@mondeja si te interesa esta issue luego avisanos, por inactividad lo he dejado sin nadie asignado. He buscado en los repositorios de la persona que lo tenia pero no encontré ningún fork de python-docs-es como para rescatar la traducción.

**Comment by mondeja** [comment]
Sí, asignamelo y me pongo con ello.

**Comment by cmaureir** [comment]
Gracias! :tada:
