### ISSUE TITLE
Translate 'library/unittest.mock.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1966]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/unittest.mock.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/unittest.mock.po`:

* Fuzzy: 4
* Percent translated: 99.7%
* Entries: 374 / 375
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by tanmay-haldar0** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by cmaureir** [comment]
> I want to work on this issue. Please assign me this issue.

¡Hola! Solo para confirmar, hablas español ¿cierto?
Te lo pregunto porque respondiste en inglés y buscamos a personas que sean nativas, o que al menos hablen  Español, pues intentamos evitar las traducciones automatizadas.

**Comment by JimmyTzuc** [comment]
Hola, hablo español nativo, Puedo trabajar este Issue? espero respuesta

**Comment by rtobar** [comment]
¡Mucho ánimo @JimmyTzuc! :muscle:

**Comment by rtobar** [comment]
@JimmyTzuc hay algo en lo que te podamos ayudar? Cuéntanos si aún quieres trabajar en este issue, porque en caso de que no sea así lo podemos dejar libre para que alguien más trabaje en él. Gracias!

**Comment by JimmyTzuc** [comment]
Hola @rtobar estoy trabajando en ello, me comunico con ustedes por Telegram para info, gracias por estar al pendiente
