### ISSUE TITLE
Translate 'library/fileinput.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1985]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/fileinput.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/fileinput.po`:

* Fuzzy: 3
* Percent translated: 97.8%
* Entries: 44 / 45
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by xandrade** [comment]
I would like to work in this issue ✋🏻

**Comment by cmaureir** [comment]
todo tuyo!
recuerda volver a 3.11 en tu repositorio antes de crear un nuevo branch para trabajar en este archivo, para que no ocurra el error frecuente que vemos de gente que genera otra rama y se trae los cambios anteriores en el nuevo PR

**Comment by xandrade** [comment]
> todo tuyo! recuerda volver a 3.11 en tu repositorio antes de crear un nuevo branch para trabajar en este archivo, para que no ocurra el error frecuente que vemos de gente que genera otra rama y se trae los cambios anteriores en el nuevo PR

Cristián, gracias por el coaching!

**Comment by cmaureir** [comment]
Queda el issue libre por inactividad. Si quieres pedirlo de nuevo, lo puedes hacer :)

**Comment by jmaxter** [comment]
Favor asignar este issue.

**Comment by rtobar** [comment]
Todo tuyo @jmaxter! 💪
