### ISSUE TITLE
Translate 'library/threading.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1987]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/threading.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/threading.po`:

* Fuzzy: 15
* Percent translated: 97.2%
* Entries: 210 / 216
* Untranslated: 6

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by clacri** [comment]
Me gustaria traducir esta tambien si es posible, o me espero a ir haciendo cada una?

**Comment by cmaureir** [comment]
dale, que son varias jaja quizás podrías usar alguna con más entradas si es que encuentras una después de ésta!
