### ISSUE TITLE
Translate 'library/timeit.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#1992]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/timeit.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/timeit.po`:

* Fuzzy: 1
* Percent translated: 98.1%
* Entries: 52 / 53
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by henrzven** [comment]
I would like to work on this issue

**Comment by cmaureir** [comment]
Amazing, all yours!

**Comment by cmaureir** [comment]
@henrzven te podemos ayudar en algo? si no tienes tiempo nos dices para asignarlo a otra persona :+1:

**Comment by cmaureir** [comment]
Queda el issue libre por inactividad. Si quieres pedirlo de nuevo, lo puedes hacer :)
