### ISSUE TITLE
Translate `library/urllib.parse.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#200]
This needs to reach 100% translated.

Current stats for `library/urllib.parse.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 140
- Untranslated: 140

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by marcosmamg** [comment]
Hola, puedo trabajar en este issue.

**Comment by humitos** [comment]
@marcosmamg adelante! que lo disfrutes! :partying_face:

**Comment by humitos** [comment]
Hola @marcosmamg! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by marcosmamg** [comment]
Si, lo tengo listo, solamente quiero revisarlo un poco mas y reparar alguno que otro error para hacer mi PR

**Comment by cmaureir** [comment]
Buena @marcosmamg ! :D Gusto de verte por estos lado, a ver si nos vemos en la PyCon2021 en US :)

**Comment by cmaureir** [comment]
@marcosmamg   te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by cmaureir** [comment]
@marcosmamg Si tienes algo, lo podrías subir? de lo contrario le asignaremos esto a otra persona, pues ha pasado mucho tiempo. Que estés bien!

**Comment by marcosmamg** [comment]
@cmaureir, disculpa los inconvenientes, este Domingo sin falta creo un pull request
