### ISSUE TITLE
Translate 'library/binascii.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2002]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/binascii.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/binascii.po`:

* Fuzzy: 3
* Percent translated: 84.4%
* Entries: 38 / 45
* Untranslated: 7

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by josephLSalgado** [comment]
Quisiera continuar con este otro. ¿Será que puedo hacer otros issues a la vez? 😁

**Comment by cmaureir** [comment]
Mientras no sean muchos (más de 3) yo creo que todo super :)

**Comment by josephLSalgado** [comment]
Ok, checaré otros 2 más :)
