### ISSUE TITLE
Translate 'library/queue.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2004]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/queue.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/queue.po`:

* Fuzzy: 2
* Percent translated: 97.7%
* Entries: 42 / 43
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Alfareiza** [comment]
@cmaureir ✋Me pido esta. Gracias

**Comment by cmaureir** [comment]
cerremos las que tienes asignadas y luego asignamos más

**Comment by Alfareiza** [comment]
@cmaureir En cuanto puedas, me asignas esta pfv. Pronto deben considerarse 3 issues más como cerradas.

**Comment by cmaureir** [comment]
Muchas gracias! :rocket:
