### ISSUE TITLE
Translate `library/traceback.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#201]
This needs to reach 100% translated.

Current stats for `library/traceback.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 66
- Untranslated: 66

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by beejeke** [comment]
Hi @humitos! I would like translate this file ✔

**Comment by beejeke** [comment]
Thank you @raulcd !👍

**Comment by humitos** [comment]
Hola @beejeke ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by beejeke** [comment]
Hola @humitos ! Si, perdona, pensé que había hecho el pull request hace días. Ya está hecho.
Saludos!
