### ISSUE TITLE
Translate 'library/zoneinfo.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2013]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/zoneinfo.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/zoneinfo.po`:

* Fuzzy: 0
* Percent translated: 97.3%
* Entries: 72 / 74
* Untranslated: 2

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Alfareiza** [comment]
@cmaureir Me pido esta por favor.

**Comment by cmaureir** [comment]
cerremos las que tienes asignadas y luego asignamos más

**Comment by Alfareiza** [comment]
Que tal @cmaureir , me asignas esta por favor. Gracias.

**Comment by cmaureir** [comment]
ok, igual creo que ya estás graduado hace tiempo con estas issues que tienen 1 o 2 frases sin traducir. Podrías mirar alguna issue que tengan más sin traducir, así dejamos estas sencillas para toda la gente que se vaya uniendo

**Comment by Alfareiza** [comment]
Claro que si, en la próxima asumiré unas traducciones con más frases.
