### ISSUE TITLE
Translate 'library/nis.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2017]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/nis.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/nis.po`:

* Fuzzy: 0
* Percent translated: 80.0%
* Entries: 12 / 15
* Untranslated: 3

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by carlosalma** [comment]
Me gustaría trabajar con este fichero.

**Comment by rtobar** [comment]
Todo tuyo,!

**Comment by carlosalma** [comment]
He localizado una errata en nis.rst:16, me gustaría solucionarlo.

**Comment by cmaureir** [comment]
claro, solo envía la corrección :+1:

**Comment by cmaureir** [comment]
te podemos ayudar en algo @carlosalma ?

**Comment by carlosalma** [comment]
Al revisar el fichero, solo veo como pendiente una línea que he marcado como fuzzy, por un WARNING: inconsistent term references in translated message. Si me queda algo más o, si el empleo de la etiqueta fuzzy no es adecuada, por favor indicádmelo.

**Comment by cmaureir** [comment]
Gracias! recuerda para la próxima en tu Pull Request escribir `closes #xxxx` con el número del Issue (no del Pull request).
