### ISSUE TITLE
Translate 'library/bisect.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2019]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/bisect.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/bisect.po`:

* Fuzzy: 2
* Percent translated: 87.1%
* Entries: 27 / 31
* Untranslated: 4

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by rafa238** [comment]
I want to help with this file :)

**Comment by cmaureir** [comment]
@rafa238  te podemos ayudar en algo? si no tienes tiempo nos dices y le podemos asignar este issue a otra persona :+1:

**Comment by rafa238** [comment]
Si solo un poco mas de tiempo porfavor

**Comment by cmaureir** [comment]
Queda el issue libre por inactividad. Si quieres pedirlo de nuevo, lo puedes hacer :)

**Comment by jmaxter** [comment]
Favor asignar este issue.

**Comment by cmaureir** [comment]
queda asignada a ti @santi4o :tada:  (@jmaxter se me pasó esta pero de seguro encuentras otra por ahí :D)
