### ISSUE TITLE
Translate `library/textwrap.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#202]
This needs to reach 100% translated.

Current stats for `library/textwrap.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 46
- Untranslated: 46

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by pandrearro** [comment]
I would like to work on this file.

**Comment by humitos** [comment]
Hecho en #249
