### ISSUE TITLE
Translate 'library/asyncio-policy.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2024]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/asyncio-policy.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/asyncio-policy.po`:

* Fuzzy: 1
* Percent translated: 97.1%
* Entries: 66 / 68
* Untranslated: 2

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by gomezgleonardob** [comment]
Please assign me

**Comment by cmaureir** [comment]
@gomezgleonardob  te podemos ayudar en algo? si no tienes tiempo nos dices y le podemos asignar este issue a otra persona :+1:

**Comment by cmaureir** [comment]
Queda el issue libre por inactividad. Si quieres pedirlo de nuevo, lo puedes hacer :)

**Comment by jmaxter** [comment]
Favor asignar issue.

**Comment by cmaureir** [comment]
@jmaxter entendemos tu motivación, pero mejor ir haciendo de a pocos archivos y luego asignamos más, si te los asignamos todos a la misma vez puede que otras personas que quieran comenzar se queden sin issues :P

**Comment by Jesparzarom** [comment]
Hola, si sigue libre podría colaborar con este. 🖐

**Comment by mmmarcos** [comment]
> Hola, si sigue libre podría colaborar con este. 🖐

Así parece, todo tuyo! 👍
