### ISSUE TITLE
Translate 'library/re.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2025]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/re.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/re.po`:

* Fuzzy: 8
* Percent translated: 95.4%
* Entries: 290 / 304
* Untranslated: 14

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by cmaureir** [comment]
éxito!

**Comment by cmaureir** [comment]
@josemanuel22   te podemos ayudar en algo? si no tienes tiempo nos dices y le podemos asignar este issue a otra persona :+1:

**Comment by josemanuel22** [comment]
@cmaureir gracias, asigna la issue a otra persona

**Comment by cmaureir** [comment]
queda este issue disponible para quien quiera trabajarlo!

**Comment by jdgc14** [comment]
Hola, puede trabajar este archivo?

**Comment by rtobar** [comment]
@jdgc14 con gusto te lo asigno, pero te recomendaría que termines el detalle pendiente en la traducción de functions antes de saltar a éste para que no se te enreden las cosas.

**Comment by fmoradev** [comment]
Hola, puedo finalizar este por favor?

**Comment by rtobar** [comment]
@fmoradev dale, te lo asigno ya que quedaste con las manos desocupadas nuevamente.

@jdgc14 no hubo respuesta a mi última consulta acá hace una semana más o menos, así que asumo que estás ocupado con otras cosas por el momento. Hay haaaarto trabajo disponible eso sí todavía así que aún toda ayuda es bienvenida!
