### ISSUE TITLE
Translate 'library/asyncio-eventloop.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2027]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/asyncio-eventloop.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/asyncio-eventloop.po`:

* Fuzzy: 22
* Percent translated: 97.8%
* Entries: 360 / 368
* Untranslated: 8

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by marcorichetta** [comment]
🙋

**Comment by cmaureir** [comment]
muchas gracias!

**Comment by cmaureir** [comment]
@marcorichetta te podemos ayudar en algo? si no tienes tiempo nos dices y le podemos asignar este issue a otra persona :+1:

**Comment by marcorichetta** [comment]
@cmaureir Hola Cristián. Pido disculpas, lo pospuse un tiempo y hasta me olvidé que lo tenía asignado.
No son tantos strings así que le dedicaré un tiempito el fin de semana. Gracias por preguntar!

**Comment by cmaureir** [comment]
no te preocupes! a veces hay muchas notificaciones y se pasan estas cosas :)
