### ISSUE TITLE
Translate 'library/tkinter.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2028]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/tkinter.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/tkinter.po`:

* Fuzzy: 7
* Percent translated: 94.1%
* Entries: 286 / 304
* Untranslated: 18

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by carlosalma** [comment]
Me gustaría trabajar en este fichero.

**Comment by cmaureir** [comment]
todo tuyo!

**Comment by carlosalma** [comment]
Gracias!

**Comment by cmaureir** [comment]
@carlosalma te podemos ayudar en algo? si no tienes tiempo, dinos para asignar este issue a otra persona :+1:
