### ISSUE TITLE
Como parte del glosario: fichero, archivo, carpeta, directorio,...

### ISSUE THREAD

**Issue by kikocorreoso** [python/python-docs-es#203]
Me gustaría aclarar qué usar para: *file*, *archive*, *directory*, *subdirectory*,...

En mi caso estoy usando:

* **fichero** para *file*, *archive*,...

* **Directorio** para *directory*, *folder*,...

¿Se ha hablado sobre esto en algún otro sitio? ¿Existe quorum para usar lo que estoy usando y meterlo en el glosario?

**Comment by clacri** [comment]
creo que lo mejor es que si se ha discutido en telegram con los demás, añadas eso a la memoria de traducción

**Comment by clacri** [comment]
igualmente me parece que son términos que tanto en español como en inglés se usan indistintamente. He abierto la discusión en telegram, cierro la issue aqui.
