### ISSUE TITLE
Translate 'library/syslog.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2042]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/library/syslog.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/syslog.po`:

* Fuzzy: 1
* Percent translated: 87.1%
* Entries: 27 / 31
* Untranslated: 4

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Alfareiza** [comment]
@cmaureir Me pido esta por favor.

**Comment by cmaureir** [comment]
cerremos las que tienes asignadas y luego asignamos más

**Comment by Alfareiza** [comment]
Que tal @cmaureir , me asignas esta por favor. Gracias.

**Comment by cmaureir** [comment]
hecho!
