### ISSUE TITLE
Translate 'faq/windows.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2050]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/faq/windows.html once translated.
Meanwhile, the English version is shown.

Current stats for `faq/windows.po`:

* Fuzzy: 1
* Percent translated: 95.9%
* Entries: 47 / 49
* Untranslated: 2

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by rubenesp87** [comment]
Me gustaría trabajar en este issue

**Comment by cmaureir** [comment]
todo tuyo!

**Comment by cmaureir** [comment]
@rubenesp87 te podemos ayudar en algo? si no tienes tiempo, dinos para asignar este issue a otra persona :+1:

**Comment by rubenesp87** [comment]
> @rubenesp87 te podemos ayudar en algo? si no tienes tiempo, dinos para asignar este issue a otra persona 👍

Perdona no vi la asignación 🙏  ya estoy trabajando en ella

**Comment by erickisos** [comment]
Puedo tomar este issue para cerrarlo? 😰

**Comment by cmaureir** [comment]
> Puedo tomar este issue para cerrarlo? cold_sweat

preguntale primero a @rubenesp87 en el mismo PR :+1:
