### ISSUE TITLE
Translate 'c-api/type.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2053]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/c-api/type.html once translated.
Meanwhile, the English version is shown.

Current stats for `c-api/type.po`:

* Fuzzy: 4
* Percent translated: 92.8%
* Entries: 64 / 69
* Untranslated: 5

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by henrzven** [comment]
I would like to work on this issue

**Comment by cmaureir** [comment]
same here, let's wait to close the others

**Comment by Papaganti-sravya** [comment]
I would like to work on this issue.

**Comment by cmaureir** [comment]
Como lo había pedido antes @henrzven, puedes buscar otro 'good first issue' para traducir @Papaganti-sravya :+1:

**Comment by cmaureir** [comment]
Queda el issue libre por inactividad. Si quieres pedirlo de nuevo, lo puedes hacer :)

**Comment by igmtz** [comment]
Holaa @cmaureir ! Puedo tomar este issue? 😄

**Comment by cmaureir** [comment]
todo tuyo @igmtz :+1:

**Comment by igmtz** [comment]
Hola @cmaureir ya hice un pull request (https://github.com/python/python-docs-es/pull/2370). Ando al pendiente por cualquier cambio que deba hacerse 😄

**Comment by igmtz** [comment]
Holaa @cmaureir tengo unos problemas con los test del PR :c
<img width="1217" alt="Screen Shot 2023-04-10 at 2 10 38" src="https://user-images.githubusercontent.com/104402745/230857941-a22225e3-ed85-4f90-a7c4-739392be2436.png">
