### ISSUE TITLE
Translate 'c-api/intro.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2057]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/c-api/intro.html once translated.
Meanwhile, the English version is shown.

Current stats for `c-api/intro.po`:

* Fuzzy: 3
* Percent translated: 90.4%
* Entries: 85 / 94
* Untranslated: 9

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by daorejuela1** [comment]
Hi Cristián! I would like to have this file assigned to me

**Comment by cacrespo** [comment]
@daorejuela1 que lo disfrutes! :smile:
