### ISSUE TITLE
Translate 'c-api/capsule.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2061]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/c-api/capsule.html once translated.
Meanwhile, the English version is shown.

Current stats for `c-api/capsule.po`:

* Fuzzy: 2
* Percent translated: 96.7%
* Entries: 29 / 30
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by sofide** [comment]
I would like to take this issue :)

**Comment by sofide** [comment]
Uh, cree el PR antes de que me asignen el issue, perdón por la ansiedad 😬 Era cortito igual jeje.
