### ISSUE TITLE
Translate 'c-api/init.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2065]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/c-api/init.html once translated.
Meanwhile, the English version is shown.

Current stats for `c-api/init.po`:

* Fuzzy: 13
* Percent translated: 95.1%
* Entries: 310 / 326
* Untranslated: 16

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by martorelli617** [comment]
Me gustaría traducir este archivo

**Comment by cmaureir** [comment]
ya te asigné 3 @martorelli617, cuando los termine seguimos asignando :+1:

**Comment by jdgc14** [comment]
Me gustaria trabajar en esta traduccion

**Comment by cmaureir** [comment]
@jdgc14 aún tienes disponibilidad e interés para la traducción?

**Comment by jdgc14** [comment]
Hola! Mil disculpas ya mismo lo voy a trabajar

**Comment by jdgc14** [comment]
Hola, ya subi la traduccion y ha aprobado los tests, pero en el issue numero 2273
