### ISSUE TITLE
Translate 'c-api/float.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2067]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/c-api/float.html once translated.
Meanwhile, the English version is shown.

Current stats for `c-api/float.po`:

* Fuzzy: 4
* Percent translated: 39.4%
* Entries: 13 / 33
* Untranslated: 20

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by xandrade** [comment]
I would like to work on this issue, translating to Spanish

**Comment by cmaureir** [comment]
mucho éxito :+1:

**Comment by cmaureir** [comment]
@xandrade te podemos ayudar en algo? si no tienes tiempo para continuar nos dices y le asignamos el issue a otra persona.

**Comment by xandrade** [comment]
@cmaureir no sé qué pasó que no me llegó la notificación anterior. Ahora mismo me pongo a trabajar en esto. Espero tener progreso en 2 días.

**Comment by xandrade** [comment]
@cmaureir creo que lo he logrado. No es solamente mi primera traducción, pero también mi primera contribución aca​. Así que espero que esté bien y si no, estoy listo para hacer las modificaciones pertinentes. Gracias por darme el chance y nuevamente, pido disculpas por el retraso.

**Comment by cmaureir** [comment]
muchas gracias! ya mismo revisamos tu contribución!
