### ISSUE TITLE
Translate 'c-api/marshal.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2070]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.11/c-api/marshal.html once translated.
Meanwhile, the English version is shown.

Current stats for `c-api/marshal.po`:

* Fuzzy: 4
* Percent translated: 93.8%
* Entries: 15 / 16
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by henrzven** [comment]
I want

**Comment by cmaureir** [comment]
let's finish the other issues you currently have assigned, then we can continue with more!

**Comment by erickisos** [comment]
Hola, puedo tomar este?

**Comment by cmaureir** [comment]
todo tuyo Erick
