### ISSUE TITLE
Arreglar y verificar branch protection rules

### ISSUE THREAD

**Issue by raulcd** [python/python-docs-es#2093]
Trabajando en el siguiente commit:
https://github.com/python/python-docs-es/commit/9278f937fe88b16a2a54d8cf14ac43cb3fb015d8
He hecho un push a la rama 3.11 directamente sin querer (tenía mal el remote con mi fork).
Las branch protection rules deberían haber aplicado y el push debería haber sido rechazado.

Deberíamos revisar las branch protection rules para evitar que se puedan hacer commits directamente a las ramas 3.* involuntariamente y que siempre se necesite una Pull Request.

**Comment by raulcd** [comment]
Pero se puede limitar que nadie pueda, no? que ni un super user pueda hacerlo, todos deberíamos pasar por una PR.

**Comment by humitos** [comment]
_Creo_ que lo acabo de arreglar con la setting que puse. Si querés comprobar, bienvenido 😄
