### ISSUE TITLE
Integrar el bot de telegram que usan en brasil

### ISSUE THREAD

**Issue by gilgamezh** [python/python-docs-es#21]
Investigar cómo funciona el bot de https://github.com/python/python-docs-pt-br

**Comment by marcorichetta** [comment]
Agrego link al código del bot - https://github.com/rougeth/i17obot

**Comment by gilgamezh** [comment]
https://github.com/rougeth/i17obot/issues/5

**Comment by cmaureir** [comment]
Suena genial, mirando el código del bot noté que está más relacionado con funcionalidades de transifex, que al final decidimos de no utilizar. ¿Hay algún feature en particular que piensen que podría ayudarnos?
Sería genial tener un bot más completo, ya que actualmente el que tenemos solo cubre lo siguiente:
* Avisa por cada PR nuevo con un mensaje al grupo de telegram,
* Avisa cada vez que hay un merge,
* Lista los PRs abiertos y el progreso del proyecto (basado el parseo de un sitio web donde tenemos las estadísticas)
* Genera URLs para distintos PRs.

**Comment by marcorichetta** [comment]
Buenas!

Después de bastante tiempo quise volver al proyecto y veo que este issue quedó en el limbo.
Como dice Cristian, si no usamos Transifex no le sacaremos mucho provecho.

Repregunto esto por si se les ocurre alguna feature útil actualmente para agregarle al bot que ya tenemos.
> ¿Hay algún feature en particular que piensen que podría ayudarnos?

**Comment by cmaureir** [comment]
De lo que alcancé a ver no vi nada que llamara mucho la atención, quizás tienes algo en mente?
Las features actuales no han cambiado mucho, solo que ahora tenemos un comando para listar los video-tutoriales que tenemos.

**Comment by marcorichetta** [comment]
> quizás tienes algo en mente?
No realmente. Preguntaba porque no estoy al tanto del día a día del grupo.

Una feature interesante es esta #629 pero creo que será más fácil hacerlo como ya está planteado mediante GH.

**Comment by marcorichetta** [comment]
Creo que este issue se podría cerrar
