### ISSUE TITLE
Revisar títulos y ajustar mayúsculas

### ISSUE THREAD

**Issue by cacrespo** [python/python-docs-es#2173]
Algunos títulos usan "title case" porque es una regla de estilo en inglés. Por ejemplo
https://python-docs-es.readthedocs.io/es/3.11/tutorial/venv.html
https://python-docs-es.readthedocs.io/es/3.11/library/netdata.html
https://python-docs-es.readthedocs.io/es/3.11/library/markup.html

Sin embargo, en castellano, lo correcto es que solo la primera esté en mayúscula.

**Comment by erickisos** [comment]
Les parece si creo un PR actualizando eso?

**Comment by cmaureir** [comment]
sería genial, pero si lo haces de a uno, así menos trabajo :D pues esos archivos son solo un 'ejemplo' y pueden haber varios más

**Comment by erickisos** [comment]
Justo eso estaba pensando @cmaureir jaja, deja le doy una revisada y de una vez
