### ISSUE TITLE
Translate `library/json.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#219]
This needs to reach 100% translated.

Current stats for `library/json.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 143
- Untranslated: 143

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by adriaanbd** [comment]
Hello, I'd like to work on this file, thanks!

**Comment by humitos** [comment]
Great! Thanks! Enjoy translating this file!

**Comment by adriaanbd** [comment]
@humitos is it ok to push my branch so that I can save the progress here and you can all get updated on its status?

**Comment by adriaanbd** [comment]
I've pushed my branch with a 20% progress so far. Keeping it here as backup and to update the team.

**Comment by humitos** [comment]
Yes! Prefect. You can create a PR as Draft so we know it's not ready for review yet

**Comment by humitos** [comment]
@adriaanbd did you create a PR for your branch? I'm not finding it. Could you please create it and link it to this issue?

**Comment by adriaanbd** [comment]
@humitos I haven't but will go ahead and do so. Sorry for the delay but I started a new job recently  and have been loaded with work. I left it at 20% progress. Will continue this week.

**Comment by cmaureir** [comment]
@adriaanbd  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by adriaanbd** [comment]
@cmaureir tranquilo que lo hago hoy, voy a borrar y reemplazar el archivo
