### ISSUE TITLE
Deprecated actions on main.yml

### ISSUE THREAD

**Issue by mmmarcos** [python/python-docs-es#2203]
The `actions/checkout@v2` and `actions/setup-python@v2` are deprecated and generate warnings (i.e. see annotations on 
https://github.com/python/python-docs-es/actions/runs/3483802845)

The new versions are [`actions/checkout@v3`](https://github.com/actions/checkout) and [`actions/setup-python@v4`](https://github.com/actions/setup-python).

Btw, we can try Dependabot auto-update actions feature: 
```
Dependabot checks the action's reference (typically a version number or commit
identifier associated with the action) against the latest version. If a more recent
version of the action is available, Dependabot will send you a pull request that
updates the reference in the workflow file to the latest version.
```
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

**Comment by rtobar** [comment]
Just merged, and indeed dependabot created PRs for the two deprecated packages: https://github.com/python/python-docs-es/pull/2224 and https://github.com/python/python-docs-es/pull/2225

**Comment by cmaureir** [comment]
I merged those PRs, let's see how it goes :eyes:

**Comment by mmmarcos** [comment]
@rtobar @cmaureir Thanks! Btw dependabot PRs have a lot of information about changes in newer versions, nice! 🤖

**Comment by mmmarcos** [comment]
Closing the issue. Dependabot has proved its worth ! 😁
