### ISSUE TITLE
How to get the stats of the documentation on d.p.o

### ISSUE THREAD

**Issue by egeakman** [python/python-docs-es#2253]
I saw this script at https://github.com/python/python-docs-es/blob/3.11/scripts/pageviews.py.

We would like to use something similar to this in the Turkish translation too, so I was wondering how did you access the page view stats of the Python documentation?

Can @humitos help?

**Comment by humitos** [comment]
Hi @egeakman! I remember I asked for this to the official documentation's team and they provided me the stats for the official documentation. I don't remember exactly who I contacted at that time, tho.

**Comment by egeakman** [comment]
I asked Julien about this, and he told me that @ewdurbin could help. I will ask Ee if periodic exports of these statistics are possible.

**Comment by ewdurbin** [comment]
Looks like the easily accessible way of grabbing these stats started silently failing in ~may due to https://github.com/python/psf-salt/issues/291

I can pull logs from the past 30 days from our archival bucket though. There's no automated way to access them at this time.

**Comment by egeakman** [comment]
@ewdurbin can you send the logs to me@egeakman.dev?
