### ISSUE TITLE
Translate `distutils/examples.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#227]
This needs to reach 100% translated.

Current stats for `distutils/examples.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 46
- Untranslated: 46

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by nicocastanio** [comment]
lo tomo

**Comment by humitos** [comment]
Hola @nicocastanio ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by nicocastanio** [comment]
perdón, no he podido avanzar. lo dejo libre para que lo pueda tomar alguien mas.

**Comment by estebansolo** [comment]
Lo puedo tomar?

**Comment by cmaureir** [comment]
Claro que si @estebansolo  :tada: éxito!
