### ISSUE TITLE
Podemos mover el repo  a la organización de python?

### ISSUE THREAD

**Issue by gilgamezh** [python/python-docs-es#23]
Consultar si es posible mover este repo a https://github.com/python

**Comment by raulcd** [comment]
Mail enviado a <translation@python.org> para preguntar sobre mover el repo y requisitos para hostear la documentación en docs.python.org

**Comment by raulcd** [comment]
under PEP-545:
https://www.python.org/dev/peps/pep-0545/#add-translation-to-the-language-switcher

The requirement to get to the language picker is [1] to translate the
tutorial, bugs.po, and library/functions.po.

**Comment by humitos** [comment]
Hecho! :tada:
