### ISSUE TITLE
Translate `library/collections.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#230]
This needs to reach 100% translated.

Current stats for `library/collections.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 199
- Untranslated: 199

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by javierdaza** [comment]
Yo puedo colaborar con este issue

**Comment by humitos** [comment]
@javierdaza hágale pues!

**Comment by humitos** [comment]
Hola @javierdaza ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by javierdaza** [comment]
@humitos enviaré una parte traducida este fin de semana

**Comment by cmaureir** [comment]
@javierdaza  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by javierdaza** [comment]
@cmaureir denme hasta la otra semana por favor. La otra semana estaré libre. 
Aunque si posiblemente necesite ayuda porque está bastante extenso (o no se si queda mejor que me asignen uno más pequeño)

**Comment by cmaureir** [comment]
Genial, la próxima semana vemos como vas, y ahí vemos si hacemos un merge parcial y re-abrimos otra issue para lo que quede faltante. éxito!

**Comment by cmaureir** [comment]
Hola @javierdaza, si tienes problemas con continuar con esto avisanos y lo podemos dejar libre para otra persona. Igual lo que lleves lo puedes subir, y lo podemos incluir parcialmente ;)
