### ISSUE TITLE
Translate `library/configparser.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#231]
This needs to reach 100% translated.

Current stats for `library/configparser.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 172
- Untranslated: 172

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by LlaveLuis** [comment]
Saludos, quisiera traducir ese archivo.

**Comment by humitos** [comment]
Hágale pues! Asignado
