### ISSUE TITLE
Translate `library/shutil.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#233]
This needs to reach 100% translated.

Current stats for `library/shutil.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 142
- Untranslated: 142

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by silvinabt87** [comment]
I'd like to work on this one!

**Comment by humitos** [comment]
@silvinabt87 great! enjoy translating :smiley:
