### ISSUE TITLE
Display version 3.11.0 for Spanish translation

### ISSUE THREAD

**Issue by mmmarcos** [python/python-docs-es#2339]
The version displayed for the Spanish translation is `3.11.2` even though translation is based on `3.11.0`.

![image](https://user-images.githubusercontent.com/786907/223120481-703c5c84-217c-477d-96f5-f03839025c81.png)

This should not be an issue in the general case but some docs have been updated between `3.11.0` and `3.11.2` (i.e. https://github.com/python/cpython/commit/62251c3da06eb4662502295697f39730565b1717). We should probably display `3.11.0` for the Spanish translation.

~_Explicit is better than implicit_~
_Right is better than wrong_ ^^

**Comment by cmaureir** [comment]
I suggested to update the docs with bug-fix releases, but the proposal was not accepted, because it would create more work, and some in-progress PRs might get out of sync.

https://github.com/python/python-docs-es/pull/1821

**Comment by cmaureir** [comment]
Not sure if we have control on that, it seems to be something from the deployment side of things.
On the other side, displaying 3.10.2 will show the "new text" in English, which is not too bad.

The problem I see with displaying 3.11.0 is that many newcomers might thing "Oh, so this is not valid because I downloaded 3.11.2" so very personally, I'd rather have incomplete docs, and display the latest/greatest, than showing the initial version we have the translations for.

**Comment by m-aciek** [comment]
Today some reader [has written on docs@python.org](https://mail.python.org/archives/list/docs@python.org/thread/4QGDLU2XAQGN2QNSQCFAYFVOI4WAMYEJ/) about missing translations of paragraphs in the tutorial.

I think pulling (/merging) the newest version of docs is better, it at least gives an opportunity to translators to translate the published docs, we currently don't build docs for `micro` versions other then latest (e.g. 3.11.1).

Either way if you'd like to push and try to change the build of Spanish docs, https://github.com/python/docsbuild-scripts is the repo that hosts the docs building scripts.

**Comment by mmmarcos** [comment]
@m-aciek @cmaureir I agree, we should display (and translate) the latest version of the docs. I guess we'll wait for the upcoming 3.12.0 and discuss following `micro` versions after that.

BTW, here is the translation progress: https://python-docs-es.readthedocs.io/es/3.11/progress.html
