### ISSUE TITLE
tutorial/stdlib.po

### ISSUE THREAD

**Issue by Sublian** [python/python-docs-es#2380]
Me gustaria trabajar con este archivo

**Comment by cmaureir** [comment]
Ya que no había un issue creado con este archivo, podrías agregar más información al issue que creaste de por qué había que trabajar en ese archivo?

**Comment by rtobar** [comment]
@Sublian este issue fue el que abriste antes de que se publicaran los issues para 3.12, cierto? Y además el PR que enviaste ya fue aceptado? Si es todo así, recomendaría que cierres este issue para evitar futuras confusiones.
