### ISSUE TITLE
Notas migración 3.11 to 3.12

### ISSUE THREAD

**Issue by cacrespo** [python/python-docs-es#2385]
.overrides/upgrade-python-version.rst

- Reemplazar 3.11 por 3.12 en dónde corresponda.
- Mover paso 10 (crear virtualenv) entre 7 y 8.
- Añadir el file reviewers-guide.rst al listado de "Clean possible garbage" (paso 9) .
- Añadir paso final de commitear todos los archivos generados.
- Crear rama 3.12 en el repositorio para hacer el merge ahí.
- Cambiar branch por defecto en el repositorio.
- Rebase de todos los PR a 3.12

**Comment by mmmarcos** [comment]
Algunos archivos mas para cambiar `3.11` por `3.12`: 
* [.overrides/faq.rst#L207-L209](https://github.com/python/python-docs-es/blob/b83f1b035e93531510165fc42d11b915e4649bf6/.overrides/faq.rst?plain=1#L207-L209)
* [.overrides/CONTRIBUTING.rst#L92-L96](https://github.com/python/python-docs-es/blob/b83f1b035e93531510165fc42d11b915e4649bf6/.overrides/CONTRIBUTING.rst?plain=1#L92-L96)
* [.overrides/progress.rst#L13](https://github.com/python/python-docs-es/blob/b83f1b035e93531510165fc42d11b915e4649bf6/.overrides/progress.rst?plain=1#L13)

**Comment by mmmarcos** [comment]
Hay que sumar las notas de @aandrea :grin:

**Comment by aandrea** [comment]
Hola!

@cacrespo anotó casi todo lo que yo tenía de mi lado :)
Algo para ver es que en el paso de la generación  de los archivos .po hay varios RuntimeWarning.
![image](https://github.com/python/python-docs-es/assets/4357386/c10360f8-dab4-475c-8bdd-8ba3001939f9)

Imagino que no debe ser muy importante porque pareciera que en el script de git actions son ignorados. 
https://github.com/python/python-docs-es/blob/e78e15fa36a9a144ef7099626ab91676f07f60ec/.github/workflows/main.yml

`
PYTHONWARNINGS=ignore::FutureWarning,ignore::RuntimeWarning sphinx-build -j auto -W --keep-going -b html -d cpython/Doc/_build/doctree -D language=es . cpython/Doc/_build/html`

¿Valdrá la pena ignorarlos tambien en dicha etapa?

**Comment by aandrea** [comment]
Hola, si nadie se opone me asigno este issue.

**Comment by aandrea** [comment]
[ .overrides/upgrade-python-version.rst](https://github.com/python/python-docs-es/blob/b83f1b035e93531510165fc42d11b915e4649bf6/.overrides/upgrade-python-version.rst)
* ~Reemplazar 3.11 por 3.12 en dónde corresponda.~
* ~Mover paso 10 (crear virtualenv) entre 7 y 8.~
* ~Añadir el file reviewers-guide.rst al listado de "Clean possible garbage" (paso 9) .~
* ~Añadir paso final de commitear todos los archivos generados.~
* ~Crear rama 3.12 en el repositorio para hacer el merge ahí.~
* ~Cambiar branch por defecto en el repositorio.~
* ~Rebase de todos los PR a 3.12~
