### ISSUE TITLE
Translate `howto/annotations.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2387]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/howto/annotations.html once translated.
Meanwhile, the English version is shown.

Current stats for `howto/annotations.po`:

* Fuzzy: 1
* Percent translated: 97.8%
* Entries: 44 / 45
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Yenniferh** [comment]
I'd like to translate this file

**Comment by cmaureir** [comment]
Lo mismo acá, cuando acabes los otros, te vamos asignando más

**Comment by Yenniferh** [comment]
Puedo trabajar en este? De los otros dos que tenía asignado, uno fue mergeado y el otro está en espera de revisión

**Comment by rtobar** [comment]
Asignado, como bien dices ya avanzaste con otros issues, y además éste es más bien pequeño
