### ISSUE TITLE
Translate `howto/enum.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2390]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/howto/enum.html once translated.
Meanwhile, the English version is shown.

Current stats for `howto/enum.po`:

* Fuzzy: 10
* Percent translated: 92.3%
* Entries: 217 / 235
* Untranslated: 18

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Yenniferh** [comment]
Me puede asignar este issue también?

**Comment by rtobar** [comment]
@Yenniferh y este también!

**Comment by Yenniferh** [comment]
Tuve inconvenientes con mi laptop y perdí lo que llevaba de la traducción de este archivo. Volveré a traducirlo una vez tenga el workspace configurado
