### ISSUE TITLE
Translate `howto/logging.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2394]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/howto/logging.html once translated.
Meanwhile, the English version is shown.

Current stats for `howto/logging.po`:

* Fuzzy: 3
* Percent translated: 98.2%
* Entries: 222 / 226
* Untranslated: 4

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Yenniferh** [comment]
I'd like to translate this file

**Comment by cmaureir** [comment]
Ya te dejé los otros dos @Yenniferh :+1: a medida que vayas acabándolos te asignamos más

**Comment by Yenniferh** [comment]
Me pueden asignar este? Solo tengo un pequeño PR en espera de revisión

**Comment by rtobar** [comment]
Tuyo @Yenniferh
