### ISSUE TITLE
Translate `extending/newtypes_tutorial.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2396]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/extending/newtypes_tutorial.html once translated.
Meanwhile, the English version is shown.

Current stats for `extending/newtypes_tutorial.po`:

* Fuzzy: 44
* Percent translated: 99.2%
* Entries: 124 / 125
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by kbiggers** [comment]
Hola! me gustaría trabajar en esta propuesta, alguien me la puede asignar?

**Comment by rtobar** [comment]
Gracias @kbiggers por las ganas de ayudar, y perdón por l demora. Veo que esta sería tu primera contribución, ¿no? En ese aso sería ideal si tomaras un issue con menos entradas a traducir (éste tiene 44 fuzzy más una son traducir). ¡Muchas gracias!

**Comment by cmaureir** [comment]
:warning:  Cerrando este issue para poder tener uno actualizado luego de la migración a 3.13
