### ISSUE TITLE
Translate `tutorial/stdlib.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2405]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/tutorial/stdlib.html once translated.
Meanwhile, the English version is shown.

Current stats for `tutorial/stdlib.po`:

* Fuzzy: 2
* Percent translated: 93.8%
* Entries: 45 / 48
* Untranslated: 3

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Sublian** [comment]
Saludos, me gustaría trabajar en este archivo

**Comment by cmaureir** [comment]
asignado @Sublian :tada:

**Comment by Sublian** [comment]
Buen día amigos.
<Consulta>
La actualización que hice previamente la envié a la 3.11 y está generando error. 
Debo enviarla a este issue o terminar con la anterior? Gracias por su pronta respuesta

**Comment by cmaureir** [comment]
Deberías enviar todo a 3.12
