### ISSUE TITLE
Translate `library/venv.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#242]
This needs to reach 100% translated.

Current stats for `library/venv.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 86
- Untranslated: 86

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Qkolnek** [comment]
¿Podría trabajar en este archivo?

**Comment by humitos** [comment]
@Qkolnek sí! adelante! happy translation time!

**Comment by humitos** [comment]
Hecho en #273
