### ISSUE TITLE
Translate `library/warnings.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#243]
This needs to reach 100% translated.

Current stats for `library/warnings.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 109
- Untranslated: 109

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by gomezgleonardob** [comment]
Please assign me

**Comment by humitos** [comment]
Hecho en #329
