### ISSUE TITLE
Translate `c-api/float.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2441]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/c-api/float.html once translated.
Meanwhile, the English version is shown.

Current stats for `c-api/float.po`:

* Fuzzy: 5
* Percent translated: 97.1%
* Entries: 34 / 35
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by PaolaDaft** [comment]
Hi!
Can you assign it to me?

**Comment by cmaureir** [comment]
Ya tienes dos @PaolaDaft cuando las acabes te seguimos asignando

**Comment by JulioReyes11** [comment]
Hola, me gustaría encargarme de este archivo.

**Comment by rtobar** [comment]
Adelante @JulioReyes11, todo tuyo 😉
