### ISSUE TITLE
Translate `library/tempfile.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#245]
This needs to reach 100% translated.

Current stats for `library/tempfile.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 60
- Untranslated: 60

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by darwing1210** [comment]
@humitos me gustaría colaborar con este :)

**Comment by humitos** [comment]
@darwing1210 adelante! que lo disfrutes :smile:
