### ISSUE TITLE
Translate `library/signal.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2528]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/signal.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/signal.po`:

* Fuzzy: 20
* Percent translated: 99.3%
* Entries: 135 / 136
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by RiveroDev** [comment]
Hola!.. Me gustaría contribuir con la traducción de este archivo.

**Comment by rtobar** [comment]
@RiveroDev te recomiendo hacer #24

**Comment by RiveroDev** [comment]
OK .. Voy a  tomar tu sugerencia. Voy primero con el #2540, y luego con este, estoy aprendiendo mucho con el proceso y el manejo de git y github
