### ISSUE TITLE
Translate `library/argparse.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2535]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/argparse.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/argparse.po`:

* Fuzzy: 20
* Percent translated: 96.8%
* Entries: 328 / 339
* Untranslated: 11

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by JuliKM** [comment]
Hello, I would like to take this issue, could you assign it to me?

**Comment by xooseph** [comment]
También podré tomar este otro? 👀

**Comment by rtobar** [comment]
@xooseph te lo asigno. Perdón @JuliKM que se nos fue por las ramas hace tanto tiempo cuando lo pediste.

**Comment by JuliKM** [comment]
No hay problema!
