### ISSUE TITLE
Translate `library/csv.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2546]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/csv.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/csv.po`:

* Fuzzy: 2
* Percent translated: 90.4%
* Entries: 94 / 104
* Untranslated: 10

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by cmaureir** [comment]
> @cmaureir to which language is this translated to, is it translated from es to en or?

Hey, this is the 'python-docs-es' repository, so everything is translated to 'es' (Spanish).

**Comment by UlisesAlexanderAM** [comment]
Hola, me gustaría traducir este archivo.

**Comment by cmaureir** [comment]
adelante @UlisesAlexanderAM :+1:
