### ISSUE TITLE
Translate `library/decimal.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2550]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/decimal.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/decimal.po`:

* Fuzzy: 61
* Percent translated: 97.6%
* Entries: 331 / 339
* Untranslated: 8

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Manikantan-S** [comment]
He aprendido español desde 6th hasta 12th , por lo que supongo que tengo un nivel de comprensión primario del español y puedo hacer este trabajo.Por favor, asigna este issue a mí. Gracias

**Comment by cmaureir** [comment]
Te comenté en el otro issue, que ya que tu mensaje tiene errores gramaticales, quizás un issue donde hay que revisar 61 entradas fuzzy es demasiado trabajo y requiere buen conocimiento.

**Comment by Manikantan-S** [comment]
ok

**Comment by jcaalzago** [comment]
¿Puedo ayudar en la traducción de este fichero?

**Comment by rtobar** [comment]
Adelante @jcaalzago, muchas gracias! Recuerda agregarte también al archivo `TRANSLATORS` si quieres aparecer listado
