### ISSUE TITLE
Translate `library/msilib.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2553]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/msilib.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/msilib.po`:

* Fuzzy: 0
* Percent translated: 99.0%
* Entries: 96 / 97
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by carlosm00** [comment]
Buenas @cmaureir, también me ofrezco voluntario para este issue también. Gracias de antemano!

**Comment by rtobar** [comment]
@carlosm00 te dejo éste asignado también
