### ISSUE TITLE
Translate `library/ftplib.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2554]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/ftplib.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/ftplib.po`:

* Fuzzy: 4
* Percent translated: 94.4%
* Entries: 67 / 71
* Untranslated: 4

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by ericklasluisa** [comment]
Hola, me gustaría trabajar en esta traducción!

**Comment by Alfareiza** [comment]
Retomemos labores 😁, @cmaureir me podrías asignar esta pfv?

**Comment by rtobar** [comment]
Asignado!
