### ISSUE TITLE
Translate `library/exceptions.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2556]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/exceptions.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/exceptions.po`:

* Fuzzy: 21
* Percent translated: 94.4%
* Entries: 168 / 178
* Untranslated: 10

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Madhusri02** [comment]
let me translate this entries.

**Comment by cmaureir** [comment]
Nuestro objetivo es que personas con Español nativo puedan hacer las traducciones para evitar errores menores que traductores pueden generar. Gracias por tu interés de todos modos :)

**Comment by Marydifeld** [comment]
Buenas tardes, ¿podría apoyar con esto?

**Comment by carlosm00** [comment]
Buenas, me ofrezco voluntario para este issue también. Un saludo.
