### ISSUE TITLE
Translate `library/urllib.request.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2558]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/urllib.request.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/urllib.request.po`:

* Fuzzy: 4
* Percent translated: 98.6%
* Entries: 278 / 282
* Untranslated: 4

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by allengb208** [comment]
I would like to  solve this issue. Can you please explain a bit more .

**Comment by carlosm00** [comment]
Buenas, me ofrezco voluntario para este issue. Un saludo.

**Comment by mmmarcos** [comment]
Ahí va este también, gracias @carlosm00 !!
