### ISSUE TITLE
Translate `library/codecs.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2559]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/codecs.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/codecs.po`:

* Fuzzy: 19
* Percent translated: 98.3%
* Entries: 525 / 534
* Untranslated: 9

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by AYUSHMOHANTY10** [comment]
I want!!

**Comment by cmaureir** [comment]
como te mencionaba en el otro issue, estamos dando prioridad a personas que sepan español

**Comment by carlosm00** [comment]
Buenas! Puedo colaborar con este issue? Un saludo.

**Comment by cmaureir** [comment]
> Buenas, puedo colaborar con esta issue? Un saludo.

todo tuyo @carlosm00 Gracias!
