### ISSUE TITLE
Translate `library/token.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2568]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/token.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/token.po`:

* Fuzzy: 0
* Percent translated: 27.3%
* Entries: 18 / 66
* Untranslated: 48

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by parag477** [comment]
Can you assign this issue to me. I want to work on this.

**Comment by zodacdev** [comment]
¿Puedo tomar este?

**Comment by xooseph** [comment]
Hola. Podrían asignarme este issue? 😊

**Comment by cacrespo** [comment]
Asignado @xooseph ! 
Que lo disfrutes 🥳

**Comment by xooseph** [comment]
Existe la posibilidad de cambiar mi nombre y el username en el archivo TRANSLATORS? 🤔​

**Comment by rtobar** [comment]
Si, el error sólo indica que la posición en la que está puesto el nuevo nombre no es correcto si queremos mantener orden alfabético, y te muestra dónde debería ir para que el orden se preserve.

**Comment by xooseph** [comment]
Muy cierto @rtobar, gracias 🎉
