### ISSUE TITLE
Translate `library/curses.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2569]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/curses.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/curses.po`:

* Fuzzy: 15
* Percent translated: 98.0%
* Entries: 637 / 650
* Untranslated: 13

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by rtobar** [comment]
Adelante @juanjosaurio , bienvenido y muchas gracias por el interés!

**Comment by juanjosaurio** [comment]
No es abandono, es el fin de año y comenzar un trabajo nuevo. Si esta semana no logro iniciar, te aviso para que lo reasignes.
Gracias

**Comment by cmaureir** [comment]
:warning:  Cerrando este issue para poder tener uno actualizado luego de la migración a 3.13
