### ISSUE TITLE
Translate `library/timeit.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2570]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/timeit.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/timeit.po`:

* Fuzzy: 1
* Percent translated: 94.6%
* Entries: 53 / 56
* Untranslated: 3

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by jcaalzago** [comment]
¿Puedo ayudar en esta traducción?

**Comment by khushi-98** [comment]
I want to work on this error.

**Comment by carlosm00** [comment]
Buenas! Puedo trabajar en este issue? Gracias de antemano.

**Comment by cacrespo** [comment]
Dale para adelante @carlosm00 ! :muscle:

**Comment by carlosm00** [comment]
Muchas gracias @cacrespo!!
