### ISSUE TITLE
Translate `library/chunk.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2571]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/chunk.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/chunk.po`:

* Fuzzy: 0
* Percent translated: 87.2%
* Entries: 34 / 39
* Untranslated: 5

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by khushi-98** [comment]
i would like to solve this error.

**Comment by carlosm00** [comment]
Buenas,
Lo mismo por aquí, no veo que esté todavía asignado a nadie, así que con gusto me ofrezco voluntario para este issue también.
Gracias de antemano.
Un saludo.

**Comment by mmmarcos** [comment]
@carlosm00 todo tuyo!
