### ISSUE TITLE
Translate `library/doctest.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2572]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/doctest.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/doctest.po`:

* Fuzzy: 1
* Percent translated: 97.1%
* Entries: 305 / 314
* Untranslated: 9

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by jcaalzago** [comment]
¿Puedo ayudar en esta traducción?

**Comment by khushi-98** [comment]
Give me a chance to solve this problem.

**Comment by carlosm00** [comment]
Buenas,
Me preguntaba si puedo contribuir en este issue. 
Gracias de antemano.

**Comment by mmmarcos** [comment]
@carlosm00 gracias a vos de antemano, ahí te asigné el issue :)
