### ISSUE TITLE
Translate `library/idle.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2573]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/idle.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/idle.po`:

* Fuzzy: 8
* Percent translated: 99.7%
* Entries: 288 / 289
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by FarhaKousar1601** [comment]
# English version checked and translated 100% #2573

**Comment by oicaroabreu** [comment]
¡Me gustaría mucho empezar en este proyecto! ¿Puedes asignarme este issue? @rtobar me recomendó empezar poco a poco jaja

**Comment by rtobar** [comment]
Ahora sí @oicaroabreu, un punto de partida mucho más manejable, ¡muchas gracias por el entusiasmo!

**Comment by oicaroabreu** [comment]
Tengo una duda, no encuentro las expresiones 'fuzzy' en la documentación en inglés para comparar el contexto. ¿Debo hacerlas de manera normal? ¿Qué recomiendas?

<img width="896" alt="image" src="https://github.com/python/python-docs-es/assets/136408366/b9cf9935-54fd-4213-83e8-493b7d7fc4dd">

**Comment by rtobar** [comment]
No estoy 100% seguro, pero pareciera ser que te encontraste con traducciones que se refieren a entradas que van hacia el índice global, las cuales hemos decidido dejar "traducidas" al inglés. En https://github.com/python/python-docs-es/pull/2706 hay una buena descripción al respecto, y de hecho hace poco incorporamos a la rama 3.12 (gracias a ese PR) un script que te puede ayudar a identificar esas entradas, y lidiar con ellas.

Échale un vistazo, y dinos si tienes más problemas. Si tienes ya más o menos listos los cambios también puedes abrir desde ya un PR y ahí podemos discutir directamente sobre los cambios, en vez de hacerlo acá en el issue donde los demás no pueden ver los cambios que has realizado.
