### ISSUE TITLE
Translate `library/smtplib.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2591]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/smtplib.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/smtplib.po`:

* Fuzzy: 10
* Percent translated: 97.4%
* Entries: 114 / 117
* Untranslated: 3

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by dporta97** [comment]
Buenas tardes! 
¿Podría acabar de traducir esta issue?
Gracias!

**Comment by rtobar** [comment]
Muchas gracias @dporta97!

Sí, la tabla la primera vez que aparece no arroja siempre los resultados que debería, pero a la segunda vez ya empieza a ver bien -- es algo que tenemos que arreglar por nuestro lado.

Lamentablemente no he tenido tiempo para dedicarme a revisar varias de las traducciones que están esperando revisión, pero ya pasaré (o alguien más) por la tuya e iremos dejando comentarios de ser necesario.

**Comment by dporta97** [comment]
Estoy a la espera de la validación de #2753

**Comment by dporta97** [comment]
Estoy a la espera de la validación de #2753
