### ISSUE TITLE
Translate `library/tkinter.tix.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2592]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/tkinter.tix.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/tkinter.tix.po`:

* Fuzzy: 34
* Percent translated: 98.6%
* Entries: 71 / 72
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by AYUSHMOHANTY10** [comment]
I want !!

**Comment by cmaureir** [comment]
gracias por el interés @AYUSHMOHANTY10 pero estamos considerando solo a personas con buen nivel de español, o personas nativas.

**Comment by jcaalzago** [comment]
¿Puedo ayudar en este fichero?
