### ISSUE TITLE
Translate `library/runpy.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2595]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/runpy.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/runpy.po`:

* Fuzzy: 9
* Percent translated: 90.0%
* Entries: 36 / 40
* Untranslated: 4

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by rohit27-2** [comment]
Hey cmaureir, I would like to take this up.

**Comment by Sublian** [comment]
Me gustaria colaborar con este archivo

**Comment by rtobar** [comment]
Adelante @Sublian
