### ISSUE TITLE
Translate `library/tkinter.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#260]
This needs to reach 100% translated.

Current stats for `library/tkinter.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 268
- Untranslated: 268

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by cacrespo** [comment]
Lo tomo! No le tengo miedo 😄

**Comment by humitos** [comment]
Esaaaa! Adelante
