### ISSUE TITLE
Translate `library/audioop.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2603]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/audioop.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/audioop.po`:

* Fuzzy: 0
* Percent translated: 92.0%
* Entries: 46 / 50
* Untranslated: 4

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by carlosm00** [comment]
Hi team,
Is this still open? I would like to contribute.
Regards.

**Comment by rtobar** [comment]
Hola @carlosm00, gracias por el ánimo :+1:. ¿Podrías confirmar brevemente que hablas Español de forma nativa, o avanzada? Estamos tratando de priorizar gente que hable de forma nativa o avanzada. Si es así, ningún problema y te asigno el issue.

**Comment by carlosm00** [comment]
Buenas @rtobar, gracias por tu respuesta tan rápida. Así es, el español es mi lengua materna. Espero que sea confirmación suficiente 😃.

**Comment by rtobar** [comment]
Gracias por la confirmación, todo tuyo @carlosm00, y éxito con tu primera contribución 👍
