### ISSUE TITLE
Translate `library/sys.monitoring.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2606]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/sys.monitoring.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/sys.monitoring.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 104
* Untranslated: 104

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Alfareiza** [comment]
@cmaureir Me asignas esta por favor, vámonos con algo totalmente nuevo.

**Comment by rtobar** [comment]
Ese es el espíritu @Alfareiza 🚀
