### ISSUE TITLE
Translate `library/gc.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2609]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/gc.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/gc.po`:

* Fuzzy: 1
* Percent translated: 94.8%
* Entries: 55 / 58
* Untranslated: 3

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Snehaaa18** [comment]
please assign me this issue

**Comment by thegeekyyyy** [comment]
can you assign me this

**Comment by martorelli617** [comment]
Saludos, me gustaría traducir este archivo.

**Comment by cmaureir** [comment]
@thegeekyyyy @Snehaaa18 :wave: hola, como este proyecto es la traducción de la documentación al Español, estamos dando la posibilidad a que las personas que hablan el idioma de forma nativa puedan hacer las traducciones. Muchas gracias por su interés!
