### ISSUE TITLE
Translate `library/re.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#261]
This needs to reach 100% translated.

Current stats for `library/re.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 286
- Untranslated: 286

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by MiguelHeCa** [comment]
Hi! I'd like to contribute translating this file.

**Comment by raulcd** [comment]
Thanks @MiguelHeCa , assigned

**Comment by MiguelHeCa** [comment]
Great, thanks!
