### ISSUE TITLE
Translate `library/argparse.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#262]
This needs to reach 100% translated.

Current stats for `library/argparse.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 277
- Untranslated: 277

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Qkolnek** [comment]
¿Puedo trabajar en este archivo?

**Comment by humitos** [comment]
Adelante!

**Comment by humitos** [comment]
Hola @Qkolnek ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by Qkolnek** [comment]
Acabo de hacer el PR en Draft. Tengo el archivo traducido al 40%.
