### ISSUE TITLE
Translate `library/stdtypes.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2622]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/stdtypes.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/stdtypes.po`:

* Fuzzy: 104
* Percent translated: 90.0%
* Entries: 1102 / 1225
* Untranslated: 123

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by annezao** [comment]
hey, can i help with this issue?

**Comment by cmaureir** [comment]
Lo mismo acá, si me aclaras en la otra issue que hablas español, te las asignamos!

**Comment by jcaalzago** [comment]
¿Puedo ayudar en la traducción de este fichero?

**Comment by rtobar** [comment]
Adelante @jcaalzago, muchas gracias! Recuerda agregarte también al archivo `TRANSLATORS` si quieres aparecer listado

**Comment by rtobar** [comment]
Perdón @jcaalzago por asignarte este issue y después quitártelo. No me fijé al asignártelo, pero este archivo cuenta con más de 200 entradas en las que hay que trabajar, lo que no es recomendable para alguien que está haciendo su primera contribución. Por otro lado #2550 es más apropriado, así que te dejo ese asignado.

**Comment by jcaalzago** [comment]
Hola, ¿me la pueden asignar ahora?

**Comment by cmaureir** [comment]
:warning:  Cerrando este issue para poder tener uno actualizado luego de la migración a 3.13
