### ISSUE TITLE
Translate `library/atexit.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2625]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/atexit.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/atexit.po`:

* Fuzzy: 0
* Percent translated: 84.2%
* Entries: 16 / 19
* Untranslated: 3

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Sublian** [comment]
Saludos, me gustaria traducir este archivo

**Comment by rtobar** [comment]
Vi que leíste mi mensaje en el otro issue, pero dejo acá el comentario por claridad para quien entre a leer los comentarios por acá: mejor no asignarte este issue ahora y tratar de limitar la cantidad de trabajo que tienes andado en paralelo. Ya cuando vayas cerrando otros issues felizmente te podemos asignar este u otro mas

**Comment by Sublian** [comment]
Saludos... Listo para asumir nuevos issues

**Comment by rtobar** [comment]
Todo tuyo @Sublian!

**Comment by Sublian** [comment]
Saludos, en esta traducción me encontre con una palabra que puede generar ciertos problemas en la traducción, traceback que si bien puede definirse como un rastreo o seguimiento.
Desde ya estare atento a las revisiones
