### ISSUE TITLE
Translate `library/copy.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2628]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/copy.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/copy.po`:

* Fuzzy: 1
* Percent translated: 84.6%
* Entries: 22 / 26
* Untranslated: 4

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Sublian** [comment]
Saludos, me agradaria apoyar con este archivo

**Comment by rtobar** [comment]
Listo! Recuerda tratar de no sobrecargarte con muchas traducciones en paralelo, con esta van dos que van a estar en progreso al mismo tiempo, t mmy es fácil confundirse. Te recomiendo que termines esta y la otra que ya tienes asignada antes de pedir otra más -- y descuida, hay aún mucho trabajo por realizar 😊

**Comment by Sublian** [comment]
Perfecto muchas gracias, tomare en cuenta tu recomendación.
