### ISSUE TITLE
Translate `library/math.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2629]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/library/math.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/math.po`:

* Fuzzy: 6
* Percent translated: 96.8%
* Entries: 122 / 126
* Untranslated: 4

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Ritwik1607** [comment]
Dear admin,
It would be great if you assign this issue to me.I am highly interested in this project and would love to contribute to it.

**Comment by rtobar** [comment]
> Dear admin, It would be great if you assign this issue to me.I am highly interested in this project and would love to contribute to it.

Hola @Ritwik1607  ¿sabes español? idealmente la traducción está enfocada a personas que tengan un buen nivel para que no hayan artefactos de las traducciones automáticas.

**Comment by martorelli617** [comment]
Me gustaría traducir este archivo.

**Comment by rtobar** [comment]
Gracias @martorelli617!
