### ISSUE TITLE
Translate `library/exceptions.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#263]
This needs to reach 100% translated.

Current stats for `library/exceptions.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 127
- Untranslated: 127

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Roluisker** [comment]
Hii, I would like to work in this issue

**Comment by humitos** [comment]
@Roluisker excellent! Enjoy working on this translation! :smile:
