### ISSUE TITLE
Translate `faq/design.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2632]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/faq/design.html once translated.
Meanwhile, the English version is shown.

Current stats for `faq/design.po`:

* Fuzzy: 21
* Percent translated: 99.3%
* Entries: 141 / 142
* Untranslated: 1

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by namansharma18899** [comment]
Hey I would be intersted in resolving this. Can you guys assign the issue to me, thanks.

**Comment by cmaureir** [comment]
> Hey I would be intersted in resolving this. Can you guys assign the issue to me, thanks.

Hola @namansharma18899 ¿sabes español? idealmente la traducción está enfocada a personas que tengan un buen nivel para que no hayan artefactos de las traducciones automáticas.

**Comment by namansharma18899** [comment]
Yeah I don't think I'am the best man for the job 😅

**Comment by cmaureir** [comment]
Hola @Manikantan-S :wave: gracias por tu mensaje. Desafortunadamente tu mensaje tiene un par de errores gramaticales, con lo que no sé si tendrás el nivel necesario. Lo que si podrías mirar es alguna issue que tenga menos frases por revisar, por ejemplo, esta a pesar de tener una entrada para traducir, tiene 21 entradas fuzzy que requieren atención detallada para ver los cambios.

**Comment by Manikantan-S** [comment]
Ok

**Comment by martorelli617** [comment]
Saludos, me gustaría traducir este archivo.

**Comment by rtobar** [comment]
Adelante @martorelli617 👍
