### ISSUE TITLE
Translate `reference/lexical_analysis.po`

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#2644]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.12/reference/lexical_analysis.html once translated.
Meanwhile, the English version is shown.

Current stats for `reference/lexical_analysis.po`:

* Fuzzy: 55
* Percent translated: 76.7%
* Entries: 240 / 313
* Untranslated: 73

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by rodpoblete** [comment]
Me gustaría tomar esta issue 🙋

**Comment by rtobar** [comment]
@rodpoblete no creo que haya problems en que hagas esta traducción, pero ya tienes un issue grande bajo el brazo con 40 entradas por traducir, ¿quizás sea buena idea ir de a uno? Espero tu confirmación para proseguir

**Comment by rodpoblete** [comment]
> @rodpoblete no creo que haya problems en que hagas esta traducción, pero ya tienes un issue grande bajo el brazo con 40 entradas por traducir, ¿quizás sea buena idea ir de a uno? Espero tu confirmación para proseguir.
> 
> Y muchas gracias por las ganas!!!

Ningún problema. Cuando termina la otra prosigo con esta :)

**Comment by jcaalzago** [comment]
¿Puedo ayudar en esta issue?

**Comment by cmaureir** [comment]
:warning:  Cerrando este issue para poder tener uno actualizado luego de la migración a 3.13
