### ISSUE TITLE
Translate `library/logging.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#265]
This needs to reach 100% translated.

Current stats for `library/logging.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 311
- Untranslated: 311

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Roluisker** [comment]
Hola, want help with this issue :) .

**Comment by humitos** [comment]
Sure! Thanks. Enjoy

**Comment by humitos** [comment]
Hola @Roluisker ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by Roluisker** [comment]
Hola @humitos!. 
Si he adelantado una parte, gracias por la idea. Voy a revisar que no tenga problemas adelanto algo mas y subo el Draft :)

**Comment by cmaureir** [comment]
@Roluisker  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by cmaureir** [comment]
@Roluisker si te parece bien, le asignaremos  esto a otra persona por la inactividad. Sería genial que subieras un draft de lo que llevas para que tu contenido no se pierda.

**Comment by cacrespo** [comment]
Buenas! @cmaureir quisiera tomar este archivo!
Veo que en el fork de @Roluisker ya hay un avance así que podemos continuarlo.

Saludos,

**Comment by cmaureir** [comment]
@cacrespo adelante! pero no sé si podemos llegar y copiarlo, ya que @Roluisker no nos ha dicho nada. Quizás te puedes intentar contactar con el a ver si puede subir un draft de su parte, y tu solo lo continuas en otro PR
