### ISSUE TITLE
Seguir mejorando la memoria

### ISSUE THREAD

**Issue by hectorcanto** [python/python-docs-es#269]
Continua #83 

Añadir links a diccionarios y glosarios:
- Wordreference
- Linguee
- Iate
- Panhispanico de dudas
- Glosario Ruby (otros?)

**Comment by clacri** [comment]
@hectorcanto creo que esta issue ya se puede cerrar que no se hizoa utomaticamente con tu pr, cierto?

**Comment by cmaureir** [comment]
Yo creo que si, y si aparece alguna otra mejora abrimos otra Issue.
