### ISSUE TITLE
Set minimal workflow permissions

### ISSUE THREAD

**Issue by pnacht** [python/python-docs-es#2772]
This repo's automated workflows currently run with write-all tokens. This puts the project at risk of supply-chain attacks. [GitHub](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-secrets) recommends ensuring all workflows run with minimal permissions.

I've taken a look at the workflows and they don't need such broad permissions.

This issue can be solved in two ways:
- add top-level read-only permissions to all workflows; and/or
- set the default token permissions to read-only in the repo settings.

I'll be sending a PR along with this issue that sets the top-level permissions (and grants additional permissions for the jobs that need them). If you instead (or also) wish to modify the default token permissions:

1. Open the repo settings
2. Go to [Actions > General](https://github.com/python/python-docs-es/settings/actions)
3. Under "Workflow permissions", set them to "Read repository contents and packages permissions"

---

**Disclosure:** My name is Pedro and I work with Google and the [Open Source Security Foundation](https://openssf.org) to improve the supply-chain security of important open-source projects.

**Comment by mmmarcos** [comment]
Thanks for the contribution and the details about the issue. 

Changing default token permissions sounds like a good idea too. I do not have maintainer role for this repo, so @cmaureir @rtobar what do you think?

**Comment by rtobar** [comment]
I don't have a maintainer role either, and I also don't know who actually does -- I suspect @cmaureir does though. Otherwise we can ask in our Telegram group.

I left a minor comment in the PR, but overall I'm pretty happy with the changes. Like I said in the PR, I'll follow suit in other projects I maintain, I definitely like having a more strict token by default and avoid security risks.

**Comment by cmaureir** [comment]
Thanks for your contribution :)

> I'll be sending a PR along with this issue that sets the top-level permissions (and grants additional permissions for the jobs that need them). If you instead (or also) wish to modify the default token permissions:
> 
>     1. Open the repo settings
> 
>     2. Go to [Actions > General](https://github.com/python/python-docs-es/settings/actions)
> 
>     3. Under "Workflow permissions", set them to "Read repository contents and packages permissions"

This is now done :tada:
