### ISSUE TITLE
Homogeneizar las traducciones de `// y floor division` a "división entera a la baja"

### ISSUE THREAD

**Issue by jcaalzago** [python/python-docs-es#2797]
Como motivo de la votación realizada en telegram en la que se consideraba el cambio en la traducción de `floor division` y `//` propuesto en la [issue 2754](https://github.com/python/python-docs-es/issues/2754), en la que el resultado de la misma fue:

![imagen](https://github.com/python/python-docs-es/assets/2773907/d100c7b1-7367-43ac-8046-c308e3a83f13)

Realizo un listado de los ficheros en los que se hace mención a estos términos (puede sufrir algún cambio, en caso que falte o sobre alguno):

- [x]  ~~https://docs.python.org/es/3.12/c-api/number.html~~ [PR 2799](https://github.com/python/python-docs-es/pull/2799) 
- [x] ~~https://docs.python.org/es/3.12/faq/programming.html~~ [PR 2799](https://github.com/python/python-docs-es/pull/2799)
- [x] ~~https://docs.python.org/es/3.12/glossary.html~~ [PR 2812](https://github.com/python/python-docs-es/pull/2812) 
- [x] ~~https://docs.python.org/es/3.12/howto/pyporting.html~~ [PR 2812](https://github.com/python/python-docs-es/pull/2812)
- [x] ~~https://docs.python.org/es/3.12/library/datetime.html~~ [PR 2801](https://github.com/python/python-docs-es/pull/2801)
- [x] ~~https://docs.python.org/es/3.12/library/decimal.html~~ * fuera del alcance de esta issue 
- [x] ~~https://docs.python.org/es/3.12/library/stdtypes.html~~ [PR 2800](https://github.com/python/python-docs-es/pull/2800)
- [x] ~~https://docs.python.org/es/3.12/reference/expressions.html~~ [PR 2800](https://github.com/python/python-docs-es/pull/2800)
- [x] ~~https://docs.python.org/es/3.12/tutorial/introduction.html~~ **ningún cambio necesario @jcaalzago
- [x] ~~https://docs.python.org/es/3.12/whatsnew/2.2.html~~ [PR 2801](https://github.com/python/python-docs-es/pull/2801)
- [x] ~~https://docs.python.org/es/3.12/whatsnew/2.6.html~~ [PR 2801](https://github.com/python/python-docs-es/pull/2801)
- [x] ~~https://docs.python.org/es/3.12/whatsnew/3.9.html~~ [PR 2798](https://github.com/python/python-docs-es/pull/2798)
- [x] ~~https://docs.python.org/es/3.12/whatsnew/3.11.html~~ [PR 2798](https://github.com/python/python-docs-es/pull/2798)
- [x] ~~También hay que añadir el operador `//` y el término `floor division` a la memoria de traducción.~~ [PR 2808](https://github.com/python/python-docs-es/pull/2808) 

El término de `floor division` en el módulo `decimal` es distinto, y se acordó no tocarlo en este momento.

**Comment by MateoCamara** [comment]
Venga, yo me puedo encargar. Esta sería mi segunda contribución.

**Comment by cacrespo** [comment]
:clap: :clap: :clap: 
Muy bueno el listado con los files a trabajar @jcaalzago. Lo retoqué un poquito.

Les recuerdo el paso a paso para contribuir está [aquí](https://python-docs-es.readthedocs.io/es/3.12/CONTRIBUTING.html)

¿Les parece si vamos mencionando en el primer comentario los files que vamos trabajando? (me adelanté y les asigné 2 a cada uno :P) 

¡Muy buen trabajo!

**Comment by jcaalzago** [comment]
¿Creamos una PR por cada fichero?

**Comment by cacrespo** [comment]
> @cacrespo ¿Creamos una PR por cada fichero?

La verdad que es lo mismo... son cambios tan chiquitos que tal vez vale la pena juntar varios en un sólo PR y ya.
[Acá](https://github.com/python/python-docs-es/pull/2798) corregí los últimos dos. Si alguno puede hacer el review así mergeamos sería estupendo.

**Comment by jcaalzago** [comment]
> > @cacrespo ¿Creamos una PR por cada fichero?
> 
> La verdad que es lo mismo... son cambios tan chiquitos que tal vez vale la pena juntar varios en un sólo PR y ya. [Acá](https://github.com/python/python-docs-es/pull/2798) corregí los últimos dos. Si alguno puede hacer el review así mergeamos sería estupendo.

Creo que ya la revisé (es la primera vez que hago revisión). 
También he creado 3 PR para el resto de ficheros que quedaban pendientes (menos la memoria de traducción).

Cuando podáis revisadme las PR.

**Comment by cacrespo** [comment]
Hola @MateoCamara, ¿has podido avanzar con los ajustes que tenías asignados? Sólo nos faltan esos dos ajustes y terminamos :partying_face:

**Comment by jcaalzago** [comment]
> Muy buenas!! No estaba seguro de si finalmente tenía yo asignado parte, sorry! Me pongo con ello :)

Ya se terminaron todas las tareas de esta issue, ¿no? Lo digo para cerrarla

**Comment by MateoCamara** [comment]
> > Muy buenas!! No estaba seguro de si finalmente tenía yo asignado parte, sorry! Me pongo con ello :)
> 
> Ya se terminaron todas las tareas de esta issue, ¿no? Lo digo para cerrarla

Están terminadas, sí! 👍
