### ISSUE TITLE
Extraer bigramas y n-gramas para uniformizar las traducciones

### ISSUE THREAD

**Issue by hectorcanto** [python/python-docs-es#280]
Muchas de las traducciones más difíciles y representativas son bigramas o n-gramas como p.e. "helper function".

Para traducirlas de manera consistente se propone utilizar una herramienta NLP, como por ejemplo NLTK o Spacy, para identificar las expresiones más recurrentes y comprobarlas.

Una vez identificados, se decidirá una traducción preferente y se substituirá en la mayor parte de sitios posibles.

**Comment by humitos** [comment]
@hectorcanto ¿qué pasó que lo cerraste?

**Comment by hectorcanto** [comment]
fue sin querer o algo automatico @humitos

**Comment by humitos** [comment]
Esto es/era una buena idea. Sin embargo, el issue lleva abierto 2 años y parece que no hubo tracción necesaria para llevarlo adelante. De cualquier forma, si hay alguien interesado en hacerlo se puede re-abrir.
