### ISSUE TITLE
Aclaración sobre entradas del índice en library/string.po

### ISSUE THREAD

**Issue by carlosm00** [python/python-docs-es#2813]
Buenas,
Tras la aclaración en https://github.com/python/python-docs-es/pull/2810#discussion_r1475208674, volví al fichero que usé como referencia y me di cuenta que estas entradas del índice sí aparecen traducidas. Nadé un poco entre PRs e Issues y encontré que en el comentario https://github.com/python/python-docs-es/pull/2667#pullrequestreview-1678225076 sí se sugieren traducciones a estos. Asimismo, encontré el mensaje [del grupo de telegram](https://t.me/python_docs_es/21686) mencionado en https://github.com/python/python-docs-es/pull/2706. 
Tras todo esto, me pregunto si estas entradas en library/string.po no se deben traducir o si este caso es especial al tratarse del artículo sobre _strings_. 
En caso de no deber traducirse, ya creé una [branch en mi fork con las entradas en inglés](https://github.com/carlosm00/python-docs-es/tree/correccion-string) para reducir el trabajo, quedando por completar las dos líneas fuzzy (con las que también me presentaría voluntario para traducirlas y presentarlo todo en un único PR).

Dicho esto, espero no molestar y que este issue sea útil para el proyecto, aunque sea sólo para aclarar esto 😄.
Saludos.

**Comment by cacrespo** [comment]
@carlosm00 ya casi casi tenés domada a la bestia! Para mi estás en condiciones de ser declarado "**Amo y Señor de los Índices**".

Van mis dos centavos:
Es un tema muy particular. Si bien hay una regla general (la que discutimos y votamos en el grupo de Telegram) yo creo que es cuestión de ver el caso específico y decidir sobre eso con más o menos sensatez.

Por ejemplo, fijate en la imagen. Yo creo que lo más conveniente ahí es unificar al español porque no refieren a Clases o Métodos sino al símbolo concreto. Más allá de los matices ningún hispanoparlante dice "curly brackets" ;-)

![image](https://github.com/python/python-docs-es/assets/10950697/1cc4c274-f2d8-4e9d-a23a-d83a53a42951)

De todos modos, lo dejo a tu criterio. Estás haciendo un trabajo espectacular :rocket: :rocket: :rocket:

**Comment by carlosm00** [comment]
Hola @cacrespo , 
Siento la respuesta tan tardía, pero mil gracias por tu apoyo 😄. Me gusta tu explicación y me parece que tiene bastante sentido, sobre todo para este caso en particular. Gracias por la aclaración! De este modo, procedo a cerrar este issue. De nuevo, gracias por tu tiempo, apoyo y colaboración, es un placer colaborar en este proyecto.
