### ISSUE TITLE
Error in Spanish translation

### ISSUE THREAD

**Issue by MelchDev** [python/python-docs-es#2827]
In the Spanish versión of [Tipos secuencia — list, tuple, range](https://docs.python.org/es/3/library/stdtypes.html#sequence-types-list-tuple-range) The first Table has an error:

<img width="599" alt="image" src="https://github.com/user-attachments/assets/8f7747be-91da-4f0c-bf26-389e03ca6cfe">

It will be "el segmento de _s_ desde _i_ hasta _j_, con paso _k_"

**Comment by cacrespo** [comment]
Muchas gracias por reportarlo @MelchDev. ¿Te animás a hacer el PR para corregirlo?
Es super fácil, [acá](https://python-docs-es.readthedocs.io/es/3.12/CONTRIBUTING.html) tenés una guía paso a paso para hacerlo.

Cualquier duda que tengas, escribí sin problemas.
