### ISSUE TITLE
Translate `library/unittest.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#285]
This needs to reach 100% translated.

Current stats for `library/unittest.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 497
- Untranslated: 497

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by rapto** [comment]
Puedo intentarlo yo

**Comment by humitos** [comment]
Adelante! Que lo disfrutes!

**Comment by humitos** [comment]
Hola @rapto! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by rapto** [comment]
No lo olvido, se me ha complicado la vida. Voy subiendo lo que tengo.
