### ISSUE TITLE
Translate `library/time.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#286]
This needs to reach 100% translated.

Current stats for `library/time.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 231
- Untranslated: 231

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Juancacorps** [comment]
Hoy comencé a traducir esta librería
.

**Comment by humitos** [comment]
Hola @Juancacorps ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by Juancacorps** [comment]
Hola buenas noches, sigo avanzando en la traducción.

**Comment by cmaureir** [comment]
@Juancacorps  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by Juancacorps** [comment]
Ya hice mi git push hace tiempos

**Comment by cmaureir** [comment]
Hola @Juancacorps, estás seguro que abriste un Pull-request?
no existe nada con tu usuario en la lista, ni abierto, ni cerrado: https://github.com/python/python-docs-es/pulls?q=is%3Apr+Juancacorps
Quizás solo lo hiciste en tu fork?

**Comment by cmaureir** [comment]
En tu fork encontré una rama que se llama 'traduccion-time' https://github.com/Juancacorps/python-docs-es/blob/traduccion-time/library/time.po Pero eso nunca fue abierto como Pull-request acá :(

**Comment by Juancacorps** [comment]
😳
