### ISSUE TITLE
Translate `library/string.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#287]
This needs to reach 100% translated.

Current stats for `library/string.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 172
- Untranslated: 172

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by fabridamicelli** [comment]
a este me le animo :)

**Comment by humitos** [comment]
Adelante! Que lo disfrutes

**Comment by humitos** [comment]
Hola @fabridamicelli ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by fabridamicelli** [comment]
Hola @humitos! 
Avancé un trecho pero aún falta. 
Me parece buena idea lo del draft PR.  Ahí lo mando así le pueden dar un vistazo y ayudarme a corregir antes de que meta la pata del todo :)
