### ISSUE TITLE
Translate `library/multiprocessing.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#299]
This needs to reach 100% translated.

Current stats for `library/multiprocessing.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 509
- Untranslated: 509

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by mjmolina** [comment]
Me encanta este módulo, lo uso a menudo y me encantaría traducirlo.

**Comment by humitos** [comment]
@mjmolina ¡Excelente! Nadie mejor que vos para hacerlo entonces :smile:

**Comment by humitos** [comment]
Hola @mjmolina ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by mjmolina** [comment]
Hola! 
Muchas gracias por preocuparte :) !! 
El "goal" de mi fin de semana es acabar estas traducciones :), con lo que estoy trabajando a tope en ello! Haré el PR muy pronto.
