### ISSUE TITLE
Translate `library/itertools.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#301]
This needs to reach 100% translated.

Current stats for `library/itertools.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 147
- Untranslated: 147

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by jcpmmx** [comment]
@humitos soy nuevo por acá y me gustaría echarle un ojo al proceso para poder ayudar.
Saludos!

**Comment by humitos** [comment]
Hola @jcpmmx! Adelante! Recordá seguir los pasos de la guía de contribución :smile: --te asigno este issue a vos. Que lo disfrutes!

**Comment by jcpmmx** [comment]
Sorry for the silence here.
WIP.

**Comment by humitos** [comment]
Great! If you want, you can open a PR as Draft with what you have already

**Comment by jcpmmx** [comment]
Almost done!

BTW, which language is the official here for discussions, commit messages, PRs?

**Comment by humitos** [comment]
Whatever you like the most 😬

I try to use English so it's useful for other translators in another languages
