### ISSUE TITLE
Translate `using/windows.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#302]
This needs to reach 100% translated.

Current stats for `using/windows.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 310
- Untranslated: 310

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by itrjwyss** [comment]
Quiero trabajar en esta traducción.

**Comment by humitos** [comment]
Yaaaaay! Bienvenida! Espero que disfrutes traduciendo este archivo. Muchas gracias!

**Comment by humitos** [comment]
Hola @itrjwyss ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by itrjwyss** [comment]
Hola @humitos, había entendido que se subía todo. Y la semana pasada estuve en las previas a lanzamiento de una nueva aplicación. Pero voy subiendo lo que tengo.

**Comment by cmaureir** [comment]
@itrjwyss  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by cmaureir** [comment]
@itrjwyss podrías subir lo que avanzaste? nos gustaría asignar esto a otra persona, pero no nos gustaria que se perdiera todo tu trabajo.

**Comment by kiolo45** [comment]
Quisiera trabajar en esta traducción.

**Comment by fzuccolo** [comment]
Hola, me gustaría traducir este archivo, gracias!

**Comment by cmaureir** [comment]
Se me había pasado esta issue por completo, mil disculpas!
Te lo asigné a ti @kiolo45, en caso que no puedas o no quieras tomarlo ahora 28 días más tarde, avisame así se lo puedo asignar a @fzuccolo .

**Comment by cmaureir** [comment]
@fzuccolo te interesa tomar esta issue?

**Comment by fzuccolo** [comment]
Sí por supuesto!

**Comment by cmaureir** [comment]
Si es tu primera issue, te recomiendo que puedas mirar otras que tengan menos entradas, pues esta es bastaaaaaante larga.
Te la dejo asignada igual, pero avisame si prefieres quedarte con una más pequeña
