### ISSUE TITLE
Translate `library/runpy.po`

### ISSUE THREAD

**Issue by sofide** [python/python-docs-es#3028]
This file is 75% translated and needs to reach 100%.

The rendered version of this file will be available at https://docs.python.org/es/3.13/library/runpy.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/runpy.po`:

- Total entries: 40

- Entries that need work: 10 - (25%)
  - Fuzzy: 10
  - Untranslated: 0

Please, comment here if you want this file to be assigned to you and a member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by xooseph** [comment]
Hola. Podría empezar a traducir para la 3.13 con este issue? 🤞
