### ISSUE TITLE
Translate `library/math.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#303]
This needs to reach 100% translated.

Current stats for `library/math.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 97
- Untranslated: 97

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by lasr21** [comment]
I'm in, I have experience localizing Firefox es-MX

**Comment by humitos** [comment]
Excellent! Enjoy!

**Comment by humitos** [comment]
Hola @lasr21 ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by lasr21** [comment]
Ya casi, acabo en un par de dias hago el PR para revisión :)

**Comment by cmaureir** [comment]
@lasr21  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by cmaureir** [comment]
@lasr21 podrías subir lo que alcanzaste a subir? nos gustaría asignar este archivo a otra persona, pero sin que se pierda lo que lograste hacer.

**Comment by fjsevilla-dev** [comment]
Quisiera tomar este ;)

**Comment by cmaureir** [comment]
Que máquina @fjsevilla-dev :tada: :muscle: :snake:
