### ISSUE TITLE
Translate `reference/datamodel.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#304]
This needs to reach 100% translated.

Current stats for `reference/datamodel.po`:

- Fuzzy: 0
- Percent translated: 24%
- Entries: 111 / 448
- Untranslated: 337

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by c0x6a** [comment]
Can I have this one now? :)

**Comment by humitos** [comment]
@c0x6a all yours! thanks of your time!

**Comment by humitos** [comment]
Hola @c0x6a ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by c0x6a** [comment]
hola @humitos ... sí justo ayer abrí un PR, el #402

**Comment by cmaureir** [comment]
@c0x6a  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by c0x6a** [comment]
> @c0x6a te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

hola, tuve un "issue" con el COVID, ahora estoy mejor, voy a seguir viendo la traducción de este archivo  🤟🏻

**Comment by cmaureir** [comment]
@c0x6a te podemos ayudar con algo? no sé si lograste avanzar un poco más la traducción del archivo, pero si tienes algo, no nos gustaría que se perdiera ;)

**Comment by migrmrz** [comment]
Hola, ¿podría continuar con este issue? Veo que es largo, pero podría trabajar por secciones más pequeñas, así no esperamos hasta que alguien termine todo y también da oportunidad de que alguien más que quiera ayudar, pueda trabajarlo.

**Comment by cmaureir** [comment]
Dale @migrmrz, éxito!

**Comment by migrmrz** [comment]
¡gracias!
