### ISSUE TITLE
Translate `library/threading.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#305]
This needs to reach 100% translated.

Current stats for `library/threading.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 198
- Untranslated: 198

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by GabrielAnguita** [comment]
yo quisiera darle con esta!

**Comment by humitos** [comment]
@GabrielAnguita muchas gracias! adelante!
