### ISSUE TITLE
Translate `library/turtle.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#306]
This needs to reach 100% translated.

Current stats for `library/turtle.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 514
- Untranslated: 514

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by alvarmaciel** [comment]
Puedo esta? me estoy matando con turtle y jupyter lab /notebook me vendŕia bien

**Comment by humitos** [comment]
Muy bien! Adelante @alvarmaciel! Muchas gracias :smile:
