### ISSUE TITLE
Translate `library/pickle.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#307]
This needs to reach 100% translated.

Current stats for `library/pickle.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 205
- Untranslated: 205

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by manuelramos** [comment]
Hola @humitos , me gustaría colaborar con la traducción de este. Saludos

**Comment by humitos** [comment]
@manuelramos Hola tocayo! Adelante! Todo suyo --qué lo disfrutes!

**Comment by humitos** [comment]
Hola @manuelramos ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by manuelramos** [comment]
Hola @humitos, si, estoy avanzando con el archivo a paso lento eso si (unos meses complicados en cuanto a tiempo). Por el momento no necesito ayuda, pero seguro la pediré en caso de que si la necesite, en el chat. Gracias por la idea del Draft PR, lo voy a hacer con lo que tengo hasta el momento. Avísame si hay algún deadline o alguna preferencia de tiempos asi me hago mas tiempo y me apuro a terminarlo :) Gracias.

**Comment by humitos** [comment]
Genial! No hay deadline, pero voy haciendo un seguimiento del estado de los issues para saber como estamos y ver si la gente necesita ayuda. Gracias!
