### ISSUE TITLE
Translate `library/enum.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#308]
This needs to reach 100% translated.

Current stats for `library/enum.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 179
- Untranslated: 179

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by katialira** [comment]
Este puede ser para mi :D

**Comment by humitos** [comment]
Yaaaaay! Bienvenida de nuevo :wink:

**Comment by humitos** [comment]
Hola @katialira ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.
