### ISSUE TITLE
Translate `library/stdtypes.po`

### ISSUE THREAD

**Issue by sofide** [python/python-docs-es#3119]
This file is 71% translated and needs to reach 100%.

The rendered version of this file will be available at https://docs.python.org/es/3.13/library/stdtypes.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/stdtypes.po`:

- Total entries: 1332

- Entries that need work: 383 - (29%)
  - Fuzzy: 141
  - Untranslated: 242

Please, comment here if you want this file to be assigned to you and a member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by cmaureir** [comment]
Me la pido porque tiene muchas sin traducir.
