### ISSUE TITLE
Translate `library/os.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#314]
This needs to reach 100% translated.

Current stats for `library/os.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 766
- Untranslated: 766

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by lecovi** [comment]
Si les parece bien, tomo este...

**Comment by humitos** [comment]
¡Adelante @lecovi! Muchas gracias :smile: --pregunta si tienes cualquier duda, y recuerda seguir los pasos de la guía de colaboración :tada:

**Comment by lecovi** [comment]
Si, vamos a ver cómo nos va traduciendo! :smile:
