### ISSUE TITLE
Translate `library/socket.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#315]
This needs to reach 100% translated.

Current stats for `library/socket.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 300
- Untranslated: 300

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by ramsal** [comment]
For me!

**Comment by humitos** [comment]
Yay! Thanks for contributing

**Comment by humitos** [comment]
Hola @ramsal ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by cmaureir** [comment]
@ramsal  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by cmaureir** [comment]
Si pudiste traducir algo @ramsal, avisanos para que lo subas y no se pierda lo que lograste avanzar.

**Comment by ramsal** [comment]
Hola, disculpa, voy a subir los avances, no había visto las notificaciones anteriores.

**Comment by cmaureir** [comment]
Muchas gracias! Si no tienes tiempo para dejar eso pasando el CI y aceptando comentarios de futuros revisores, nos dices y continuamos el PR ;)
Pero ojalá que puedieras continuarlo y terminarlo, pero entendemos que a veces el tiempo no acompaña mucho.
