### ISSUE TITLE
Translate `library/sys.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#316]
This needs to reach 100% translated.

Current stats for `library/sys.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 385
- Untranslated: 385

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Tai543** [comment]
Pido esta 😃

**Comment by raulcd** [comment]
Gracias @Tai543

**Comment by humitos** [comment]
Hola @Tai543 ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by Tai543** [comment]
Hola @humitos si he avanzado muy poco creo para el volumen de linea 😞 pero abrire el PR en Draft 👍

**Comment by Tai543** [comment]
@humitos el PR esta abierto
