### ISSUE TITLE
Translate `library/xml.etree.elementtree.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#317]
This needs to reach 100% translated.

Current stats for `library/xml.etree.elementtree.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 224
- Untranslated: 224

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by dav009** [comment]
🙋

**Comment by raulcd** [comment]
Gracias @dav009

**Comment by humitos** [comment]
Hola @dav009 ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by clacri** [comment]
Me encantaría revisar esta issue si @dav009 la traduce, es un módulo que me interesa :)

**Comment by cmaureir** [comment]
@dav009  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by cmaureir** [comment]
Si tienes algo @dav009 avisanos para que no se pierda el trabajo que hiciste.

**Comment by migrmrz** [comment]
Hola, me gustaría colaborar con este issue.

**Comment by cmaureir** [comment]
Hola @migrmrz, ¿es tu primera colaboración? si es así, te recomiendo que puedas mirar un archivo pequeño, para que te familiarices con el flujo de trabajo, ya que este archivo es bastante largo. Te parece si miras uno mucho más corto y cuando lo tengas listo te asignamos este issue?

**Comment by migrmrz** [comment]
Hola. Sí es mi primera. Intenté buscar algo más, pero no encontré. Igual fue una búsqueda rápida. Seguiré buscando más a fondo para solicitar la asignación. Gracias.

**Comment by mmmarcos** [comment]
Hola! Nadie trabajando en esta traducción ? yo puedo dedicarle un poco de tiempo :)

**Comment by cmaureir** [comment]
Todo tuyo @mmmarcos  ;)
Gracias por el interés y nos avisas si tienes alguna pregunta!

**Comment by mmmarcos** [comment]
Traducción terminada! 
/cc @cmaureir
