### ISSUE TITLE
Translate `library/unittest.mock.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#319]
This needs to reach 100% translated.

Current stats for `library/unittest.mock.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 372
- Untranslated: 372

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by gomezgleonardob** [comment]
Please assign me

**Comment by raulcd** [comment]
Assigned @gomezgleonardob

**Comment by humitos** [comment]
Hola @gomezgleonardob ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by clacri** [comment]
Hola @gomezgleonardob estoy retomando la traducción de rapto de unittest.po y he visto que habia esta issue y otra de ficheros muy relacionados. Como hace mucho tiempo que no la has actualizado quería confirmar contigo si sigues queriendo ocuparte de la issue, y en caso contrario que nos lo dijeras para poder reasignarla. Un saludo!

**Comment by clacri** [comment]
This issue is free now for new assignement

**Comment by fjsevilla-dev** [comment]
Me gustaría retomar este.

**Comment by cmaureir** [comment]
grande @fjsevilla-dev la máquina de la traducción :tada:
