### ISSUE TITLE
Translate `howto/argparse.po`

### ISSUE THREAD

**Issue by sofide** [python/python-docs-es#3199]
This file is 70% translated and needs to reach 100%.

The rendered version of this file will be available at https://docs.python.org/es/3.13/howto/argparse.html once translated.
Meanwhile, the English version is shown.

Current stats for `howto/argparse.po`:

- Total entries: 135

- Entries that need work: 40 - (30%)
  - Fuzzy: 0
  - Untranslated: 40

Please, comment here if you want this file to be assigned to you and a member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Carlangueitor** [comment]
I'd like to work on this :pray: .

**Comment by rtobar** [comment]
Gracias @Carlangueitor por la traducción. Igual para la próxima mejor espera a que te asignen el issue, puede llegar a pasar que dos personas terminan duplicando trabajo.
