### ISSUE TITLE
Translate `howto/annotations.po`

### ISSUE THREAD

**Issue by sofide** [python/python-docs-es#3203]
This file is 87% translated and needs to reach 100%.

The rendered version of this file will be available at https://docs.python.org/es/3.13/howto/annotations.html once translated.
Meanwhile, the English version is shown.

Current stats for `howto/annotations.po`:

- Total entries: 48

- Entries that need work: 6 - (13%)
  - Fuzzy: 3
  - Untranslated: 3

Please, comment here if you want this file to be assigned to you and a member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Carlangueitor** [comment]
I'd like to work on this :pray: .

**Comment by rtobar** [comment]
Todo tuyo @Carlangueitor
