### ISSUE TITLE
Translate `library/decimal.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#323]
This needs to reach 100% translated.

Current stats for `library/decimal.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 328
- Untranslated: 328

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Chris99999** [comment]
Quiero traducirlo =D

**Comment by humitos** [comment]
Hola! Que lo disfrutes! Recuerda seguir los pasos de la guía de contribución 😃

**Comment by humitos** [comment]
Hola @Chris99999 ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by cmaureir** [comment]
@morenocl  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by cmaureir** [comment]
@morenocl si tienes algo, seria genial que lo subas como draft para que no se pierda y alguien más pueda continuar.

**Comment by fjsevilla-dev** [comment]
Me gustaría seguir con este, creo que es el último de los módulos matemáticos que queda por traducir por fin 😂

**Comment by cmaureir** [comment]
Muchas gracias @fjsevilla-dev :tada:
