### ISSUE TITLE
Translate `reference/expressions.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#324]
This needs to reach 100% translated.

Current stats for `reference/expressions.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 315
- Untranslated: 315

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by MichellePerezS** [comment]
Hola ,quisiera ayudar a traducir esta parte de documentación.

**Comment by humitos** [comment]
Muchas gracias! Adelante. Recuerda seguir la guía de colaboración y pregunta si tienes cualquier duda!

**Comment by humitos** [comment]
Hola @MichellePerezS ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by cmaureir** [comment]
@MichellePerezS  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by cmaureir** [comment]
Si tienes algo parcial @MichellePerezS sería genial que lo subieras para que alguien más lo pueda continuar.

**Comment by mondeja** [comment]
Buenas, ¿podría traducir este archivo?

**Comment by cmaureir** [comment]
Claro @mondeja, ya eres de la casa!
