### ISSUE TITLE
Translate `howto/regex.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#325]
This needs to reach 100% translated.

Current stats for `howto/regex.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 286
- Untranslated: 286

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by shpotes** [comment]
Me la pido!

**Comment by humitos** [comment]
Hola! Adelante. Que lo disfrutes!

**Comment by humitos** [comment]
Hola @shpotes ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by cmaureir** [comment]
@shpotes  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by cmaureir** [comment]
Si tienes algún avance parcial, seria genial que lo subas para que no se pierda y alguien más lo pueda continuar.

**Comment by mjmolina** [comment]
Hola! Me gustaría traducir este documento :)

**Comment by cmaureir** [comment]
gracias, éxito con la traducción :tada:
