### ISSUE TITLE
Translate `reference/lexical_analysis.po`

### ISSUE THREAD

**Issue by sofide** [python/python-docs-es#3284]
This file is 51% translated and needs to reach 100%.

The rendered version of this file will be available at https://docs.python.org/es/3.13/reference/lexical_analysis.html once translated.
Meanwhile, the English version is shown.

Current stats for `reference/lexical_analysis.po`:

- Total entries: 327

- Entries that need work: 158 - (49%)
  - Fuzzy: 63
  - Untranslated: 95

Please, comment here if you want this file to be assigned to you and a member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by kbiggers** [comment]
Hola! Puedo trabajar en este issue, alguien me lo podría asignar?

**Comment by cacrespo** [comment]
@kbiggers Todo tuyo!
