### ISSUE TITLE
Translate `deprecations/index.po`

### ISSUE THREAD

**Issue by sofide** [python/python-docs-es#3298]
This file is 0% translated and needs to reach 100%.

The rendered version of this file will be available at https://docs.python.org/es/3.13/deprecations/index.html once translated.
Meanwhile, the English version is shown.

Current stats for `deprecations/index.po`:

- Total entries: 208

- Entries that need work: 208 - (100%)
  - Fuzzy: 0
  - Untranslated: 208

Please, comment here if you want this file to be assigned to you and a member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by cmaureir** [comment]
Me la pido para hacer un archivo nuevito
