### ISSUE TITLE
Actualizar rama 3.7 con últimos cambios de 3.7.7

### ISSUE THREAD

**Issue by raulcd** [python/python-docs-es#334]
There are some [paragraphs](https://github.com/python/python-docs-es/blob/3.7/tutorial/controlflow.po#L29):
```
Besides the while statement just introduced, Python uses the usual flow control statements known from other languages, with some twists.
```
That appear incorrectly because we haven't updated the last 3.7 version and applied the backports that were done:
https://github.com/python/cpython/commit/8b907a8875d1b22d8f060dee9430cc82d471e86b
This was backported from 3.8 and is translated there.
It can be seen on the published documentation here:
https://docs.python.org/es/3.7/tutorial/controlflow.html#more-control-flow-tools)

**Comment by humitos** [comment]
Shouldn't we tell them to disable `3.7` online version and just stick with 3.8?

**Comment by raulcd** [comment]
I don't think so, lots of changes appear directly if we just merge. For example the tutorial is almost all translated on python3.6 just because the different paragraphs haven't changed and it just picks them up:
https://docs.python.org/es/3.6/tutorial/
I think we can just use that there's not that many releases and these process should be done only once a new release is created.

**Comment by clacri** [comment]
@raulcd esta issue tiene que seguir abierta o está ya outdated?

**Comment by humitos** [comment]
@clacri entiendo que no, lo que reporta @raulcd sigue pasando. Hay que actualizar las ramas anteriores con lo nuevo que tenemos. Ellos construyen todas las versiones aunque no las tengamos 100% traducidas. Sin embargo, hay mucho texto que se comparte entre todas las versiones y haciendo un "merge loco" de las versiones nuevas hacia atrás podemos tener las más viejas con más párrafos traducidos.
