### ISSUE TITLE
Translate `library/difflib.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#337]
This needs to reach 100% translated.

Current stats for `library/difflib.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 132
- Untranslated: 132

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Bgeninatti** [comment]
Hola @humitos . Me gustaría contribuir con esta traducción.

**Comment by humitos** [comment]
@Bgeninatti adelante! Cuando vayas avanzando, acordate de abrir el PR en draft con lo primero que vayas teniendo, así te podemos dar un feedback mínimo temprano. Gracias!
