### ISSUE TITLE
Translate `library/urllib.request.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#338]
This needs to reach 100% translated.

Current stats for `library/urllib.request.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 271
- Untranslated: 271

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by gomezgleonardob** [comment]
Please assign me

**Comment by raulcd** [comment]
Thanks @gomezgleonardob , assigned

**Comment by cmaureir** [comment]
@gomezgleonardob  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by clacri** [comment]
hola @gomezgleonardob nos puedes confirmar si quieres continuar con esta issue?

**Comment by cmaureir** [comment]
queda libre esta issue

**Comment by mondeja** [comment]
Uh que buen módulo, me lo pido :tada:
¿Me lo podéis asignar?

**Comment by cmaureir** [comment]
gracias @mondeja :+1:
