### ISSUE TITLE
Translate `library/ssl.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#339]
This needs to reach 100% translated.

Current stats for `library/ssl.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 490
- Untranslated: 490

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by neosergio** [comment]
I can take this translation pending too :)

**Comment by claudio-m** [comment]
can I translate this file?

**Comment by humitos** [comment]
Hi Claudio! Sure! Go ahead and happy translating 🎉

**Comment by cmaureir** [comment]
@claudio-m  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by cmaureir** [comment]
Si lograste hacer algo seria genial que lo subas para que no se pierda tu esfuerzo ;)

**Comment by jaumemy** [comment]
Hola! Curioseando qué podía traducir, encontré esto que está pendiente parece.
Me ofrezco!

**Comment by cmaureir** [comment]
éxito @jaumemy, es un archivo bastante largo, asi que si en algún momento crees que no puedes continuar, te recomiendo que subas lo que tengas. Alternativamente, puedes abrir el PR como draft cuando te sientes a hacer las primeras traducciones y así solo lo vas actualizando cada vez que avances ;)

**Comment by jaumemy** [comment]
Gracias @cmaureir ! Ya había traducido un par más cortos y me apetecía hacer alguno más complicado.
Puedo hacer como tu dices. Lo iré subiendo en unas pocas partes para que vaya progresando mientras doy tiempo a que le hagan review .

**Comment by cmaureir** [comment]
@jaumemy al final pudiste traducir algo de acá? Si no, no pasa nada es solo para saber si te animas a seguir a cargo o si lo dejamos libre.

**Comment by jaumemy** [comment]
Hola @cmaureir !

Sí, mil disculpas pero he estado en muchas otras cosas. 
Déjalo libre y cuando esté un poco más liberado ya buscaré otra issue en qué aportar.

Un saludo!

**Comment by mmmarcos** [comment]
Hola! Nuevo por aquí, me gustaría comenzar a traducir este archivo si sigue sin estar asignado :)

**Comment by cacrespo** [comment]
Hola @mmmarcos!! Asignado. 🚀🚀🚀 
Feliz traducción! 😄

**Comment by mmmarcos** [comment]
OK, gracias! Es sobre la branch 3.9?

**Comment by cacrespo** [comment]
> OK, gracias! Es sobre la branch 3.9?

Así es. Cualquier duda que tengas puedes escribir en el grupo de Telegram también.

**Comment by mmmarcos** [comment]
La traducción avanza a paso lento pero seguro 😄

Este es el PR (en draft por el momento) : #1223

**Comment by mmmarcos** [comment]
Traducción finalizada! 🙌

El PR ya no está mas en draft --> https://github.com/python/python-docs-es/pull/1223

**Comment by mmmarcos** [comment]
Hola, ya subí todas las correcciones/sugerencias de @eamanu (gracias por el review!)

El PR debería poder mergearse 👍 

cc @cacrespo
