### ISSUE TITLE
Translate `howto/logging-cookbook.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#340]
This needs to reach 100% translated.

Current stats for `howto/logging-cookbook.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 216
- Untranslated: 216

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by cacrespo** [comment]
Lo tomo!

**Comment by humitos** [comment]
Disfrute!

**Comment by cmaureir** [comment]
@cacrespo  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by cacrespo** [comment]
Hola @cmaureir! Prefiero seguirlo (ya es algo personal). Voy lento pero estoy avanzando. Si te parece hago el PR con lo que tengo.

**Comment by cmaureir** [comment]
Sería genial si lo puedes subir como draft y así lo vas actualizando a tu tiempo, pues como no había nada, parecía que no había avance. Muchas gracias Carlos
