### ISSUE TITLE
Translate `using/cmdline.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#342]
This needs to reach 100% translated.

Current stats for `using/cmdline.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 198
- Untranslated: 198

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by gomezgleonardob** [comment]
Please assign me

**Comment by humitos** [comment]
Enjoy!

**Comment by cmaureir** [comment]
@gomezgleonardob  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by Jighdan** [comment]
Podria tomar este?

**Comment by clacri** [comment]
Esta issue fue ya completada, se debió haber cerrado en https://github.com/python/python-docs-es/pull/730
