### ISSUE TITLE
Translate `library/struct.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#343]
This needs to reach 100% translated.

Current stats for `library/struct.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 150
- Untranslated: 150

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by mgaitan** [comment]
tomo este

**Comment by humitos** [comment]
Genial! Gracias :1st_place_medal:

**Comment by cmaureir** [comment]
Ya que tomamos tus ultimos PR @mgaitan tienes algún avance en este archivo para subir y que otra persona lo continue?

**Comment by mgaitan** [comment]
No muchachos. Colgué. Más adelante si queda algo retomo, pero estoy medio quemado ahora. Avanti nomás, continuenlo

**Comment by carlos-bernad** [comment]
Hola! ¿Puedo traducir este archivo?

**Comment by cmaureir** [comment]
Listo @carlos-bernad ! Mucho éxito con la traducción :)

**Comment by cmaureir** [comment]
Como vas @carlos-bernad ? te podemos ayudar en algo? Si lograste traducir algo, seria genial que lo subas asi alguien lo pueda continuar si no tuviste tiempo

**Comment by carlos-bernad** [comment]
@cmaureir Gracias por el mensaje, esta semana lo completo.
