### ISSUE TITLE
Translate `library/codecs.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#344]
This needs to reach 100% translated.

Current stats for `library/codecs.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 502
- Untranslated: 502

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by cmaureir** [comment]
Me voy a ir apuntando los archivos mas aburridos para sacarlos luego y que nos olvidemos :P
