### ISSUE TITLE
Translate `library/doctest.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#348]
This needs to reach 100% translated.

Current stats for `library/doctest.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 306
- Untranslated: 306

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by trallard** [comment]
Yo pido esta

**Comment by raulcd** [comment]
Asignado @trallard ! Muchas gracias

**Comment by cmaureir** [comment]
@trallard avisanos si te podemos ayudar en algo para hacer el PR :)

**Comment by trallard** [comment]
Hey he andado suuuuper ocupada con trabajo y organizando eventos virtuales. Esta semana tengo tiempo para mover esto y mandar el PR

**Comment by cmaureir** [comment]
@trallard me imagino lo ocupada que debes andar, si llevas algo en este archivo, te parece subir lo que llevas y así alguien más lo puede continuar? aún quedan muchos archivos más, solo que no se abrieron los issues de todos de una vez :)

**Comment by clacri** [comment]
hola Tania @trallard nos podrías confirmar si quieres continuar con esta issue? o si tienes algo parcial que quieras subir?

**Comment by cmaureir** [comment]
Si lograste traducir algo, avisanos. Lo dejamos libre para otra persona

**Comment by aroquega** [comment]
¿Este es el famoso doctest que sólo los expertos en git saben usar @cmaureir? me encantaría traducir este archivo, en cuanto revisen el #939. 

Por mientras mantendré los ojos en esta issue 👀.

**Comment by clacri** [comment]
toda tuya, mientras te están revisando la otra puedes comenzar esta!

**Comment by cmaureir** [comment]
@aroquega ojalá tengas tiempo de acabar lo que queda, que no es mucho y ya has hecho gran cantidad del trabajo! Si en algún momento te quedas sin tiempo, avisanos así lo tomamos y acabamos :tada:
