### ISSUE TITLE
Translate `library/asyncio-task.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#350]
This needs to reach 100% translated.

Current stats for `library/asyncio-task.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 172
- Untranslated: 172

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by darwing1210** [comment]
Me apunto a este :)

**Comment by humitos** [comment]
Excelente! Gracias. Que lo disfrutes 😉

**Comment by humitos** [comment]
Hola @darwing1210! ¿Cómo vienes con la traducción de este archivo? ¿Has podido avanzar? ¿Tienes alguna duda en la que te podamos ayudar?

Si tienes un pequeño porcentaje traducido, sería bueno que abras una PR en Draft así te podemos dar un poco de feedback y ayudarte a continuar.

**Comment by darwing1210** [comment]
Gracias @humitos siento mucho la demora, lo tendré listo lo más pronto posible

**Comment by cmaureir** [comment]
@darwing1210  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by cmaureir** [comment]
Lo dejamos libre para otra persona. Si pudiste traducir algo, seria genial que lo subieras para que no se pierda el trabajo

**Comment by alcides29** [comment]
Puedo trabajar en esta traducción

**Comment by cmaureir** [comment]
Gracias @alcides29 :tada:
