### ISSUE TITLE
Translate `reference/import.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#351]
This needs to reach 100% translated.

Current stats for `reference/import.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 187
- Untranslated: 187

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Jighdan** [comment]
I'll take it

**Comment by humitos** [comment]
Yay! Enjoy it and thanks! Remember to read the contributing guide 😉
