### ISSUE TITLE
Translate `library/idle.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#352]
This needs to reach 100% translated.

Current stats for `library/idle.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 271
- Untranslated: 271

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by narvmtz** [comment]
Hi @humitos, I would like to work on this one! :smile:

**Comment by raulcd** [comment]
Thanks @narvmtz !
