### ISSUE TITLE
Translate `reference/lexical_analysis.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#353]
This needs to reach 100% translated.

Current stats for `reference/lexical_analysis.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 182
- Untranslated: 182

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by MiguelHeCa** [comment]
Hola, yo quisiera también traducir este!

**Comment by humitos** [comment]
Adelante!

**Comment by humitos** [comment]
Hola @MiguelHeCa ! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by MiguelHeCa** [comment]
Sí he avanzado, pero muy poco. Perdona por no hacer antes el PR! Ahora lo hago para que puedan ir viendo el progreso. Prometo ponerme al día!

**Comment by cmaureir** [comment]
@MiguelHeCa  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by MiguelHeCa** [comment]
@cmaureir  En verdad disculpas por la demora!! Ya lo tengo hecho al 100%, pero como lo tengo en pr-draft no sé cómo hacerlo de forma que ya no sea draft. Lo reviso esta noche

**Comment by cmaureir** [comment]
Ahí lo asocié a este issue, y lo cambié a open, para que no sea Draft :+1:
