### ISSUE TITLE
Guía para colaborar como revisor

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#399]
Hemos estado haciendo reuniones puntuales con algunas personas para hacer el "onboarding" sobre "¿cómo hacer un review?". Si bien creo que es super interesante y todos lo disfrutamos, no escala.

Estaría bueno tener una guía similar a CONTRIBUTING (enlazada desde ésta) que mencione que se puede colaborar haciendo revisiones.

Por ejemplo, la [gente de Spacemacs lo hace](https://develop.spacemacs.org/CONTRIBUTING.html) con un apartado específico para colaborar haciendo reviews.

Podemos poner los ejemplos comunes de fallo en travis:

* una palabra tiene un typo y falla `pospell`
* se debe incluir una palabra válida al `dict`
* ¿cuándo se debe usar una palabra con asteriscos?
* error de `powrap`
* ¿cómo descargar una rama de otra persona, editarla y hacer push?
* ¿cómo se muestran los errores de Sphinx cuando faltan enlaces en la traducción?
* ¿cómo debemos dar feedback a las personas?
* uso de las sugerencias de GitHub
* etc...

**Comment by humitos** [comment]
@silvinabt87 sé que estuviste tomando algunas notas de lo que hablamos en la reunión, ¿podrías agregar a este issue las cosas que me estoy oldivando? O, incluso, mejor aún --¿te gustaría escribir esta guía? :wink:

**Comment by clacri** [comment]
súper buena idea!!!

**Comment by humitos** [comment]
@clacri @silvinabt87 siéntanse libres de modificar la descripción de este issue agregando más puntos que debamos tener en cuenta en la guía

**Comment by silvinabt87** [comment]
@humitos @clacri me pongo a organizar mis notas en un texto y ponemos manos a la obra! Conforme se me vayan ocurriendo tips los agrego al issue

**Comment by silvinabt87** [comment]
@humitos @clacri estoy armando el texto para la guía, empezando a incluir mis notas e incorporando los tips de este issue. Comencé con un Google Docs para mi misma, pero me gustaría compartirlo con uds y otrxs voluntarixs para que aportemos todxs. En que file del proyecto lo puedo hacer? (disculpen si es una pregunta muy básica)

**Comment by clacri** [comment]
ninguna pregunta sobra :) mira, para poder incluirlo tienes que crearlo el fichero en el directorio oculto que se llama .overrides/ (en el repo). Esto sirve porque esas paginas no van a la documentacion de python, es un directorio solo con nuestras cosas del proyecto de traduccion. Dentro hay otras páginas como la memoria de traducción y demás. Puedes crear una PR con una primera versión, que cree la página. Tendrás que tener en cuenta la sintaxis de markdown para que se vea bien, pero no te preocupes ahora por eso que si cuando lo subas da error el build lo revisamos.

**Comment by silvinabt87** [comment]
genial!! gracias!! eso quería: hacerlo con markdown y que ya quede listo, porque con el Google Docs estoy haciendo un paso de más :P

**Comment by humitos** [comment]
> Tendrás que tener en cuenta la sintaxis de markdown para que se vea bien

Ojo que no es Markdown, sino que es reStructuredText. Esta guía te puede ayudar a entender cómo definir cada tipo de sección, negrita, título, etc https://www.sphinx-doc.org/es/master/usage/restructuredtext/index.html

**Comment by clacri** [comment]
oooops perdón me confundí !!!!

**Comment by silvinabt87** [comment]
Sí, yo no me di cuenta tampoco pero entré en Sphinx para escribir con RST, porque sabía que ese era el formato de los archivos, y encontré esa guía. Gracias!
