### ISSUE TITLE
Translate `library/statistics.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#417]
This needs to reach 100% translated.

Current stats for `library/statistics.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 152
- Untranslated: 152

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by RubenGavidia** [comment]
me gustaria traducir este archivo.

**Comment by humitos** [comment]
Hola @RubenGavidia! Bienvenido y gracias por colaborar! Espero que lo disfrutes :wink:

**Comment by cmaureir** [comment]
@RubenGavidia  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by RubenGavidia** [comment]
Hola. La traduccion esta a 84%, se me presento un incoveniente y no puedo continuar con la traduccion.

**Comment by cmaureir** [comment]
@RubenGavidia te gustarí subir lo que llevas y que alguien más lo continúe?

**Comment by fjsevilla-dev** [comment]
Me gustaría continuar con este, para seguir con el mundo matemático mas que nada... :)
_"A Bayesian is one who, vaguely expecting a horse, and catching a glimpse of a donkey, strongly believes he has seen a mule."_

**Comment by cmaureir** [comment]
Gracias @fjsevilla-dev :rocket:
