### ISSUE TITLE
Translate `library/optparse.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#419]
This needs to reach 100% translated.

Current stats for `library/optparse.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 406
- Untranslated: 406

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by claudio-m** [comment]
can I work on this translation?

**Comment by humitos** [comment]
Hi Claudio! I just assigned another issue, #339. Please work on that first. Once finished, we can assign this one to you if nobody else has taken it. Thanks!

**Comment by genvalen** [comment]
Can I work on this?

**Comment by humitos** [comment]
hey @genvalen! Sure! Go ahead! Remember to follow the steps from the Contributing Guide. I'm sorry for the late reply here :disappointed:

**Comment by cmaureir** [comment]
@genvalen  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by genvalen** [comment]
@cmaureir, @humitos , disculpenme. :( Creo que por ahora no voy a tener opportunidad de ayudar con esta traduccion.

**Comment by humitos** [comment]
OK. No te preocupes. Liberamos el issue así lo puede tomar otra persona. Si vuelves a tener tiempo, no dudes en agarrar otro de los issues que estén libres. Gracias por avisar!

**Comment by fjsevilla-dev** [comment]
¡Buenas! Me gustaría tomar este, habrá que darle algo de cariño aunque sea un módulo obsoleto... :)

**Comment by cmaureir** [comment]
Gracias @fjsevilla-dev, éxito con la traducción :)
