### ISSUE TITLE
Translate `library/hashlib.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#423]
This needs to reach 100% translated.

Current stats for `library/hashlib.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 137
- Untranslated: 137

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by adriEzeMartinez** [comment]
Lo podrè tomar?

**Comment by cmaureir** [comment]
Claro! Muchas gracias @adriEzeMartinez  :)

**Comment by adriEzeMartinez** [comment]
genial! muchas gracias!

**Comment by cmaureir** [comment]
@adriEzeMartinez  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by cmaureir** [comment]
Queda libre para otra persona.

**Comment by mondeja** [comment]
Hola, ¿puedo tomar este?

**Comment by cmaureir** [comment]
Gracias @mondeja mucho éxito :tada:
