### ISSUE TITLE
Translate `library/operator.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#424]
This needs to reach 100% translated.

Current stats for `library/operator.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 177
- Untranslated: 177

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by brianbok** [comment]
Hola, me gustaría ayudar con la traducción de library/operator :smile:

**Comment by humitos** [comment]
Hola @brianbok! Bienvenido! Que disfrutes mucho la traducción de este módulo! Recuerda seguir los pasos de la guia de colaborador :wink:
