### ISSUE TITLE
Translate `library/logging.handlers.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#425]
This needs to reach 100% translated.

Current stats for `library/logging.handlers.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 255
- Untranslated: 255

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by jcantilo** [comment]
can I work on this? is my first time but I want to colaborate

**Comment by humitos** [comment]
Sure! Great! Please, follow the steps and considerations from the contributing guide. Thanks!
