### ISSUE TITLE
Translate `library/curses.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#426]
This needs to reach 100% translated.

Current stats for `library/curses.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 630
- Untranslated: 630

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by ALandazabal** [comment]
Hello!! Can I work in this doc?

**Comment by humitos** [comment]
@ALandazabal Hola! Adelante! Espero que lo disfrutes! :tada: . Recuerda seguir los pasos que indica la guía de "Contributing"

**Comment by cmaureir** [comment]
@ALandazabal  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by ALandazabal** [comment]
Hola!! Muchas gracias por querer ayudarme :) Yo aún estoy trabajando en él, creo que esta semana ya lo termino 👍

**Comment by cmaureir** [comment]
Gracias @ALandazabal recuerda que si quieres subir un draft y te vamos haciendo correcciones de lo que llevas, también es buena idea. éxito con la traducción!
