### ISSUE TITLE
Translate `library/concurrent.futures.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#427]
This needs to reach 100% translated.

Current stats for `library/concurrent.futures.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 84
- Untranslated: 84

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Ambro17** [comment]
Buenas, me gustaría traducir está sección
Hello, I'd like to translate this section

**Comment by raulcd** [comment]
assigned, thanks @Ambro17
