### ISSUE TITLE
Translate `library/cgi.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#429]
This needs to reach 100% translated.

Current stats for `library/cgi.po`:

- Fuzzy: 0
- Percent translated: 44%
- Entries: 39 / 88
- Untranslated: 49

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by aigissch** [comment]
¡Hola! Me gustaría que me asignen este archivo. Gracias.

**Comment by humitos** [comment]
Hola @aigissch! Adelante! Que lo disfrutes!

**Comment by cmaureir** [comment]
@aigissch  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by aigissch** [comment]
> 
> 
> @aigissch te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

@cmaureir Hola, voy bien, quizás más lento de lo que se espera supongo, si es necesario hago un sprint con lo poco que me queda y lo termino ya, o subo lo que tenga y que otro continúe. No sé si es conveniente que hubiera subido mi progreso poco a poco, no tengo mucha experiencia con github y quizás ese ha sido mi principal problema. ¡Perdón por las molestias!

**Comment by cmaureir** [comment]
No te preocupes @aigissch, Lo que sea mejor para ti, si quieres subes lo que llevas y luego localmente solo tendrías que continuar haciendo traducciones y cada cierto tiempo hacer `git add library/cgi.po` luego el `git commit -m "Nuevas entradas traducidas .... "` y por ultimo un `git push origin nombre-de-tu-rama-local`. Y así vas llenando de commits el Pull request que abres con el primero. Recuerda que siempre estamos en Telegram por si tienes dudas o problemas con Git, nos puedes compartir imagenes de los errores y te podemos dar una mano.

**Comment by cmaureir** [comment]
Se subirá un avance parcial de esta issue, y luego dejaremos abierto a cualquier persona que quiera continuar. Muchas gracias por la ayuda @aigissch :+1:

**Comment by Diavolo** [comment]
Hola, me gustaría ayudar con esta tarera.

**Comment by cmaureir** [comment]
Gracias @Diavolo actualicé los números que aigissch dejó, queda como la mitad del archivo. así que espero no sea tanto trabajo.!

**Comment by cmaureir** [comment]
@Diavolo creo que tuvimos un problema de sincronización y @narvmtz también estaba trabajando en este issue, podrías ponerte en contacto con ella para ver como acabamos el archivo?
