### ISSUE TITLE
Translate `reference/compound_stmts.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#460]
This needs to reach 100% translated.

Current stats for `reference/compound_stmts.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 115
- Untranslated: 115

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by mayuti** [comment]
Hi!, Can I help translate this file?.

**Comment by cmaureir** [comment]
buenisima! Gracias @mayuti, asignado. Suerte con la traducción!

**Comment by mayuti** [comment]
Buenas!, Espero haber realizado todos los pasos correctamente en mi primera traducción. Saludos.
