### ISSUE TITLE
Translate `library/asyncio-eventloop.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#461]
This needs to reach 100% translated.

Current stats for `library/asyncio-eventloop.po`:

- Fuzzy: 0
- Percent translated: 10.45%
- Entries: 33 / 345
- Untranslated: 312

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by qagustina** [comment]
I would like to work on this :)

**Comment by raulcd** [comment]
assigned, thanks @qagustina

**Comment by cmaureir** [comment]
Queda abierta esta issue para continuar las traducción.

**Comment by Bgeninatti** [comment]
Me gustaría trabajar en este.

**Comment by cmaureir** [comment]
Asignado @Bgeninatti :tada: Mucho éxito con la traducción, son bastantes entradas así que te recomiendo que vayas haciendo 'push' a tu PR de vez en cuando, asi la gente va revisando de a poco :)
