### ISSUE TITLE
Translate `library/dataclasses.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#462]
This needs to reach 100% translated.

Current stats for `library/dataclasses.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 93
- Untranslated: 93

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by ignaciodopazo** [comment]
Hola! Soy nuevo por acá, me gustaría ayudar empezando con éste.

**Comment by humitos** [comment]
Hola! Adelante! Puedes empezar con este archivo. Recuerda seguir los pasos de la guía!

**Comment by cmaureir** [comment]
@ignaciodopazo  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by ignaciodopazo** [comment]
En este momento estoy complicado con mis tiempos, quizas sea mejor que alguien mas lo siga para no congelarlo. Eventualmente retomaré alguna otra traduccion!

**Comment by fjsevilla-dev** [comment]
Hola, me gustaría retomar esta.

**Comment by humitos** [comment]
@fjsevilla-dev adelante y, bienvenide!
