### ISSUE TITLE
Translate `faq/design.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#463]
This needs to reach 100% translated.

Current stats for `faq/design.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 138
- Untranslated: 138

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by cmaureir** [comment]
Me anoto con esta, para acabar los FAQ pronto.
