### ISSUE TITLE
Translate `reference/simple_stmts.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#465]
This needs to reach 100% translated.

Current stats for `reference/simple_stmts.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 153
- Untranslated: 153

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by mikanchu** [comment]
Hello!

I would like to have this file assigned to me.

Thank you!

**Comment by cmaureir** [comment]
Gracias @mikanchu ! Mucha suerte con la traducción :)

**Comment by cmaureir** [comment]
@mikanchu  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by mikanchu** [comment]
@cmaureir Siento el retraso, estoy teniendo unos meses algo intensos. Intentaré tenerlo terminado lo antes posible si no es molestia

**Comment by cmaureir** [comment]
> @cmaureir Siento el retraso, estoy teniendo unos meses algo intensos. Intentaré tenerlo terminado lo antes posible si no es molestia

Ningún problema @mikanchu !
Mucho éxito con tus actividades.
Recuerda que puedes siempre subir un draft de lo que llevas y así otra persona lo puede acabar. Aún quedan muchos archivos que traducir, así que no te preocupes que se podrá seguir colaborando :)

**Comment by clacri** [comment]
hola @mikanchu :) solo chequeando si sigues queriendo ocuparte de esta issue. Un saludo

**Comment by mikanchu** [comment]
Hey @clacri, si, estoy trabajando en ello. He tenido un periodo de mucho trabajo y no he podido enviarlo aun pero falta poco! Gracias por la paciencia

**Comment by clacri** [comment]
Ningún problema solo por chequear :) aprovecha el hacktoberfest ;)
