### ISSUE TITLE
Translate `library/smtplib.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#467]
This needs to reach 100% translated.

Current stats for `library/smtplib.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 107
- Untranslated: 107

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by RDCH106** [comment]
Permission to start this translation

**Comment by cmaureir** [comment]
wohoooo! Genial @RDCH106 ! ya está asignado. Suerte con la traducción! :dancers:

**Comment by cmaureir** [comment]
@RDCH106  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by RDCH106** [comment]
@cmaureir disculpa, por haber estado ausente.

Mi intención es ponerme con él este fin  de semana. Se me juntó gran carga de trabajo y abracé con muchas ganas las vacaciones desconectando del todo.

Si para este domingo no lo tengo listo, lo libero para que otro lo traduzca. En tal caso escribiré para pedirlo en este mismo hilo de conversación.
