### ISSUE TITLE
Translate `howto/functional.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#468]
This needs to reach 100% translated.

Current stats for `howto/functional.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 206
- Untranslated: 206

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Unaipg** [comment]
Hi! I'd like to translate this.

**Comment by cmaureir** [comment]
Wohooo! Genial @Unaipg , gracias y mucho éxito con la traducción!

**Comment by cmaureir** [comment]
@Unaipg  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by Unaipg** [comment]
Buenas @cmaureir disculpa por el retraso, he tenido algunos problemas de salud y he estado desconectado pero ya he vuelto a la normalidad, espero tener la traducción lista para la semana que viene.

Un saludo!

**Comment by cmaureir** [comment]
Como vas @Unaipg ? Te podemos ayudar con algo? recuerda que siempre puedes subir lo que llevas y otra persona lo puede continuar.

**Comment by cmaureir** [comment]
dejando esta issue libre

**Comment by Kajachuan** [comment]
Hola @cmaureir. Quería saber si puedo trabajar en esta issue.

**Comment by cmaureir** [comment]
@Kajachuan todo tuyo! Muchas gracias!
