### ISSUE TITLE
Translate `library/ftplib.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#470]
This needs to reach 100% translated.

Current stats for `library/ftplib.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 63
- Untranslated: 63

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by silvinabt87** [comment]
@humitos I can take this one, since it's a short one! So I can go on trying to fix my branch issues for my PR  :( I haven't found the way to solve it yet (I'll go back to beg for help on Telegram :P

**Comment by humitos** [comment]
He! Welcome to the crazy days when nothing works 😅

**Comment by cmaureir** [comment]
@silvinabt87  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by silvinabt87** [comment]
Perdón! No me di cuenta y cuando mergearon mi PR #536, no cerré este issue. Estuve revisando los archivos y entiendo que ya estaría para cerrar, pero no quiero hacer lío y cerrar algo que no va. Si lo pueden mirar y confirmarme, mejor :) gracias
