### ISSUE TITLE
Translate `library/tarfile.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#471]
This needs to reach 100% translated.

Current stats for `library/tarfile.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 201
- Untranslated: 201

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by mxarc** [comment]
¡Hola! 
Me gustaría trabajar en este issue :)

**Comment by cmaureir** [comment]
Genial! Muchas gracias @mxarc !!! Suerte con la traducción!

**Comment by cmaureir** [comment]
@mxarc  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.
