### ISSUE TITLE
Translate `library/test.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#474]
This needs to reach 100% translated.

Current stats for `library/test.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 250
- Untranslated: 250

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by mjmolina** [comment]
Hola. Me gustaría traducir este :) !

**Comment by cmaureir** [comment]
Gracias! Mucho éxito con la traducción!
