### ISSUE TITLE
Translate `distutils/apiref.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#478]
This needs to reach 100% translated.

Current stats for `distutils/apiref.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 411
- Untranslated: 411

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by samvaldez** [comment]
I want to do this.

**Comment by cmaureir** [comment]
Geniaaaaaal @samvaldez Muchas gracias!
Éxito con la traducción! :dancers:

**Comment by cmaureir** [comment]
@samvaldez  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by samvaldez** [comment]
@cmaureir Ya casi termino

**Comment by cmaureir** [comment]
@samvaldez gracias por la respuesta! Recuerda que siempre puedes subir una traducción parcial como 'draft' y así vamos corrigiendo a medida que vas actualizando. éxito!

**Comment by samvaldez** [comment]
Hola @cmaureir hice un pull request hace varios dias, al parecer no lo han revisado?; solicite nueva traduccion pero, lei que me escribiste que terminara la asignada, entonces tengo duda de si no les llego el pull request.

**Comment by cmaureir** [comment]
Creo que ese fue el problema, no hay PRs abiertos con tu usario: https://github.com/python/python-docs-es/pulls/samvaldez
Podrías revisar si efectivamente hiciste un `git push origin tu_rama_local` ?

Acabo de mirar tu fork del repositorio, pero te hiciste el pull request a ti misma: https://github.com/samvaldez/python-docs-es/pulls

Si hiciste todo lo señalado acá: https://python-docs-es.readthedocs.io/es/3.8/CONTRIBUTING.html#comienza-a-traducir
no sé como podría haber pasado...
lo que puedes mirar es repetir el paso *4* en tu repositorio local y decirme si imprime algo en la terminal.
Luego de eso, te vas a tu rama local:
hacer un `git push origin nombre_de_tu_rama_local`.

Si estás confundida con algún paso, me dices, y en el peor de los casos podemos tomar tu archivo traducido y hacer los pasos para enviar un PR desde 0.

**Comment by clacri** [comment]
Vale @eamanu entonces veo que hasta el párrafo del rst 304 lo has revisado tú. ¿vas a continuar con la revisión?
