### ISSUE TITLE
README.rst en Español?

### ISSUE THREAD

**Issue by eamanu** [python/python-docs-es#483]
Dejo esto para discusión (perdón si ya se lo ha discutido antes)

No debería estar el README en español? Si es la traducción al español de la documentación
creo que estaría bueno que lo primero que vea al entrar al proyecto 
sea un resumen en español (o en ambas lenguas?)

Saludos!

**Comment by cmaureir** [comment]
Por lo general la gente no llega por el repositorio, si no por la página https://python-docs-es.readthedocs.io/es/3.8/CONTRIBUTING.html
Pero me parece buena idea dejarlo en Castellano y abajo en inglés,
ya que si miramos las otras iniciativas de traducción, lo tienen en sus respectivos idiomas.
Así que +1

**Comment by humitos** [comment]
Creo que tenemos dos tipos de público: lectores y colaboradores. Los lectores, no deberían llegar a este repositorio en ningún caso, sino directamente a https://docs.python.org/es/3.8/. Los colaboradores, deberían llegar a https://python-docs-es.readthedocs.io/es/3.8/CONTRIBUTING.html

Supongo que podríamos agregar una pequeña sección en castellano en el README para los lectores linkeando a la documentación oficial. Yo no agregaría muchísimo más que eso, así no tenemos que mantener tantos lugares actualizados.
