### ISSUE TITLE
Translate `library/unittest.mock-examples.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#506]
This needs to reach 100% translated.

Current stats for `library/unittest.mock-examples.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 160
- Untranslated: 160

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by EduFriesen00** [comment]
queria trabaja en este issue soy del grupo de telegram estoy como edu friesen

**Comment by cmaureir** [comment]
Buena suerte con la traducción! :tada:

**Comment by clacri** [comment]
Hola @EduFriesen00 estoy retomando la traducción de rapto del fichero unnitest.po y como está muy relacionado con tu issue y la de unnitest.mock queria confirmar que sigues interesado en continuar con esta issue, y recordarte que si necesitas cualquier ayuda aquí estamos, también puedes ir poniendo una PR aunque tuvieras una traducción parcial. Un saludo!!

**Comment by cmaureir** [comment]
@EduFriesen00  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by clacri** [comment]
Hola @EduFriesen00 me lo he asignado porque estoy traduciendo otros ficheros de unittest, si ves que quieres retomarlo avísame.

**Comment by EduFriesen00** [comment]
Hola buenas tardes, yo dejé el issue porque estaba de vacaciones ahora lo
iba a retomar

**Comment by clacri** [comment]
Genial :) pues todo tuyo!

**Comment by cmaureir** [comment]
dejando esta issue libre

**Comment by framorac** [comment]
@cmaureir favor asignarme este issue. Y una consulta, como marco un PR como DRAFT? agrego un label?. Esto para ir generando commits de avance.

**Comment by cmaureir** [comment]
Cuando lo vas a abrir deberías tener la opción, de lo contrario, cuando abras el PR existe una opción en la interfaz. Si me etiquetas cuando subas el PR te lo puedo transformar a draft y te digo donde era ;)

**Comment by framorac** [comment]
Entiendo, lo hare cuando mande el primer PR. Gracias.

**Comment by cmaureir** [comment]
Hola @framorac, si le das el último empujón al archivo, yo te lo podría corregir asi lo mergeamos pronto :muscle:

**Comment by framorac** [comment]
> Hola @framorac, si le das el último empujón al archivo, yo te lo podría corregir asi lo mergeamos pronto :muscle: 

por supuesto, estoy con carga laboral pero apenas pueda termino. 🤘
