### ISSUE TITLE
Translate `library/email.examples.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#509]
This needs to reach 100% translated.

Current stats for `library/email.examples.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 12
- Untranslated: 12

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by mayuti** [comment]
Buenas!, Me podrías pasar el archivo?. Gracias.

**Comment by cmaureir** [comment]
Bien @mayuti  :D Acuerdate de crear la rama desde 3.8 para no incluir cambios anteriores. Mucha suerte!
