### ISSUE TITLE
Crear una página de recursos

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#51]
Tenemos algunos recursos y herramientas (powrap, pospell, pomerge, etc) que estaría bueno poner en una página "resources.rst" y linkearla desde contributing así la gente la descubre.

* https://www.linguee.com
* https://wordreference.com

**Comment by humitos** [comment]
> herramientas (powrap, pospell

Quizás es mejor explicar `pre-commit` para esto, que hace todo solo.

**Comment by eamanu** [comment]
Hola!, 

me gustaría trabajar en este issue.

**Comment by humitos** [comment]
@eamanu adelante!

**Comment by humitos** [comment]
Creo que hay que dividir este trabajo en docs cosas:

1. recursos relacionados con la traducción. Ejemplo: diccionarios --que quizás van en al memoria de traducción.
2. recursos relacionados con las herramientas de codigo/flujo git. Ejemplo: pre-commit --que deberían ir en su propia página para no distraer a los traductores.

**Comment by eamanu** [comment]
@humitos viendo los últimos comentarios de #371, creo que este issue se puede cerrar?

**Comment by cmaureir** [comment]
Pues yo creo que si, la página de FAQ ya tiene bastante material
