### ISSUE TITLE
Translate `library/signal.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#513]
This needs to reach 100% translated.

Current stats for `library/signal.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 119
- Untranslated: 119

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by VladimirGonzalez** [comment]
Quiero traducir este.. me lo podría asignar?

**Comment by cmaureir** [comment]
éxito con la traducción! :tada:

**Comment by cmaureir** [comment]
@VladimirGonzalez  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by alochimpasplum** [comment]
Hola, buenos días.

¿Me podríais asignar esta tarea por favor?

**Comment by cmaureir** [comment]
Claro @alochimpasplum, éxito con la traducción!
Recuerda que estamos en el discord de HacktoberfestES si es que te inscribiste, si no, tenemos un grupo de telegram en caso de preguntas.

**Comment by alochimpasplum** [comment]
Gracias! Más tarde me meto al discord ☺

**Comment by alochimpasplum** [comment]
Hola! Voy bastante de cráneo con el tema traducción... he traducido 1/6 parte del documento, pero no sé si podré continuarlo en al menos una o dos semanas, ¿queréis que haga un merge mientras no pueda continuarlo?

**Comment by cmaureir** [comment]
Claro, mejor que abras un draft. Igual es probable que en 1-2 semanas alguien pase por el PR a preguntar como vas, pero es mejor que el issue quede asignada sin actividad ;)
