### ISSUE TITLE
Translate `library/socketserver.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#514]
This needs to reach 100% translated.

Current stats for `library/socketserver.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 79
- Untranslated: 79

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by VladimirGonzalez** [comment]
Me gustaría traducir este

**Comment by cmaureir** [comment]
buenisimo @VladimirGonzalez ! Gracias! y mucha suerte con la traducción :tada:

**Comment by cmaureir** [comment]
@VladimirGonzalez  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by clacri** [comment]
Hola @VladimirGonzalez veo que también tienes asignada la issue #513. De cara al hacktoberfest nos gustaría establecer que cada persona se ocupe de una issue a la vez y cuando la acabe continúe con la siguiente. Podrías decirnos cual de ambas quieres ocuparte? En caso de que ya hubieras empezado ambas no pasa nada, pero dinoslo :) Asimismo, si necesitas una mano con la que tengas en marcha o quieres hacer un PR parcial de ellas es una buena opción. Un saludo!

**Comment by VladimirGonzalez** [comment]
Hola Como va, mil disculpas estos dias tuve que mudarme a otra ciudad y
estuve un poco complicado, me quedo traduciendo el #514 Socketserver

**Comment by clacri** [comment]
genial :) no te preocupes y muchas gracias!
