### ISSUE TITLE
Translate `license.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#515]
This needs to reach 100% translated.

Current stats for `license.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 91
- Untranslated: 91

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by zejiran** [comment]
I want to be assigned.

**Comment by cmaureir** [comment]
Grande @zejiran ! suerte con la traducción :tada:

**Comment by humitos** [comment]
This is probably a mistake. Do not translate this file. It's the license.

Please, do not do it! 😀

**Comment by humitos** [comment]
Pick another one 😉
