### ISSUE TITLE
Translate `library/email.message.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#519]
This needs to reach 100% translated.

Current stats for `library/email.message.po`:

- Fuzzy: 0
- Percent translated: 54%
- Entries: 55 / 103
- Untranslated: 48

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by gabrielBarbacil** [comment]
¡Hola!¿Puedo hacerla?

**Comment by humitos** [comment]
Adelante! Recuerda seguir la guía de contribución 💪

**Comment by cmaureir** [comment]
Queda disponible lo restante del archivo, solo son 48 entradas. Especial para alguien que quiera comenzar :+1:

**Comment by psicobloc** [comment]
Hola! puedo ayudar con este issue? se refiere a la página: https://docs.python.org/es/3.8/library/email.message.html#email.message.EmailMessage   ?

**Comment by cmaureir** [comment]
Dale @psicobloc :tada: éxito!
Si, es ese archivo completo, no solo la sección que tiene tu enlace.
