### ISSUE TITLE
Translate `library/xml.dom.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#522]
This needs to reach 100% translated.

Current stats for `library/xml.dom.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 234
- Untranslated: 234

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by hristoroque** [comment]
Me gustaría traducir este archivo

**Comment by cmaureir** [comment]
Genial @hristoroque ! Buena suerte :dancers:

**Comment by cmaureir** [comment]
@hristoroque  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by hristoroque** [comment]
Falta cerrar este issue @cmaureir
