### ISSUE TITLE
Translate `library/pydoc.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#552]
This needs to reach 100% translated.

Current stats for `library/pydoc.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 19
- Untranslated: 19

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by hristoroque** [comment]
Me gustaría traducir este archivo, aunque actualmente estoy traduciendo xml.dom pero ese archivo es tiene muchas entradas y me llevará tiempo terminarla, puedo traducir pydoc mientras hago xml.dom.

**Comment by cmaureir** [comment]
Ok! pero no te cargues mucho @hristoroque !
