### ISSUE TITLE
Translate `library/shlex.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#554]
This needs to reach 100% translated.

Current stats for `library/shlex.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 71
- Untranslated: 71

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by estebansolo** [comment]
Hola, podría tomar este issue?

**Comment by cmaureir** [comment]
Bien @estebansolo :tada: :tada: !

**Comment by cmaureir** [comment]
@estebansolo  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by estebansolo** [comment]
Si he tenido unos inconveniences y he avanzado poco, sin embargo tratare de terminarlo este fin de semana.

**Comment by cmaureir** [comment]
Gracias @estebansolo, espero que te encuentres bien y que no hayan tantos problemas.
De todas formas, es mejor que subas lo que tienes, y así si en algún momento no puedes seguir, alguien más lo puede tomar.
Ánimo! :tada:
