### ISSUE TITLE
Translate `library/zipapp.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#555]
This needs to reach 100% translated.

Current stats for `library/zipapp.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 79
- Untranslated: 79

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by juansemarquez** [comment]
Me gustaría contribuir con traduciendo este archivo.
I'd like to contibute translating this file.
Juan.

**Comment by cmaureir** [comment]
Bien @juansemarquez !!! :tada: mucho éxito!
