### ISSUE TITLE
Translate `library/gzip.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#557]
This needs to reach 100% translated.

Current stats for `library/gzip.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 56
- Untranslated: 56

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by hellocoldworld** [comment]
Hello! I'm available to work in this one, since this is my first collab I could have a version by the end of the week, approximately.

**Comment by cmaureir** [comment]
Hola @hellocoldworld , mucho éxito con la traducción.

**Comment by cmaureir** [comment]
@hellocoldworld  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by clacri** [comment]
hola @hellocoldworld, podrías confirmarnos si sigues interesado en hacer esta issue? para liberarla en caso contrario. Un saludo!

**Comment by cmaureir** [comment]
Dejando libre la issue.

**Comment by alcides29** [comment]
Buenas, podría encargarme de esta traducción

**Comment by cmaureir** [comment]
Gracias @alcides29, éxito con la traducción!
