### ISSUE TITLE
Translate `library/mmap.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#569]
This needs to reach 100% translated.

Current stats for `library/mmap.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 47
- Untranslated: 47

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by hristoroque** [comment]
May I translate this file?

**Comment by mayuti** [comment]
Hola @humitos. Podrías asignarme el archivo?. Saludos.

**Comment by cmaureir** [comment]
Grande @hristoroque :tada:

**Comment by cmaureir** [comment]
@hristoroque  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by clacri** [comment]
Lo cierro porque se mergeó en https://github.com/python/python-docs-es/pull/607
