### ISSUE TITLE
Translate `library/wsgiref.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#570]
This needs to reach 100% translated.

Current stats for `library/wsgiref.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 115
- Untranslated: 115

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by ifosch** [comment]
@cmaureir Si no ves inconveniente, me pongo con esta traducción

**Comment by cmaureir** [comment]
Claro que no! Vamos con todo @ifosch  :tada:

**Comment by cmaureir** [comment]
@ifosch  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by ifosch** [comment]
@cmaureir Esta semana estaré algo liado, pero la siguiente espero poderme poner y acabarlo (llevo más del 50% del fichero) y, quizás, coger otro más. Si hay alguien que lo quiera continuar, puedo subir lo que tengo y así no bloqueo a nadie.

**Comment by cmaureir** [comment]
Genial @ifosch, si puedes subir un draft de lo que llevas sería genial y si luego de eso sientes que no puedes continuar, y se lo asignamos a alguien más. Gracias :+1:
