### ISSUE TITLE
Translate `library/email.policy.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#572]
This needs to reach 100% translated.

Current stats for `library/email.policy.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 101
- Untranslated: 101

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by hristoroque** [comment]
Quiero traducir este archivo.

**Comment by cmaureir** [comment]
Genial @hristoroque :tada: :tada:

**Comment by cmaureir** [comment]
@hristoroque  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by clacri** [comment]
La cierro porque se mergueó en https://github.com/python/python-docs-es/pull/634
