### ISSUE TITLE
Translate `howto/curses.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#573]
This needs to reach 100% translated.

Current stats for `howto/curses.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 105
- Untranslated: 105

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by halcolo** [comment]
Me gustaría trabajar en este por favor.

**Comment by humitos** [comment]
Hola @halcolo! Excelente! Adelante! Recuerda seguir los pasos de la Contributing Guide!
