### ISSUE TITLE
Translate `library/dbm.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#574]
This needs to reach 100% translated.

Current stats for `library/dbm.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 74
- Untranslated: 74

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by katialira** [comment]
🙋‍♀️ pido este ticket y prometo no tardarme un mes :)

**Comment by Argibaycg** [comment]
Buenas, no sé si podre tomar este archivo para comenzar, es mi primer intento de colaborar y no veo otros disponibles, gracias

**Comment by cmaureir** [comment]
Hola @Argibaycg, vamos por orden, así que se lo asignamos a @katialira y luego cuando generemos mas issues, te puedes apuntar con alguno. De todas formas, hay muchos PR abiertos que corregir, y actualmente es nuestro cuello de botella y nos vendría super bien una mano! a ver si te animas  a ayudarnos a corregir :+1:

**Comment by clacri** [comment]
Hola @katialira voy a cerrar la issue porque he visto que ya estaba mergeada. La manera de que esto se haga automáticamente es que pongas el siguiente mensaje en la descripción:

Closes #n 

donde n es el numero de la issue. Como tu lo pusiste quedó linkada eso sí, asi que ahora es facil ver que se puede cerrar :) Muchas gracias por tu trabajo, un saludo!!!
