### ISSUE TITLE
Translate `library/locale.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#576]
This needs to reach 100% translated.

Current stats for `library/locale.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 140
- Untranslated: 140

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by mrcmoresi** [comment]
Hello! I'm available to work in this one, since this is my first collab I could take longer than expected but I want to work on this.

**Comment by humitos** [comment]
@mrcmoresi hágale pues! gracias por colaborar con este proyecto :smile: . Recuerda seguir la Contributing Guide y si tienes alguna duda puedes preguntarnos sin problema.
