### ISSUE TITLE
Translate `howto/clinic.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#577]
This needs to reach 100% translated.

Current stats for `howto/clinic.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 415
- Untranslated: 415

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by cmaureir** [comment]
Bueno, con tantas entradas, creo que nadie se va a querer matricular con esta, así que creo que tardaré un tiempo, pero me la asigno igual jaja Challenge accepted.

**Comment by cmaureir** [comment]
El archivo es bastante largo, así que subiré un draft pronto. pero voy como en el 50%
