### ISSUE TITLE
Translate `library/imp.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#578]
This needs to reach 100% translated.

Current stats for `library/imp.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 68
- Untranslated: 68

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Jighdan** [comment]
Me lo llevo :hand:

**Comment by cmaureir** [comment]
Gracias @Jighdan, mucha suerte con la traducción!

**Comment by Jighdan** [comment]
Hey - 
Se que me he estado retrasando un poco con esta traduccion, pero aun quisiera ser quien la termine.

**Comment by cmaureir** [comment]
Mucho ánimo @Jighdan !!!
