### ISSUE TITLE
Translate `library/bisect.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#580]
This needs to reach 100% translated.

Current stats for `library/bisect.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 17
- Untranslated: 17

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by juansemarquez** [comment]
Quisiera colaborar con este breve archivo.

**Comment by humitos** [comment]
Hola @juansemarquez! Excelente! Adelante! Recuerda seguir los pasos de la Contributing Guide!
