### ISSUE TITLE
Translate `library/asyncio-stream.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#582]
This needs to reach 100% translated.

Current stats for `library/asyncio-stream.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 76
- Untranslated: 76

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Diavolo** [comment]
Hola, me gustaría ayudar con esta tarea.

**Comment by cmaureir** [comment]
Gracias @Diavolo :tada: Mucho éxito en la traducción. Nos puedes encontrar en el grupo de telegram :)

**Comment by cmaureir** [comment]
@Diavolo  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by Diavolo** [comment]
@cmaureir disculpa por el retraso, la semana pasada no pude darle tiempo para trabajar en el archivo. Ya me puse a trabajar en el, así que debería de tenerlo en un par de días.

**Comment by cmaureir** [comment]
Perfecto, gracias @Diavolo. De todas formas, si ves que no puedes seguir, puedes hacer un Pull-request con lo que llevas y así alguien más lo continúa. éxito!
