### ISSUE TITLE
Translate `library/email.parser.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#590]
This needs to reach 100% translated.

Current stats for `library/email.parser.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 47
- Untranslated: 47

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by hristoroque** [comment]
Me gustaría hacer este.

**Comment by cmaureir** [comment]
genial @hristoroque :tada: !

**Comment by cmaureir** [comment]
@hristoroque  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by clacri** [comment]
Hola @hristoroque estoy cerrando esta issue porque he visto que ya estaba mergeada la traducción en https://github.com/python/python-docs-es/pull/632 Una forma de que las issues se cierren automáticamente es que las linkes en las PR poniendo Closes #n donde n es el numero de la issue.
