### ISSUE TITLE
Translate `library/nntplib.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#591]
This needs to reach 100% translated.

Current stats for `library/nntplib.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 84
- Untranslated: 84

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by natayafs** [comment]
Can you assign this to me?

**Comment by raulcd** [comment]
assigned, thanks @natayafs , happy translation!

**Comment by cmaureir** [comment]
@natayafs te podemos ayudar en algo con este archivo? quizás si llevas una parte, puedes subirlo como draft así vamos corrigiendo pronto.
