### ISSUE TITLE
Translate `faq/extending.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#592]
This needs to reach 100% translated.

Current stats for `faq/extending.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 60
- Untranslated: 60

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by jcantilo** [comment]
puedo encarar este?

**Comment by cmaureir** [comment]
Grande @jcantilo  :tada: !
Mira que hay varios PRs abiertos sobre extending/*
Ante alguna duda, mejor mirar esos para asi tener consistencia :)
