### ISSUE TITLE
Translate `library/bdb.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#593]
This needs to reach 100% translated.

Current stats for `library/bdb.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 92
- Untranslated: 92

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by geekcoty** [comment]
¡Hola! 
Me gustaría ayudar a traducir este archivo :)

**Comment by cmaureir** [comment]
Buenísimooooo, gracias @geekcoty :tada: Mucho éxito con la traducción.

**Comment by geekcoty** [comment]
¡Gracias!

**Comment by cmaureir** [comment]
@geekcoty si has tenido algún problema de moment, avisanos, y de seguro te podemos dar una mano. Lo mismo que cuando lleves un poco traducido, podrias subir un PR como draft y así vamos corrigiendo.

**Comment by geekcoty** [comment]
¡Buenos dias!
Me duele en el alma pero se me complicó la vida academica este cuatrimestre y no puedo dedicarle el tiempo que quería a la traducción por lo que me tengo que bajar  del proyecto :( La verdad estaba muy ilusionada y espero volver cuando termine el cuatrimestre, si no hay problema.

**Comment by fjsevilla-dev** [comment]
¡Hola! Me gustaría poder retomar éste si es posible.

**Comment by cmaureir** [comment]
Genial, gracias @fjsevilla-dev :tada:
