### ISSUE TITLE
Translate `howto/pyporting.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#599]
This needs to reach 100% translated.

Current stats for `howto/pyporting.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 85
- Untranslated: 85

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Luck547** [comment]
Quiero trabajar en él.
I wish to work on it.

**Comment by cmaureir** [comment]
Genial! Buena suerte con la traducción @Luck547 :tada:

**Comment by clacri** [comment]
Este documento seguro se consulta bastante y es un tema interesante :) me encantaría hacer review cuando ya haya alguna PR. Por cierto @Luck547 que si necesitas cualquier cosa por aquí estamos!!!

**Comment by cmaureir** [comment]
@Luck547 recuerda que puedes subir lo que lleves como draft, para que te vayamos ayudando.

**Comment by clacri** [comment]
Hola @Luck547  si necesitas cualquier ayuda con la traducción o la parte técnica de github haznoslo saber por aqui o por telegram. Igualmente puedes hacer una PR si está parcialmente traducido. Y en caso no vayas a poder completarlo no pasa nada, dinoslo y lo liberamos para que otra persona lo continue. Un saludo y muchas gracias!

**Comment by Luck547** [comment]
Ok @clacri  Gracias... me salió trabajo y más no pude continuar... podeis pasarlo y a seguir!! Un saludo y muchas gracias!

**Comment by clacri** [comment]
Pero tenías algo parcial?

**Comment by Luck547** [comment]
Nones

**Comment by yeyeto2788** [comment]
@clacri, @cmaureir si todavia esta pendiente este issue puedo encargarme yo. Seria desde la rama de 3.8?

**Comment by cmaureir** [comment]
Gracias @yeyeto2788, si, sería desde la rama 3.8
