### ISSUE TITLE
Translate `library/http.cookiejar.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#601]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/http.cookiejar.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/http.cookiejar.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 153
- Untranslated: 153

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by alphacentauri82** [comment]
Can you assign this to me please!

**Comment by cmaureir** [comment]
Genial @alphacentauri82 :tada: :tada: mucha suerte con la traducción!

**Comment by cmaureir** [comment]
@alphacentauri82  te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otra persona continué con el.

**Comment by clacri** [comment]
@alphacentauri82  si necesitas cualquier ayuda con la traducción o la parte técnica de github haznoslo saber por aqui o por telegram. Abrir un PR aunque la traduccion sea parcial es una buena opcion para recibir feedback temprano o en caso no vayas a poder terminar la traducción completa. Si como comenta Cristian no tienes tiempo tambien dinoslo y la podemos dejar libre. Un saludo y muchas gracias!

**Comment by alphacentauri82** [comment]
Uhhh no no perdón lo termino hoy. Tuve algunos contratiempos de salud pero ya estoy a punto!! Muchas gracias!!

**Comment by clacri** [comment]
No te preocupes, no era para ponerte presión, solo para saberlo :) un saludo, me alegro de tu recuperación y no te preocupes en absoluto, simplemente era un check!

**Comment by cmaureir** [comment]
@alphacentauri82 como vas?

**Comment by cmaureir** [comment]
dejando este issue libre

**Comment by GibranHL0** [comment]
Hola, me gustaría que me asignaras este issue si todavía está disponible. 😄

**Comment by cmaureir** [comment]
Hecho @GibranHL0, mucho éxito!
