### ISSUE TITLE
Translating `library/functions.po`

### ISSUE THREAD

**Issue by clacri** [python/python-docs-es#61]
I will take care of this file

**Comment by humitos** [comment]
Done in #218

**Comment by clacri** [comment]
No está acabado el fichero, entiendo que la issue debería quedarse abierta hasta que lo termine no? Mañana pensaba ponerme a seguir traduciendo, ya que los días anteriores me centré en reviews. Si acaso la próxima PR que hago del fichero la dejo en draft hasta que termine, te parece bien @humitos ?

**Comment by humitos** [comment]
Uy, perdón! Mala mía.

Sí, el issue lo dejamos abierto hasta que esté terminada la tarea.

Buena idea la de dejar el PR en Draft hasta que esté listo para review 👍

**Comment by humitos** [comment]
Puedes crear otra branch desde 3.8 (actualizada) y una nueva PR

**Comment by clacri** [comment]
Vale perfecto, hoy traduciré algún parrafito y haré eso de dejarlo como draft. Muchas gracias!

**Comment by humitos** [comment]
Re-open it since the document is not finished :smile:
