### ISSUE TITLE
pre-commit fix

### ISSUE THREAD

**Issue by clacri** [python/python-docs-es#661]
Parece que hay un error con pre-commit y ahora no se corresponde con nuestro building process. No sé nada de como arreglarlo pero estaría genial echarle un vistazo.

**Comment by cmaureir** [comment]
el cambio que se hizo a nuestro proceso de crear los docs fue pasar de:
```
cat dict dictionaries/*.txt > dict.txt
pospell -p dict.txt .....
```
por
```
awk 1 dict dictionaries/*.txt > dict.txt
pospell -p dict.txt .....
```
Solo para evitar el problema cuando algunos archivos no tenian un 'salto de línea' al final de ellos (no confundir con una línea en blanco).

Quizás pre-commit tiene algo interno donde hace ese proceso y se pueda arreglar, quizás podrías ver algun archivo de configuración cuando se instala.

**Comment by clacri** [comment]
El fichero de configuración de pre commit es este https://www.github.com/python/python-docs-es/tree/3.8/.pre-commit-config.yaml pero entiendo que el chequeo de pospell es una llamada a un script/hook como se llame en el repo de humitos. Le echo un vistazo

**Comment by clacri** [comment]
Creo que es más simple, tenemos que cambiar la llamada al pospell en el fichero yaml del pre-commit para que utilice el fichero global no? Ya no es más un dict en esa carpeta sino el generado de nuestro set. Mañana me lo miro en el ordenador que estoy con el móvil y medio dormida.

**Comment by humitos** [comment]
Me asigno este para arreglarlo cuando tenga un tiempito

**Comment by clacri** [comment]
genial! Sólo por curiosidad, por lo que he entendido viendo tu codigo y el pre-commit config en realidad solo son llamadas a scripts que hay en diferentes repositorios. En el caso de nuestro pre-commit aun estaba haciendo la llamada a pospell con nuestro fichero dict (que generabamos nosotros y siempre estaba creado). Pero ahora tenemos q añadir un paso más. Entonces que hay que hacer, hacer un script q haga lo de awk, ponerlo en un repo y añadir ese hook entre el de powrap y el de pospell?
