### ISSUE TITLE
Translate `library/mailcap.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#666]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/mailcap.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/mailcap.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 12
- Untranslated: 12

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by mxarc** [comment]
Me gustaría trabajar en este issue 🤗

**Comment by cmaureir** [comment]
Mejor que vayamos de a uno, así que cuando termines el anterior #188 te asignamos este si aún está libre ;)

**Comment by mxarc** [comment]
> Mejor que vayamos de a uno, así que cuando termines el anterior #188 te asignamos este si aún está libre ;)

¡Listo! Estoy entusiasmado por poder iniciar con esta traducción
