### ISSUE TITLE
cómo imprimimos el tutorial en PDF con este nuevo formato?

### ISSUE THREAD

**Issue by gilgamezh** [python/python-docs-es#67]
históricamente PyAr imprime el tutorial para repartirlo en eventos. Podemos seguir haciendolo? cómo?

**Comment by humitos** [comment]
```bash
sphinx-build -b latex ...
latexmk ...
```

Le podríamos decir a RTD que lo haga por nosotros, también.

Lo que teníamos en PyAr de diferente son los estilos personalizados y el tamaños. Habría que revisar qué leía `rst2pdf` --si leía una hoja de estilos de latex, podríamos usar lo mismo.

**Comment by humitos** [comment]
Acá compilé una versión en PDF de la branch 3.8: https://python-docs-es.readthedocs.io/_/downloads/es/3.8/pdf/ --se ve bien.

**Comment by gilgamezh** [comment]
@facundobatista

**Comment by facundobatista** [comment]
Está bueno ese PDF (aunque tiene el "whats new in python 2.6, no tiene sentido).

Puntualmente para imprimrlo: está bueno que deja las páginas en blanco para que los capítulos arranquen "del lado izquierdo". 

Podría tener margen extra "del lado del abrochado" de cada página.

Lo que sí habría que tocarle son los colores, ya que en general para abaratar costos la impresión es en B&N.

**Comment by humitos** [comment]
> Está bueno ese PDF (aunque tiene el "whats new in python 2.6, no tiene sentido).

Esto se puede eliminar cambiando el `contents.rst`, o bien, dándole un `contents.rst` específico con lo único que nos interesa que esté en el PDF.

Read the Docs no soporta múltiples PDF como output así de una, pero se podría hacer (medio hacky teniendo varias ramas) y construir el Tutorial por un lado y el resto por otro.

> Puntualmente para imprimrlo: está bueno que deja las páginas en blanco para que los capítulos arranquen "del lado izquierdo".
> Podría tener margen extra "del lado del abrochado" de cada página.
> Lo que sí habría que tocarle son los colores, ya que en general para abaratar costos la impresión es en B&N.

Esto se puede cambiar con hojas de estilo de LaTeX, pero yo no tengo mucha experiencia ahí.

**Comment by humitos** [comment]
> Read the Docs no soporta múltiples PDF como output así de una, pero se podría hacer (medio hacky teniendo varias ramas) y construir el Tutorial por un lado y el resto por otro.

Referencia para mi yo del futuro: https://github.com/readthedocs/readthedocs.org/blob/d45ad2b07c9f0577da86d2f76724b6469ad79b3e/readthedocs/doc_builder/backends/sphinx.py#L603-L626 --ahí es donde se decide qué output de los N PDFs se van a copiar.

**Comment by humitos** [comment]
Algo que no mencioné, pero es interesante. Esta versión y la anterior, ambas usan Sphinx, así que si quisieramos seguir utilizando el mismo proceso lo podríamos hacer a mano.

Sin embargo, algunos `PageBreak` que se agregaron a mano en el tutorial para hacer que `rst2pdf` haga un salto de página, no van a poder ser posible fácilmente. Igual, creo que `rst2pdf` no está mantenido.

**Comment by humitos** [comment]
Ahora que estamos bajo la documentación oficial, veo que ellos están construyendo todos los PDF para la versión en español también: https://docs.python.org/es/3.8/download.html

Supongo, igualmente, que no es exactamente lo que queremos, pero no quería dejar de mencionarlo en este issue.

**Comment by cacrespo** [comment]
Buenas! Estamos trabajando en este issue. Dejo por acá algunas notas:

Por el momento hay dos opciones: 
- Exportar los archivos LaTex del bloque del tutorial, modificar lo que nos parezca necesario y luego generar el .pdf.
Se necesita [cambiar 'conf.py'](https://github.com/python/python-docs-es/pull/116/files#diff-6e03d3d89630aba3403afea3514a3ac5948e70d1ced091012e56446f614da340R64), hacer un build local y luego ejecutar
```
sphinx-build -j auto -W --keep-going -b latex -d cpython/Doc/build/doctree/tutorial -D language=es . tutorial_latex
```

Este es el resultado: 
https://github.com/cacrespo/python-docs-es/tree/tutorial_pdf/tutorial_latex

Con esos archivos pude generar un [pdf](https://github.com/cacrespo/python-docs-es/blob/tutorial_pdf/tutorial_latex/python-docs-es.pdf) similar al que está disponible en el sitio oficial (lo que menciona humitos en el comment anterior).

- Otra opción es tomar justamente ese PDF de la versión en español y trabajar directamente sobre `tutorial.pdf`. Supongo que podremos cambiar algunas cosas más o menos fácil pero debe limitar bastante las posibilidades.

**Comment by humitos** [comment]
Me pareció leer en el Telegram que hubo avances con este issue. @cacrespo ¿sabés algo vos? En ese caso, ¿podés actualizar el issue con un comentario sobre el "nuevo estado de esto"?

**Comment by cacrespo** [comment]
:wave: Así es. Hemos avanzado bastante desde aquella vez.

Nos decidimos por la primera opción y en [este repositorio](https://github.com/cacrespo/tutorial_python_ES) está el paso a paso para construir el pdf con varios ajustes que fuimos decidiendo en el camino. 
Si bien es prácticamente la versión final, para el caso de la tapa y contratapa vamos a retocarla y embellecerla manualmente. Además incluimos una página con información "legal" adhoc ("prohibida su venta" y cosas por el estilo). 

En el mes de noviembre apuntamos a realizar una primera impresión y evaluar qué tal fue.

Me gustaría mover el repositorio una vez que esté definitivo el material. No sé si aquí o a PyAr o a dónde... ¿qué te parece?

**Comment by humitos** [comment]
> Me gustaría mover el repositorio una vez que esté definitivo el material. No sé si aquí o a PyAr o a dónde... ¿qué te parece?

Yo creo que sería bueno moverlo a PyAr de momento ya que es un repositorio distinto y no tenemos una organización que controlemos nosotros acá. Igualmente, es posible que podamos fusionarlo más adelante si es que _no necesitamos_ todo un repo. Más detalles en https://github.com/cacrespo/tutorial_python_ES/issues/2

Creo que podemos cerrar este issue y seguir en el otro repositorio con esta charla y demás.
