### ISSUE TITLE
Translate `library/tkinter.tix.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#670]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/tkinter.tix.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/tkinter.tix.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 71
- Untranslated: 71

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by hristoroque** [comment]
I'd like to translate this issue.

**Comment by cmaureir** [comment]
Éxito con la traducción! a ver si te tiras a la piscina y traduces uno más largo para la próximo @hristoroque :)

**Comment by hristoroque** [comment]
Pensé de 71 entradas era largo 😔
