### ISSUE TITLE
Translate `library/tracemalloc.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#673]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/tracemalloc.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/tracemalloc.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 134
- Untranslated: 134

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by samvaldez** [comment]
Hola, me pueden asignar este issue?

**Comment by cmaureir** [comment]
> Hola, me pueden asignar este issue?

Hola! vi que aún tienes asignada otra issue abierta: https://github.com/python/python-docs-es/issues/478
Te parece mejor que cuando acabes esa te asignemos otra? así evitamos cargar mucho a la gente por cosas por hacer :dancers:

**Comment by bleucode** [comment]
Hola! Soy nueva, me pueden asignar este task?

**Comment by cmaureir** [comment]
Listo @bleucode ! mucho éxito en la traducción. Cualquier duda, estamos en telegram. Si en algún momento sientes que no puedes seguir con la traducción, te recomendamos que subas un PR como draft y así alguien más puede continuar tu trabajo. Gracias :tada:

**Comment by clacri** [comment]
Hola @bleucode ,  si necesitas cualquier ayuda con la traducción o la parte técnica de github haznoslo saber por aqui o por telegram. Como comenta @cmaureir es buena idea subir una draft como PR, incluso aunque aun no hayas finalizado la traducción (y quieras hacerlo) porque de esa forma recibes feedback temprano y tus cambios van quedando guardados. Un saludo y muchas gracias!

**Comment by bleucode** [comment]
Holis, yo termine la traducción e hice un push origin, no entiendo que debo hacerlo para cerrarlo? Gracias @clacri

**Comment by clacri** [comment]
Hola! Entiendo por tu mensaje que has hecho la traducción localmente  en tu fork del repositorio? Para poder continuar el proceso, necesitamos que hagas una pull request desde tu fork a nuestro repositorio principal, de forma que alguien pueda revisar tu traducción. Los pasos para hacerlo están descritos en nuestra guía de contribución pero quizás es más sencillo con este vídeo que ha preparado @cmaureir : https://www.youtube.com/watch?v=hbHNTIrxSzk&list=PLma583Z70SlztPF8SitlWJZx3SW1aAePk&index=2
