### ISSUE TITLE
Translate `library/asynchat.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#674]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/asynchat.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/asynchat.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 33
- Untranslated: 33

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by dalai2** [comment]
Hola, me pueden asignar este issue para traduccion por favor?

**Comment by cmaureir** [comment]
Listo @dalai2 ! Mucho éxito con la traducción :dancers:

**Comment by clacri** [comment]
Hola @dalai2 , si necesitas cualquier ayuda con la traducción o la parte técnica de github haznoslo saber por aqui o por telegram. Un saludo y muchas gracias!

**Comment by cmaureir** [comment]
@dalai2 te podemos ayudar en algo?

**Comment by cmaureir** [comment]
dejando esta issue libre

**Comment by David-Lor** [comment]
Hola! Me podría poner con esta traducción

**Comment by cmaureir** [comment]
gracias @David-Lor :tada: éxito!
