### ISSUE TITLE
Translate `library/parser.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#675]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/parser.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/parser.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 49
- Untranslated: 49

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by gomezgleonardob** [comment]
Please, assign me

**Comment by cmaureir** [comment]
@gomezgleonardob vamos de a uno mejor. Cuando acabes el que ya tienes #667  vamos asignando el siguiente :)

**Comment by fjsevilla-dev** [comment]
Me gustaría traducir este.

**Comment by cmaureir** [comment]
Gracias @fjsevilla-dev :tada: éxito!
