### ISSUE TITLE
Translate `library/email.headerregistry.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#676]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/email.headerregistry.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/email.headerregistry.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 103
- Untranslated: 103

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by mjmolina** [comment]
Me gustaría traducir este :)

**Comment by cmaureir** [comment]
Listo, éxito con la traducción!

**Comment by cmaureir** [comment]
@mjmolina te podemos ayudar con algo?

**Comment by mjmolina** [comment]
Hola!

Tengo el archivo traducido al 90% :) ! Espero hacer el PR en breve!

Gracias por la paciencia!
