### ISSUE TITLE
Translate `library/stat.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#678]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/stat.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/stat.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 81
- Untranslated: 81

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by eantob** [comment]
¡Hola @humitos! Long time no see since WTD Prague last year. I'd like to work on this task!

**Comment by humitos** [comment]
@eantob Hola hola! Te asigno este issue así puedes trabajar :smile:. Un gusto verte por acá!

**Comment by cmaureir** [comment]
Dejo libre el issue. Si tenías algo parcial, seria genial que lo subieras ;)

**Comment by ricrogz** [comment]
Si este issue ha quedado libre, ¿puedo ocuparme yo?

**Comment by cmaureir** [comment]
Claro @ricrogz :tada: mucho éxito
