### ISSUE TITLE
Translate `library/audioop.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#679]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/audioop.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/audioop.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 45
- Untranslated: 45

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by hristoroque** [comment]
Me gustaría traducir esta documento

**Comment by cmaureir** [comment]
Listo! @hristoroque el próximo archivo si que tiene que ser uno más largo, eh! ya tienes bastante experiencia y es mejor dejar los cortos para gente que vaya a comenzar a colaborar :) éxito con la traducción!

**Comment by hristoroque** [comment]
Ya :)
