### ISSUE TITLE
Translate `library/lzma.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#680]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/lzma.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/lzma.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 107
- Untranslated: 107

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by fenriquegimenez** [comment]
Me asignan esta traducción por favor? Gracias!

**Comment by cmaureir** [comment]
Esa es la actitud @fenriquegimenez ! ya estás más que preparado para este archivo de más de 100 entradas :tada: mucho éxito con la traducción!
