### ISSUE TITLE
Translate `library/errno.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#681]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/errno.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/errno.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 128
- Untranslated: 128

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by FedericoJurio** [comment]
Me lo asignan?

**Comment by eamanu** [comment]
ping @humitos @cmaureir

**Comment by humitos** [comment]
Hola @FedericoJurio! Gracias por participar! Te asigno el issue así puedes trabajar :smile:

**Comment by FedericoJurio** [comment]
El PR está listo para ser revisado

**Comment by eamanu** [comment]
@FedericoJurio ahi te dejé unos comments

**Comment by FedericoJurio** [comment]
Gracias @eamanu ! Vi tus comentarios, en cuanto tenga la oportunidad trabajo en eso :)
