### ISSUE TITLE
Translate `library/shelve.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#682]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/shelve.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/shelve.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 31
- Untranslated: 31

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Alvaruz** [comment]
me asignas este por favor

**Comment by cmaureir** [comment]
Vale! Luego de esta @Alvaruz nos tenemos que enfocar de hacer el merge de ambos PRs antes de asignar un tercero ;) Gracias!

**Comment by Alvaruz** [comment]
roger that
