### ISSUE TITLE
Translate `library/code.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#684]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/code.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/code.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 31
- Untranslated: 31

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by cacrespo** [comment]
Lo tomo!

**Comment by cmaureir** [comment]
grande Carlos!
