### ISSUE TITLE
Translate `library/fnmatch.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#685]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/fnmatch.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/fnmatch.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 23
- Untranslated: 23

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by alycolbar** [comment]
Hola @humitos, quisiera contribuir con este :smile:

**Comment by humitos** [comment]
Wow! Se ve que llegué tarde :D

**Comment by alycolbar** [comment]
> Wow! Se ve que llegué tarde :D

no importa, me di cuenta además que no agregue mi nombre entre los traductores. Asi que próximamente verás otra contribución mia ~ヾ(＾∇＾)
