### ISSUE TITLE
Translate `library/crypt.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#686]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/crypt.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/crypt.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 29
- Untranslated: 29

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Diavolo** [comment]
Hola, me gustaría ayudar con esta tarea.

**Comment by cmaureir** [comment]
Ya con este te graduas @Diavolo :tada:, y que el próximo ya tengas un archivo con más entradas, así dejamos estos cortos para gente que esté comenzando :+1:
