### ISSUE TITLE
Translate `library/filesys.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#688]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/filesys.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/filesys.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 8
- Untranslated: 8

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by FedericoJurio** [comment]
Me lo asignan?

**Comment by cmaureir** [comment]
Te asigné otro de 10 entradas @FedericoJurio, te parece si dejamos este para alguien que vaya a comenzar?

**Comment by FedericoJurio** [comment]
Buena idea @cmaureir !

**Comment by a19c** [comment]
Hola Buenas noches me lo podrian asignar?

**Comment by clacri** [comment]
Hola @a19c , si necesitas ayuda con algún aspecto de la traducción o la parte técnica no dudes en contactarnos por github o telegram.  Muchas gracias por encargarte de la issue, y un saludo!

**Comment by a19c** [comment]
Hola, gracias por la ayuda seguramente en esta semana escriba en el grupo
de telegram, estoy ayudando a un compañero que estaba atrasado en tareas y
en la parte también de documentación y me pidió ayuda en lo de traducción.
Esta semana voy a hacer el pr sin falta! Muchísimas gracias por
contactarte

**Comment by cmaureir** [comment]
@a19c te podemos ayudar con algo?

**Comment by cmaureir** [comment]
dejando esta issue libre

**Comment by yeyeto2788** [comment]
@cmaureir puedo encargarme de este issue?

**Comment by cmaureir** [comment]
Claro, mucho éxito! @yeyeto2788
