### ISSUE TITLE
Translate `library/pyexpat.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#689]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/pyexpat.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/pyexpat.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 128
- Untranslated: 128

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by EduFriesen00** [comment]
hola como vas? me la podrían asignar?

**Comment by cmaureir** [comment]
Hola @EduFriesen00, muchas gracias por tu interés. Mucho éxito con la traducción! cualquier duda estamos en Telegram.
