### ISSUE TITLE
Translate `library/poplib.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#690]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/poplib.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/poplib.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 49
- Untranslated: 49

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by fenriquegimenez** [comment]
Please let me take this one, I want to start contributing with the project.

**Comment by cmaureir** [comment]
listo, gracias @fenriquegimenez :tada: buena suerte

**Comment by fenriquegimenez** [comment]
Dejé un pull request nuevo con las indicaciones recibidas, aguardo feedback :) #764
