### ISSUE TITLE
Translate `library/trace.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#691]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/trace.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/trace.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 39
- Untranslated: 39

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by FedericoJurio** [comment]
Me asignan esta tarea?

**Comment by cmaureir** [comment]
Muchas gracias @FedericoJurio ! éxito con la traducción :)

**Comment by FedericoJurio** [comment]
El PR está listo para ser revisado
