### ISSUE TITLE
Translate `library/getpass.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#693]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/getpass.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/getpass.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 10
- Untranslated: 10

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by FedericoJurio** [comment]
Me lo asignan?

**Comment by cmaureir** [comment]
Genial @FedericoJurio, con esta ya te gradúas eh! el próximo ojalá tengas más entradas, así dejamos los que son cortos para la gente que vaya a comenzar.

**Comment by FedericoJurio** [comment]
El PR está listo para ser revisado
