### ISSUE TITLE
Translate `library/http.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#696]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/http.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/http.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 193
- Untranslated: 193

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Victoriapm** [comment]
Hola, 

Puedo tomar este?

Saludos!

**Comment by cmaureir** [comment]
Listo @Victoriapm, éxito con la traducción! y recuerda que cualquier pregunta estamos en telegram.
