### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by Jboni7** [python/python-docs-es#727]
Hola a todos me llamo Joseph y vivo en Ecuador los últimos 30 meses he estado puliendo mis habilidades en ingles lo que me ha permitido obtener un certificado b2 en Ingles y me gustaría aportar a este proyecto.
El problema es que he revisado los repositorios y todos están traducidos
Si me podrían decir con cual comenzar estaría gustoso de ayudarles.

**Comment by cmaureir** [comment]
Hola @Jboni7 te recomiendo que le eches un vistazo a la guía y si quieres contactarnos, te unas al canal de Telegram. Siempre tenemos cosas que hacer! https://python-docs-es.readthedocs.io/es/3.8/CONTRIBUTING.html
