### ISSUE TITLE
Párrafos marcados como fuzzy en tkinter

### ISSUE THREAD

**Issue by aroquega** [python/python-docs-es#738]
Existen párrafos marcados como fuzzy en la [traducción de tkinter](https://docs.python.org/es/3/library/tkinter.html), por lo que existen párrafos sin traducir a pesar de @cmaureir hizo una revisión meticulosa.
Tkinter es una librería muy conocida e importante por lo que creo que es importante que su página en la documentación no debe tener párrafos marcados en fuzzy. 

También el título es "Interface de Python ..." cuando estoy más que seguro que debería ser "Interfaz de Python..." porque el traductor en otras secciones tradujo "Interface" como "Interfaz".

Nota: la traducción de tkinter se hizo antes de que se haga conocido por el chat de telegram que las secciones marcadas como fuzzy no se traducen.

**Comment by hristoroque** [comment]
¿Puedo hacer un PR y desmarcar los fuzzy y de paso darle una segunda revisada al documento?

**Comment by cacrespo** [comment]
Hola @hristoroque, sería estupendo si puedes revisarlo y desmarcar todos los fuzzy. Dale para adelante!!

**Comment by clacri** [comment]
hola @hristoroque es este el PR sobre el que versaba esta issue? https://github.com/python/python-docs-es/pull/737

**Comment by hristoroque** [comment]
No no, aún ni siquiera hice un PR de lo de tkinter. 

tkinter.tix es una extensión descontinuada de tkinter, ahora voy a cerrar el issue de tkinter.tix cuando terminé esa traducción 👍
