### ISSUE TITLE
Error al ejecutar make build

### ISSUE THREAD

**Issue by eamanu** [python/python-docs-es#759]
Hola!

Cuanod ejecuto el comando `make build` obtento este error y se queda ahí:

![ - 214](https://user-images.githubusercontent.com/7605307/93464222-36cbf680-f8bf-11ea-95cf-556fc073dfa3.png)

**Comment by cmaureir** [comment]
Extraño, podrías compartir todo el log para poder ver si hay algo en pasos anteriores que ocasione el problema?

**Comment by mondeja** [comment]
Es porque no has activado el entorno virtual antes de ejecutar `make build`. Esto es un fallo de diseño en el `Makefile`: cuando ejecuta `PYTHONWARNINGS=ignore::FutureWarning $(VENV)/bin/sphinx-build` está ejecutando el binario `sphinx-build` que existe dentro del entorno virtual pero no comprueba antes si se encuentra activado. Subo un pull request para solucionarlo en un momento.

**Comment by humitos** [comment]
@mondeja el error que se muestra en el screenshot no parece estar relacionado con la activación del entorno virtual. Sphinx se está ejecutando correctamente desde el entorno virtual, pero falla por un problema de encoding.

**Comment by mondeja** [comment]
@humitos ¿Y por qué falla sólo si no está activado previamente el entorno?

**Comment by cmaureir** [comment]
Pues yo creo que activar el entorno como requerimiento para que funcione `make build` no es mucho pedir, mejor cerramos esto y si alguien lo considera muy importante, lo podemos reabrir
