### ISSUE TITLE
Translate 'reference/toplevel_components.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#773]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/reference/toplevel_components.html once translated.
Meanwhile, the English version is shown.

Current stats for `reference/toplevel_components.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 18
* Untranslated: 18

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by willian593** [comment]
saludos, m podria dar esta issues

**Comment by cmaureir** [comment]
Cuando hagamos merge de #1081 te recomiendo trabajar en una segunda issue, ya que hay un par de detalles aún que resolver. Te la dejo asignada, pero como ambas son "good first issue" quizás podrías buscar una con más entradas para dejar estas a la gente que comienza.
