### ISSUE TITLE
Translate 'distutils/packageindex.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#777]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/distutils/packageindex.html once translated.
Meanwhile, the English version is shown.

Current stats for `distutils/packageindex.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 3
* Untranslated: 3

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by wgarcia1309** [comment]
Hola, me gustaria trabajar en esta traduccion 😄

**Comment by cmaureir** [comment]
Genial @wgarcia1309 ! Mucho éxito y cualquier cosa nos puedes encontrar en el Discord de HacktoberfestES o en nuestro grupo de telegram
