### ISSUE TITLE
Translate 'distutils/commandref.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#778]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/distutils/commandref.html once translated.
Meanwhile, the English version is shown.

Current stats for `distutils/commandref.po`:

* Fuzzy: 0
* Percent translated: 17.2%
* Entries: 5 / 29
* Untranslated: 24

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by josephLSalgado** [comment]
Hola @cmaureir, soy yo de nuevo :). Quisiera trabajar en este issue, si se puede claro.

**Comment by cmaureir** [comment]
Genial, mucho éxito con la traducción ;) y ya con este te graduas de las "good first issues", de seguro el siguiente tendrá más entradas :tada: :muscle:
