### ISSUE TITLE
Translate 'library/ipc.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#786]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/ipc.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/ipc.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 4
* Untranslated: 4

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by h3ct0rjs** [comment]
Hi @cmaureir  Would you assign this issue to me, it will be good to learn the world flow. Also if you could share with me the docs about how to run the unit test locally. 

Sincerely, 
H

**Comment by cmaureir** [comment]
Gracias @h3ct0rjs, como ya vi, tienes otros Pull-request, recuerda por favor, volver a las rama principal, 3.8 antes de crear una nueva rama de traducción relacionada a este archivo.
La información para construir la documentación está acá: https://python-docs-es.readthedocs.io/es/3.8/faq.html#como-puedo-hacer-un-build-local-de-la-documentacion

Cualquier cosa, estamos en el grupo de telegram.

**Comment by h3ct0rjs** [comment]
Gracias @cmaureir . Esperando para iniciar este 😄

**Comment by cmaureir** [comment]
te podemos ayudar con algo @h3ct0rjs ?

**Comment by AdolfoVillalobos** [comment]
Hola a todos. Como van con esto? Me encantaría contribuir con este issue, en caso de que aun este inconcluso. Encuentro genial el proyecto, y creo seria una buena oportunidad para familiarizarme con el flujo de trabajo.

Saludos!

**Comment by cacrespo** [comment]
@AdolfoVillalobos genial!!! Actualmente estamos bastante atrasados con las revisiones. Sería estupendo si pudieras colaborar en esa tarea. Si puedes, súmate al grupo en Telegram y lo vamos conversando.

**Comment by AdolfoVillalobos** [comment]
@cacrespo Excelente, me acabo de incorporar al grupo. Lo conversamos por esa vía!

Saludos.
