### ISSUE TITLE
Translate 'library/concurrent.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#787]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/concurrent.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/concurrent.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 3
* Untranslated: 3

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by migrmrz** [comment]
Hola, ¿podría colaborar con este issue? Veo que solo es una sección corta (concurrent.futures.as_completed(fs, timeout=None)) la que falta de traducir.

**Comment by cmaureir** [comment]
Este si que sí @migrmrz :dancers:  mucho éxito!
