### ISSUE TITLE
Translate 'library/concurrency.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#788]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/concurrency.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/concurrency.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 3
* Untranslated: 3

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by lucasmiranda42** [comment]
Hi! Can I work on this? It'd be my first contribution indeed :) Thanks!

**Comment by cmaureir** [comment]
Gracias @lucasmiranda42 :tada:, recuerda que de todas formas estaremos este sábado con el sprint de la PyConAr, en caso que tengas dudas, si no, nos puedes contactar por telegram.

**Comment by lucasmiranda42** [comment]
Genial! Voy chusmeando y el sábado me sumo al sprint entonces :) Gracias!

**Comment by aroquega** [comment]
El #1145 cerró este issue. @cmaureir, no se cerró automáticamente.
