### ISSUE TITLE
Translate 'library/quopri.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#792]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/quopri.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/quopri.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 9
* Untranslated: 9

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by yeyeto2788** [comment]
Buenas @cmaureir, mientras espero que el PR sea aprobado y dado que hacktoberfest ha acabado es posible que pueda trabajar en este issue y otros para ir bajando la lista de issues.

**Comment by cmaureir** [comment]
Claro @yeyeto2788, pero igual ahora dentro de poco tenemos un nuevo evento, donde esperamos tener gente nueva participando ;) así que te dejo este último de los cortitos.
