### ISSUE TITLE
Translate 'library/python.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#793]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/python.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/python.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 2
* Untranslated: 2

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by yeyeto2788** [comment]
Volunteer here 🐍

**Comment by cmaureir** [comment]
Since you already have two good first issue, maybe you could try to find another without that label, so we leave the short ones for new people ;)

**Comment by yeyeto2788** [comment]
No problem. I'll another issue.

**Comment by endikagil** [comment]
I would like to try helping on this

**Comment by cmaureir** [comment]
Gracias @endikagil :+1:
