### ISSUE TITLE
Translate 'library/asyncio-exceptions.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#804]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/asyncio-exceptions.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/asyncio-exceptions.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 19
* Untranslated: 19

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by andipandiber** [comment]
Hola.. Te puedo Ayudar con este de aqui

**Comment by cmaureir** [comment]
Vale @andipandiber y con esta ya te graduas ;) y quizás para la próxima puedes elegir un archivo con más entradas aún :tada:
