### ISSUE TITLE
Translate 'library/email.encoders.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#808]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/email.encoders.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/email.encoders.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 15
* Untranslated: 15

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by willian593** [comment]
Saludos m podría dar esta issues, se lo agradezco de antemano

**Comment by cmaureir** [comment]
Como ya tienes un PR abierto y una segunda asignada, siendo ambas "good first issue" quizás podrías buscar una con más entradas para dejar estas a la gente que comienza.

**Comment by popiula** [comment]
Hola. Me gustaría colaborar aquí. ¿Puedo empezar con esta issue? Gracias!

**Comment by cmaureir** [comment]
Muchas gracias @popiula éxito con la traducción!

**Comment by popiula** [comment]
Gracias!

**Comment by popiula** [comment]
queda algo pendiente aqui?

**Comment by cmaureir** [comment]
había un problema con el CI, ahora lo miro cuando termine de ejecutar de nuevo.

**Comment by popiula** [comment]
Gracias
