### ISSUE TITLE
Translate 'library/reprlib.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#809]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/reprlib.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/reprlib.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 21
* Untranslated: 21

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by jaumemy** [comment]
Hola, para mi primera contribución, me gustaría poder traducir este módulo que se ve interesante.
Podrían asignarmelo? gracias!

**Comment by cmaureir** [comment]
Mucho éxito con la traducción! @jaumemy, recuerda leer la guía de contribución y nos puedes encontrar en telegram!

**Comment by jaumemy** [comment]
Gracias Cristián! Ya me pongo a ello
