### ISSUE TITLE
Translate 'library/posix.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#810]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/posix.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/posix.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 14
* Untranslated: 14

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by h3ct0rjs** [comment]
Hi @cmaureir  Hope you're doing well, I'd like to solve this issue, please assign this to me. 

Thanks in advanced, 
H
Colombia

**Comment by cmaureir** [comment]
Gracias por el interés! éxito con la traducción :tada:

**Comment by h3ct0rjs** [comment]
@cmaureir I'm still working on this, it has been a long week. I Hope to finish this on sunday

**Comment by h3ct0rjs** [comment]
@cmaureir  #1106 help me with the proper review 😄

**Comment by cmaureir** [comment]
@h3ct0rjs podrías volver a crear un PR con solo tus cambios al archivo? o prefieres dejar este issue para otra persona?

**Comment by h3ct0rjs** [comment]
@cmaureir Hola, preferiria dejar estos cambios para alguien más.

**Comment by cmaureir** [comment]
Queda disponible este issue.

**Comment by yeyeto2788** [comment]
@cmaureir puedo encargarme de este issue?

**Comment by cmaureir** [comment]
@yeyeto2788 vi que ya hiciste la traducción, pues ya tienes bastante experiencia. Intentemos dejar los "good first issue" para gente que está comenzando, quizás nos puedas dar una mano con archivos más largos ;)

**Comment by yeyeto2788** [comment]
@cmaureir Got it! Gracias igualmente.
