### ISSUE TITLE
Translate 'library/sndhdr.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#811]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/sndhdr.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/sndhdr.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 6
* Untranslated: 6

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by MelissaEscobar** [comment]
Hi! I want to contribute translating. Please assign me this issue :D

**Comment by cmaureir** [comment]
Te asigné el otro @MelissaEscobar, cuando lo termines y te acostumbres al flujo de trabajo, te asignamos este ;)

**Comment by MelissaEscobar** [comment]
¡Súper!. Muchas gracias.

**Comment by enrique-zarate** [comment]
Puedo ayudar con este issue?

**Comment by cmaureir** [comment]
Gracias @enrique-zarate mucho éxito!
