### ISSUE TITLE
Translate 'library/modulefinder.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#812]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/modulefinder.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/modulefinder.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 13
* Untranslated: 13

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by willian593** [comment]
Saludos cordiales. 
Me gustaría ayudar en esta issues, me la podrían asignar, gracias de antemano.

**Comment by cmaureir** [comment]
Ya tienes dos "good first issues" @willian593, si te faltan para el Hacktoberfest, me parece bien, pero si no, sería genial que nos pudieras ayudar con archivos con más entradas.

**Comment by willian593** [comment]
Ok, entonces quisiera ayudar con esta issues, Translate 'whatsnew/3.2.po' #1030

**Comment by dvidsilva** [comment]
@cmaureir me gustaria colaborar con esta

**Comment by cmaureir** [comment]
hecho, éxito, y con esta ya te graduas de los "good first issues" ;)
