### ISSUE TITLE
Translate 'library/tkinter.scrolledtext.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#815]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/tkinter.scrolledtext.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/tkinter.scrolledtext.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 7
* Untranslated: 7

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by willian593** [comment]
Saludos, me podria dar esta issues

**Comment by cmaureir** [comment]
Como ya tienes un PR abierto y una segunda asignada, siendo ambas "good first issue" quizás podrías buscar una con más entradas para dejar estas a la gente que comienza.

**Comment by 0-Arngerdur-1** [comment]
Hola que tal, me gustaría ayudar con este issue.

**Comment by cmaureir** [comment]
éxito con la traducción @0-Arngerdur-1
