### ISSUE TITLE
Mention how to configure `git diff` properly

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#82]
It's possible to create a `git diff` command that will show only relevant parts.

I deleted it at https://github.com/PyCampES/python-docs-es/pull/80/files#diff-88b99bb28683bd5b7e3a204826ead112L211-L233, but we should re-add it in the "Resources page" #51, once we have it.

**Comment by humitos** [comment]
* https://formulae.brew.sh/formula/podiff
* https://aur.archlinux.org/packages/podiff

**Comment by eamanu** [comment]
Hi,

Let here a proposal to use podiff. I can make de PR after close #51 

---

Simplificar el `git diff`
-------------------------

El comando `git dif` tiene datos que pueden llegar a ser inútiles como por ejemplo:

. code-block:: diff

    -#: ../Doc/library/signal.rst:406
    +#: ../Doc/library/signal.rst:408

Para ellos debemos instalar brew. Si no lo tienes instalado puedes seguir el instructivo de instalación Brew_.

Una vez instalado brew, hay que instalar podiff, para ellos ejectar el siguiente comando:

. code-block:: bash
    brew install pdiff

Luego abrir el archivo de configuración del respositorio local y escribir al final:

   [diff "podiff"]
   command = $(brew --prefix)/bin/podiff -D--minimal

Luego, si no existiese el archivo `.gitatributes` en la carpeta dónde se encuentran los 
archivos .po con los que se van a trabajar, crealo, y luego,  agregar la siguiente línea 

    *.po diff=podiff

.. _Brew: https://docs.brew.sh/Installation

**Comment by clacri** [comment]
@eamanu vi que ya agregaste la pagina de recursos, está esto incluido? se puede cerrar la issue?

**Comment by cmaureir** [comment]
Pues yo creo que si, voy a cerrarlo y si sienten que se puede mejorar o continuar la discusión, lo podemos reabrir :)
