### ISSUE TITLE
Translate 'library/custominterp.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#821]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/custominterp.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/custominterp.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 3
* Untranslated: 3

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by MelissaEscobar** [comment]
Hi! I want to contribute translating. Please assign me this issue :D

**Comment by cmaureir** [comment]
Te asigné el otro @MelissaEscobar, cuando lo termines y te acostumbres al flujo de trabajo, te asignamos este ;)

**Comment by m3lissaeg** [comment]
¡Holaa! Por favor no me olvides jeje. Ya el anterior quedó aprobado 😺

**Comment by cmaureir** [comment]
Ningún problema, además con esta ya te graduas de las "good first issue", a ver si el siguiente es uno con más entradas :tada:
