### ISSUE TITLE
Translate 'library/py_compile.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#822]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/py_compile.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/py_compile.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 25
* Untranslated: 25

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by cmaureir** [comment]
Dale @iam-agf :tada:

**Comment by iam-agf** [comment]
Recordatorio de que se debe cerrar esta issue.

**Comment by cmaureir** [comment]
Me parece extraño que no se cerrase solo, si le pusimos Closes #822
