### ISSUE TITLE
Translate 'library/copyreg.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#824]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/copyreg.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/copyreg.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 9
* Untranslated: 9

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by MelissaEscobar** [comment]
Hi! I want to contribute translating. Please assign me this issue :D

**Comment by cmaureir** [comment]
Te asigné el otro @MelissaEscobar, cuando lo termines y  te acostumbres al flujo de trabajo, te asignamos este ;)

**Comment by Xaraxx** [comment]
Hola! me gustaría traducir esta parte me lo podrían asignar?

**Comment by cmaureir** [comment]
Mejor de a uno @Xaraxx, cuando acabes el otro te asigno este ;)

**Comment by Xaraxx** [comment]
Muchas gracias!! es que no sabía cual escoger! :+1:  muchas gracias @cmaureir!!

**Comment by Xaraxx** [comment]
Hola @cmaureir  ya terminé he hice pull request de la anterior me podrias asignar esta?

**Comment by cmaureir** [comment]
OK! ya con este te graduas de los "good first issues" ;) a ver si nos das una mano con los pendientes con más entradas luego. Mucho éxito.

**Comment by Xaraxx** [comment]
Eso sería genial @cmaureir la verdad es que me encanta esto de contribuir a la comunidad! :+1: estoy muy felíz
