### ISSUE TITLE
Translate 'library/email.generator.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#826]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/email.generator.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/email.generator.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 41
* Untranslated: 41

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by JuliKM** [comment]
Me interesa traducir este issue

**Comment by clacri** [comment]
Hola @JuliKM como ya has sigo asignado una issue de las de good first issue (importlib.metadata.po), sería mejor si ahora escogieras una un poco más grande, de forma que estas quedan para los primerizos en la traducción.

**Comment by cmaureir** [comment]
Debido a la alta demanda, le he quitado el 'good first issue' a este issue por tener mas de 30 entradas. Si luego de que acabes con lo que estás ahora @JuliKM y te sigue interesando este archivo, nos puedes avisar!

**Comment by JuliKM** [comment]
Hola que tal! Si, me sigue interesando! Bueno, en el otro vi las correcciones e hice commit, la verdad que no se si con eso ha terminado o habra que hacer otra revision, soy first-timer :).
Pero bueno, cuando este el otro, puedo tomar este.
