### ISSUE TITLE
Translate 'library/urllib.robotparser.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#827]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/urllib.robotparser.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/urllib.robotparser.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 14
* Untranslated: 14

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by 0-Arngerdur-1** [comment]
Hola, que tal ¿puedo traducir este issue?

**Comment by cmaureir** [comment]
gracias @0-Arngerdur-1 :tada:

**Comment by cmaureir** [comment]
como vas @0-Arngerdur-1 ?

**Comment by 0-Arngerdur-1** [comment]
Hola, le pare por un tiempo, pero ya regrese de nuevo

**Comment by cmaureir** [comment]
Genial, @0-Arngerdur-1  no es tan largo el archivo, así que de seguro lo acabas pronto :muscle: :tada:

**Comment by 0-Arngerdur-1** [comment]
Listo :+1:  :smile:
