### ISSUE TITLE
Translate 'library/binary.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#829]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/binary.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/binary.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 4
* Untranslated: 4

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by ricrogz** [comment]
¿Podría encargarme también de este Issue? El que se me asignó ayer ya está como PR, a la espera de ser revisado.

**Comment by cmaureir** [comment]
Vale @ricrogz, y con este te graduas de los "good first issue" a ver si nos puedes dar una mano con las traducciones pendientes que tienen más entradas :+1:
