### ISSUE TITLE
Decide and document in Memory Translation these terms

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#83]
I deleted them from the README in https://github.com/PyCampES/python-docs-es/pull/80/files#diff-88b99bb28683bd5b7e3a204826ead112L171-L208

We should discuss and decide what words we are going to use in Spanish and document these decisions in the Memory Translation.

**Comment by hectorcanto** [comment]
In the case of titles, I added an entry and  a reference to "Diccionario Panhispanico de Dudas" in PR #143  following the discussion in the PR #58. If you are satisfied, please assign this to me and close it, or let's continue the discussion.

**Comment by humitos** [comment]
I like what you described in your PR! :+1: 

Feel free to close after merging that.

**Comment by hectorcanto** [comment]
#143 mezclada, sección de estilo en memoria iniciada.
Continuemosla

**Comment by cmaureir** [comment]
Cerrando porque la memoria ya está en funcionamiento hace tiempo. Si hay que mejorarla o agregar un flujo de trabajo distinto, abrimos esto sin problemas.
