### ISSUE TITLE
Translate 'library/unicodedata.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#842]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/unicodedata.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/unicodedata.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 29
* Untranslated: 29

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by fjsevilla-dev** [comment]
Me gustaría traducir este, si no hay alguno mas largo... Es el que he encontrado con más entradas, las issues se volatilizan como la antimateria... ;)
