### ISSUE TITLE
Translate 'library/undoc.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#843]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/undoc.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/undoc.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 9
* Untranslated: 9

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by zejiran** [comment]
Hey, I would like to translate this.

**Comment by David-Lor** [comment]
@cmaureir Me podrían asignar esta traducción?

**Comment by cmaureir** [comment]
Claro @David-Lor ! Mucho éxito con la traducción :)
Si estás participando en #HacktoberfestES nos puedes encontrar en el canal de Discord y si no, tenemos un canal de Telegram donde te puedes unir para aclarar dudas.
éxito con la traducción!
