### ISSUE TITLE
Translate 'library/modules.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#846]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/modules.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/modules.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 3
* Untranslated: 3

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by sofiacarballo** [comment]
Hi! Could I work on this issue?

**Comment by cmaureir** [comment]
Debería salir rápido este ;)
Recuerda volver a la rama principal, 3.8, antes de crear una nueva rama para esta traducción. éxito!
