### ISSUE TITLE
Translate 'library/email.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#847]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/email.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/email.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 27
* Untranslated: 27

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by willian593** [comment]
saludos cordiales.
Quisiera colaborar en esta traducción, me podría dar este issues, gracias de antemano

**Comment by cmaureir** [comment]
listo! mucho éxito con la traducción :tada:
