### ISSUE TITLE
Translate 'library/netdata.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#851]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/netdata.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/netdata.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 2
* Untranslated: 2

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by fenriquegimenez** [comment]
Me asignas esta issue @cmaureir? Es un archivo pequeño pero lleva tiempo sin que nadie le haya prestado atención

**Comment by cmaureir** [comment]
Bueno tenemos 2 paginas llenas de "good first issue" https://github.com/python/python-docs-es/labels/good%20first%20issue
Espero nos puedas ayudar con otros archivos grandes pendientes, ya que tienes la experiencia suficiente.
Te lo asigno igual ;)
