### ISSUE TITLE
Translate 'library/windows.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#853]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/windows.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/windows.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 2
* Untranslated: 2

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by rishabhmishra25** [comment]
I would like to contribute and translate it. Thanks in advance!

**Comment by cmaureir** [comment]
Mejor puedes terminar el otro que te he asignado @rishabhmishra25, y así miramos cuando acabes ese, te asignamos uno nuevo ;)

**Comment by rishabhmishra25** [comment]
> Mejor puedes terminar el otro que te he asignado @rishabhmishra25, y así miramos cuando acabes ese, te asignamos uno nuevo ;)

Absolutamente! Haré uno ahora, puedes asignarme otros para * hacktober Fest *

**Comment by clacri** [comment]
Hola @rishabhmishra25 ! hemos decidido que durante el hacktoberfest vamos a asignar una issue por persona, y solo cuando la PR asociada esté ya hecha entonces asignaremos otro.

**Comment by lis17** [comment]
Hola,
Estoy aprendiendo y me gustaría hacer mi primera contribución con esta traducción. Es mi primera primerísima contribución y espero poder completarla.

**Comment by Xaraxx** [comment]
Hola me gustaría contribuir traduciendo esta parte!

**Comment by cmaureir** [comment]
Gracias @Xaraxx, mucho éxito con la traducción. Recuerda mirar la guía de contribución y nos puedes encontrar en telegram!

**Comment by Xaraxx** [comment]
Muchas gracias! :+1:
