### ISSUE TITLE
Translate 'library/tty.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#855]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/tty.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/tty.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 9
* Untranslated: 9

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by rishabhmishra25** [comment]
I would like to contribute and translate it. Thanks in advance!

**Comment by cmaureir** [comment]
Mejor puedes terminar el otro que te he asignado @rishabhmishra25, y así miramos cuando acabes ese, te asignamos uno nuevo ;)

**Comment by rishabhmishra25** [comment]
> Mejor puedes terminar el otro que te he asignado @rishabhmishra25, y así miramos cuando acabes ese, te asignamos uno nuevo ;)

Absolutamente! Haré uno ahora, puedes asignarme otros para  _hacktober Fest_

**Comment by CosmicTiger** [comment]
Hola estoy interesado en trabajar esta issue. ¿Podrías asignarmelo?

**Comment by cmaureir** [comment]
Gracias @CosmicTiger, éxito con la traducción!

**Comment by cmaureir** [comment]
Como vas @CosmicTiger ?

**Comment by juansemarquez** [comment]
Es un archivo breve, y lleva más de 3 meses sin actividad... Si no se oponen, me gustaría contribuir aquí, ya que hubo varios cambios en CI desde mi última intervención, y me sirve para ponerme a tono antes de abordar un archivo más extenso. ¡Gracias!

**Comment by cacrespo** [comment]
Hola @juansemarquez! Genial que lo quieras tomar. Dale para adelante y cualquier inconveniente pregunta sin problemas. 🚀

**Comment by juansemarquez** [comment]
Perfecto. ¡Gracias!
