### ISSUE TITLE
Translate 'library/keyword.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#856]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/keyword.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/keyword.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 5
* Untranslated: 5

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by rishabhmishra25** [comment]
I would like to contribute and translate it. Thanks in advance!

**Comment by cmaureir** [comment]
Mejor puedes terminar el otro que te he asignado @rishabhmishra25, y así miramos cuando acabes ese, te asignamos uno nuevo ;)

**Comment by rishabhmishra25** [comment]
> Mejor puedes terminar el otro que te he asignado @rishabhmishra25, y así miramos cuando acabes ese, te asignamos uno nuevo ;)

Absolutamente! Haré uno ahora, puedes asignarme otros para  _hacktober Fest_

**Comment by MaikaRG** [comment]
Can I do this issue? :)

**Comment by fenriquegimenez** [comment]
Me asignas esta issue mientras se revisa la otra PR @cmaureir?

**Comment by cmaureir** [comment]
éxito @fenriquegimenez ;)
