### ISSUE TITLE
Translate 'library/html.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#859]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/html.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/html.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 8
* Untranslated: 8

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Yenniferh** [comment]
Hola, ¿puedo ayudar a traducir este archivo?

**Comment by clacri** [comment]
Hola @Yenniferh te la asigno ahora.
esta sería tu primera contribución verdad? Si necesitas cualquier cosa o tienes dudas no dudes en contactarnos por aqui o por el telegram.
Estás participando en el evento de HacktoberfestES?

**Comment by Yenniferh** [comment]
Sí, @clacri sería mi primera contribución a un proyecto open source. Tambien, es la primera vez que participo en Hacktoberfest. Por lo que estoy muy emocionada 😄

**Comment by clacri** [comment]
Estupendo :) bienvenida!!!

**Comment by Yenniferh** [comment]
Muchas gracias @clacri 😄 Sinceramente no pensé que se podía colaborar en proyectos open source haciendo traducciones. Llevo varios meses siendo traductora voluntaria de los cursos de Coursera y pues nada, aquí estamos para aportar un granito de arena.
