### ISSUE TITLE
Translate 'library/token.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#864]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/token.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/token.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 65
* Untranslated: 65

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by iam-agf** [comment]
¿Puedo realizar esta issue?

**Comment by cmaureir** [comment]
Hecho! éxito con la traducción! :tada:

**Comment by iam-agf** [comment]
No puedo utilizar powrap pero ya terminé la traducción. ¿Qué puedo hacer para resolver ese problema?

**Comment by cmaureir** [comment]
Sube el Pull-request de todas maneras, yo puedo pasarle powrap cuando todos los otros problemas estén resueltos.

**Comment by iam-agf** [comment]
Vale, voy.

**Comment by iam-agf** [comment]
Listo. Para evitar conflictos volví a hacer fork al repositorio para que sólo sea la rama con su respectiva edición.

**Comment by cmaureir** [comment]
Igual el fork solo hazlo una sola vez, puedes crear cuantas ramas quieras y hacer distintos Pull requests, del mismo fork.
