### ISSUE TITLE
Translate 'library/stringprep.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#865]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/stringprep.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/stringprep.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 25
* Untranslated: 25

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Xhiel23** [comment]
Hola! Me gustaría trabajar en este issue :)

**Comment by cmaureir** [comment]
Gracias por el interés! Mucho éxito con la traducción :)
No olvides mirar la guía de contribución o unirte a los canales de comunicación en caso de preguntas.

**Comment by Xhiel23** [comment]
De acuerdo! Muchas gracias ^^

> Gracias por el interés! Mucho éxito con la traducción :)
> No olvides mirar la guía de contribución o unirte a los canales de comunicación en caso de preguntas.
