### ISSUE TITLE
Translate 'library/_dummy_thread.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#866]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/_dummy_thread.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/_dummy_thread.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 5
* Untranslated: 5

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by josephLSalgado** [comment]
Hola. Me gustaría trabajar en este issue

**Comment by cmaureir** [comment]
Gracias @josephLSalgado ! recuerda mirar la guía de contribución y si tienes preguntas, te puedes unir al grupo de telegram que tenemos.
