### ISSUE TITLE
Translate 'library/pickletools.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#870]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/pickletools.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/pickletools.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 17
* Untranslated: 17

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Jighdan** [comment]
Puedo tomar dos al mismo tiempo? Son bien cortitos hehe

**Comment by cmaureir** [comment]
Dale @Jighdan no hay problema, no lo recomendabamos pero de seguro los puedes sacar rápido :)
