### ISSUE TITLE
Translate 'library/misc.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#871]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/misc.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/misc.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 2
* Untranslated: 2

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by yeyeto2788** [comment]
Can I get this one assigned? Seems like it can be done pretty quick 😛

**Comment by cmaureir** [comment]
Hola @yeyeto2788, claro, sin problema ;) mucho éxito con la traducción! :tada:

**Comment by yeyeto2788** [comment]
Gracias! PR abierto ya, esperando a la revisión. 😛
