### ISSUE TITLE
Translate 'library/xml.sax.handler.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#873]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/xml.sax.handler.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/xml.sax.handler.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 92
* Untranslated: 92

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by gomezgleonardob** [comment]
Please assign me

**Comment by cmaureir** [comment]
gracias @gomezgleonardob , éxito con la traducción :tada: recuerda ir mirando la otra que ya tienes asignada, para que podamos hacer merge pronto, una vez que tengas la revisión

**Comment by cmaureir** [comment]
dejando libre este issue

**Comment by gomezgleonardob** [comment]
Puedo retomar este :)

**Comment by cmaureir** [comment]
dale @gomezgleonardob, éxito! :tada:
