### ISSUE TITLE
Translate 'library/distribution.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#877]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/distribution.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/distribution.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 2
* Untranslated: 2

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by avallbona** [comment]
Hola, ¿puedo encargarme de esta issue?

**Comment by cmaureir** [comment]
Estamos intentando dejar las issues con 'good first issues' para la gente que recién comienza, como ya hiciste un archivo pequeño, sería genial si pudieras mirar uno que no tenga ese label, te parece?

**Comment by avallbona** [comment]
Vale, genial. 👍

**Comment by lgfunderburk** [comment]
Please assign this to me.

**Comment by cmaureir** [comment]
Gracias @lgfunderburk mucho éxito con la traducción!

**Comment by lgfunderburk** [comment]
PR aqui https://github.com/python/python-docs-es/pull/1113
