### ISSUE TITLE
Translate 'library/development.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#878]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/development.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/development.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 4
* Untranslated: 4

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by oropher** [comment]
I'd like to work in this translation

**Comment by clacri** [comment]
Hola @oropher, te la asigno, veo que es tu primera contribución al proyecto. Si necesitas cualquier ayuda consultanos por aqui o por telegram. Asimismo, queria consultarte si estás participando en el evento de HacktoberfestES.

**Comment by oropher** [comment]
Gracias, si es la primera contribucion, Sie estoy participando, pero mas que nada queria contribuir en algo desde hace mucho y fue una buena oportinudad para comenzar.
