### ISSUE TITLE
Translate 'library/ossaudiodev.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#880]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/ossaudiodev.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/ossaudiodev.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 97
* Untranslated: 97

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by zejiran** [comment]
@cmaureir, ¿te parece bien si me encargo de este issue?

**Comment by cmaureir** [comment]
Gracias @zejiran este si que si :) al menos cercano a 100 entradas está bien para gente con experiencia ;)
