### ISSUE TITLE
Translate 'library/html.entities.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#881]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/html.entities.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/html.entities.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 9
* Untranslated: 9

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by tanrax** [comment]
¿Es posible trabajar en esta traducción?

**Comment by cmaureir** [comment]
Te asigné otra @tanrax, estamos dejando las que tienen el label 'good first issue' como "primera issue" para la gente que se nos use, si encuentras otra issue que no tenga ese label, te la podemos asignar sin problemas ;)

**Comment by tanrax** [comment]
@cmaureir de acuerdo busco otra. Gracias por el esfuerzo!

**Comment by avallbona** [comment]
Hola, me gustaría trabajar en esta traducción, ¿es posible?

**Comment by cmaureir** [comment]
Claro @avallbona :tada: mucho éxito
