### ISSUE TITLE
Translate 'library/runpy.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#882]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/runpy.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/runpy.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 36
* Untranslated: 36

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by cacrespo** [comment]
Lo tomo!

**Comment by cmaureir** [comment]
@cacrespo como vez el label "good first issue" es para gente que esté comenzando y no sepa mucho de todo, como tu ya eres de los veteranos, te parece si miras otro sin sin ese label? así dejamos estos "cortos" para personas nuevas

**Comment by cacrespo** [comment]
Dale. Perfecto!!

**Comment by andipandiber** [comment]
Talvez pudiera Trabajar en este Issue..

**Comment by cmaureir** [comment]
Gracias @andipandiber :tada: éxito con la traducción!
