### ISSUE TITLE
Translate 'library/othergui.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#883]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/othergui.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/othergui.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 13
* Untranslated: 13

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by yeyeto2788** [comment]
Hey guys! Do mind if I take this one over?

**Comment by humitos** [comment]
@yeyeto2788 buenísimo! Metele nomás y muchas gracias! Te lo asigno :)

**Comment by yeyeto2788** [comment]
Eso si que fue rapido, gracias!
