### ISSUE TITLE
Translate 'library/faulthandler.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#886]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/faulthandler.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/faulthandler.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 35
* Untranslated: 35

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by rosggu** [comment]
Can I work in this issue? I'm Spanish native speaker :-)

**Comment by cmaureir** [comment]
Claro! éxito con la traducción @rosggu :tada:

**Comment by cmaureir** [comment]
Te podemos ayudar con algo @rosggu ? siempre puedes ir subiendo tus cambios parciales al archivo ;)

**Comment by cmaureir** [comment]
dejandro libre este issue

**Comment by Kajachuan** [comment]
Buenas. Me gustaría trabajar en este issue.

**Comment by cmaureir** [comment]
Claro @Kajachuan, mucho éxito!
