### ISSUE TITLE
Translate 'library/email.charset.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#887]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/email.charset.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/email.charset.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 44
* Untranslated: 44

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Alvaruz** [comment]
Buenas.

Me asignan este por favor.

**Comment by cmaureir** [comment]
Gracias por tu interés @Alvaruz ! Recuerda que este Domingo comienza el evento HacktoberfestES donde estamos reuniendo desarrolladores de habla hispana para tener todo un mes de colaboración y más :+1:
Si aún no consigues tu entrada, lo puedes hacer en https://hacktoberfest.es.python.org/

Respecto al Hacktoberfest, recuerda que los PRs cuentan desde el 1 de Octubre.

**Comment by Alvaruz** [comment]
si, estoy al tanto, gracias!
