### ISSUE TITLE
Translate 'library/codeop.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#888]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/codeop.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/codeop.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 14
* Untranslated: 14

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by ktowen** [comment]
Hello, I would like to work in this issue.

**Comment by cmaureir** [comment]
Te asigné otra, y así dejamos esta para alguien que recién comience :)

**Comment by paaaron** [comment]
Hola... Podria empezar con esta?

**Comment by cmaureir** [comment]
Claro @paaaron :tada: mucho éxito!

**Comment by paaaron** [comment]
Hola @cmaureir... Actualmente Travis me esta sugiriendo ajustar el file. Podrias orientarme?
