### ISSUE TITLE
Translate `using/index.po`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#89]
This file is at 0% translated. It needs to reach 100% translated.

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/es/3.7/CONTRIBUTING.html)

**Comment by dvidsilva** [comment]
I can take it! @humitos

**Comment by humitos** [comment]
Perfect! Go ahead! Thanks

**Comment by humitos** [comment]
Hola @dvidsilva! ¿Has podido avanzar con este archivo? ¿Necesitas alguna ayuda? Si quieres, puedes abrir una PR en Draft con el progreso que tengas hasta el momento --así te podemos dar un feedback temprano.

**Comment by dvidsilva** [comment]
Hola @humitos que pena! hemos estado embolatados con cosas por acá! esta semana la subo y si no les aviso para que alguien mas la coja. 

Gracias!

**Comment by cmaureir** [comment]
@dvidsilva te podemos ayudar en algo para poder continuar con este archivo? Si no tienes tiempo, lo podemos dejar libre para que otro continué con el.

**Comment by dvidsilva** [comment]
@cmaureir hola que pena, si liberalo para que lo coja alguien más y apenas tenga tiempo cojo otro. 

Gracias!

**Comment by mondeja** [comment]
Hola, ¿podéis asignarme este issue?

**Comment by cmaureir** [comment]
listo! gracias @mondeja
