### ISSUE TITLE
Translate 'library/hmac.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#890]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/hmac.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/hmac.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 25
* Untranslated: 25

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by mondeja** [comment]
Hola, ¿podríais asignarme este? Gracias

**Comment by cmaureir** [comment]
@mondeja como ves tenemos el label 'good first issue' porque es para alguna persona que recién comience. Te parece si miras otra con más entradas? y así dejamos esta para alguien nuevo  nuevo? Si no encuentras ninguna, aún quedan unos archivos sin traducir que puedo crear issues nuevas ;) así que me puedes avisar.

**Comment by mondeja** [comment]
Perfecto, busco otro

**Comment by Jmdelafuente** [comment]
Hola! Si se puede, me gustaría ayudar en esta traducción.

**Comment by cmaureir** [comment]
Gracias @Jmdelafuente ! mucho éxito con la traducción :)

**Comment by cmaureir** [comment]
Que tal @Jmdelafuente ? te podemos dar una mano con algo?

**Comment by Jmdelafuente** [comment]
> Que tal @Jmdelafuente ? te podemos dar una mano con algo?

La verdad que tengo dificultad para traducir algunas palabras. Ya hice push en el fork, pero si pudiera consultarle a alguien algunas dudas estaría mas que agradecido

**Comment by cmaureir** [comment]
No hay ningún Pull-request en el repositorio con tu traducción. Quizás lo hiciste en tu repositorio y no acá?
Justamente la idea de subir un PR como draft es poder hacer la discusión de las palabras que no sepas, a modo de revisión, adicionalmente, para eso tenemos el canal de telegram que señalamos en la  guía de contribución.

**Comment by cmaureir** [comment]
dejando libre este issue

**Comment by framorac** [comment]
favor asignarme este issue.

**Comment by framorac** [comment]
Favor asignarme este issue.

**Comment by cmaureir** [comment]
Hola @framorac, ya tienes dos "good first issue" mergeadas: https://github.com/python/python-docs-es/pulls?q=is%3Apr+is%3Amerged+author%3Aframorac+ te parece si dejamos este archivo para alguien que esté comenzando?
Acá puedes ver todas las issues abiertas que no tienen a nadie asignado y que no tienen ese label: https://github.com/python/python-docs-es/issues?q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22+no%3Aassignee

**Comment by framorac** [comment]
perfecto, @cmaureir tomo otro.

**Comment by Kajachuan** [comment]
Hola @cmaureir. Quería consultarte si puedo trabajar en este issue.

**Comment by cmaureir** [comment]
Claro @Kajachuan ya con este segundo good first issue te graduas :)
