### ISSUE TITLE
Translate 'library/asyncio-policy.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#891]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/asyncio-policy.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/asyncio-policy.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 65
* Untranslated: 65

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by iam-agf** [comment]
¿Puedo intentar esta issue ahora que se concluya la revisión de la #864 ?

**Comment by cmaureir** [comment]
Si @iam-agf a penas hagamos el merge de esa, te la asignamos.

**Comment by iam-agf** [comment]
Voy a empezar con esta entonces, ¿sí?

**Comment by cmaureir** [comment]
Hecho! @iam-agf :tada: :tada:

**Comment by iam-agf** [comment]
Estoy teniendo unos problemas con la traducción de este documento, no sé cómo traducir estas palabras:

- event loop policy (**sugerencia** política de evento de ciclo)
- policy API (**sugerencia**: política API, política de API, API de políticas)
- watcher (**sugerencia**: observador, watcher)
- default asyncio policy (**sugerencia**: política por defecto de asyncio)

¿Puedes darme tu recomendación de éstos?

**Comment by cmaureir** [comment]
Hola @iam-agf, justamente este tipo de discusiones las tenemos en el canal de telegram (y ahora en Octubre en discord), pues si no tenemos la palabra en https://python-docs-es.readthedocs.io/es/3.8/translation-memory.html las decidimos entre todos, para tener los puntos de vistas de distintos paises, con lo que te invito a unirte ;)

Pero en **mi opinión** las traduciría como:
* política de evento de ciclos
* política de API
* observador
* política ayncio por defecto
