### ISSUE TITLE
Translate 'library/email.mime.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#892]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/email.mime.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/email.mime.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 38
* Untranslated: 38

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by David-Lor** [comment]
¿Puedo ponerme con esta?

**Comment by cmaureir** [comment]
Hola @David-Lor ! como ya tuviste experiencia haciendo https://github.com/python/python-docs-es/pull/926 quizás podrías buscar otra issue que no tenga el label 'good first issue', y así dejamos esta para alguien que recién comience, te parece?

**Comment by David-Lor** [comment]
@cmaureir perfecto! busco otra más avanzada entonces 👍

**Comment by Ibnmardanis24** [comment]
@cmaureir Buenas! Estoy interesado en participar en esta issue como parte de mis contribuciones en el hacktoberfest. He tenido la oportunidad de mirar ejemplos de traducción dentro de este proyecto para hacerme una idea. Además vuestra guía de contribución parece bastante exhaustiva. Si os parece bien podríais asignármela y para el fin de semana intentaría tener una PR para revisión! Un saludo.

**Comment by cmaureir** [comment]
Sin problemas @Ibnmardanis24, cualquier cosa puedes encontrarnos en telegram o en discord (si te inscribiste en hacktoberfestES). éxito :tada:

**Comment by cmaureir** [comment]
Como va todo @Ibnmardanis24 ? te podemos ayudar en algo?

**Comment by Ibnmardanis24** [comment]
Perdonad si he estado pasivo esta semana, han sido unos días un poco extraños aquí en Madrid. En cualquier caso, he podido seguir vuestra guía y he comenzado la traducción con poedit. Entre hoy y mañana tendré algo útil para vosotros. Un saludo. 👍
