### ISSUE TITLE
Translate 'library/email.errors.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#896]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/email.errors.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/email.errors.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 23
* Untranslated: 23

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by rishabhmishra25** [comment]
I would like to contribute and translate it. Thanks in advance!

**Comment by cmaureir** [comment]
Gracias @rishabhmishra25, recuerda que si quieres participar en el Hacktoberfest, los PR cuentan desde el 1 de Octubre. Mucho éxito con la traducción.

**Comment by rishabhmishra25** [comment]
> Gracias @rishabhmishra25, recuerda que si quieres participar en el Hacktoberfest, los PR cuentan desde el 1 de Octubre. Mucho éxito con la traducción.

Prepararé la traducción y emitiré una _Pull request_ el 1 de octubre. Gracias!

**Comment by rishabhmishra25** [comment]
If found appropriate please assign me others as well!

**Comment by cmaureir** [comment]
@rishabhmishra25 encontré unos errores gramaticales en tu traducción que eran extraños, por curiosidad estás aprendiendo Español? o solo estás usando herramientas externas como Google Translate? Sin lugar a duda valoramos tu esfuerzo, pero necesitamos gente que tenga un conocimiento de español para al menos poder corregir esos errores de gramática. Si tienes algún otro lenguaje que manejes aparte del inglés, quizás puedes encontrar otras iniciativas de  traducción en Python, y si no, puedes comenzar una!

**Comment by rishabhmishra25** [comment]
@cmaureir Apologies for the grammatical errors, Actually I am learning Spanish hence the mistakes. I understand the kind of expertise needed and feel I should pass on this to someone more experienced in the language. Thanks for the opportunity though!

**Comment by cmaureir** [comment]
@rishabhmishra25 it's quite challenging to be honest, to jump into contributing into "translating to X language" while learning it.
However, you were quite close to finish your file, and you needed to fix the issues of the powrap and pospell commands, and that was all, I can take over your patch if you want, but we really appreciate your effort.
