### ISSUE TITLE
Translate 'library/__main__.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#897]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/__main__.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/__main__.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 4
* Untranslated: 4

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by zejiran** [comment]
Hello! Can I translate this file?

**Comment by clacri** [comment]
Hola @zejiran he visto que has comentado en varias issues. Nuestro flujo de trabajo prefiere priorizar que se asigne una issue cada vez y que cuando este se complete se asigne una nueva, así que sería mejor que nos indiques por cual prefieres comenzar.

**Comment by zejiran** [comment]
Entonces comenzaré por este, el primero de octubre por el Hacktoberfest. Usualmente cmaureir me asignaba varios en paralelo.

**Comment by cmaureir** [comment]
Ahora son otros tiempos y estamos renovados...jajaja es solamente para poder tener más control con las issues para el Hacktoberfest @zejiran ya que mucha gente se puede asignar varios y dejamos a gente que quiera comenzar sin archivos que traducir.

Adicionalmente, creo que tu ya te habías graduado de traductor :P a ver si te animas a un archivo más grande y dejamos estos con un par de entradas para la gente que recién comienza.

Si no encuentras uno largo que te apetezca puedo mirar de crear alguna otra issue importante, solo para ti ;)

**Comment by zejiran** [comment]
Perfecto, entonces tomaré otro issue.

**Comment by zayle** [comment]
¿Puedo hacer esta issue? Soy hispanohablante (México).

**Comment by clacri** [comment]
Si, te la acabo de asignar :) bienvenido!

**Comment by cmaureir** [comment]
Como vas @zayle ? te podemos ayudar en algo? Si tienes problemas con git o las otras herramientas, avisanos

**Comment by cmaureir** [comment]
dejando este issue libre

**Comment by tinchoram** [comment]
Hola! 😁 podría tomar este issue? me gustaría empezar a contribuir.

**Comment by cmaureir** [comment]
Claro @tinchoram, todo tuyo. éxito!
