### ISSUE TITLE
Translate 'library/cgitb.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#900]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/cgitb.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/cgitb.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 10
* Untranslated: 10

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by ktowen** [comment]
Hello, I would like to work in this issue.

**Comment by cmaureir** [comment]
Te asigné otra, y así dejamos esta para alguien que recién comience :)

**Comment by ayosefiguera** [comment]
Hola @cmaureir, me gustaría trabajar en este issue.

**Comment by cmaureir** [comment]
con esta ya te graduas @ayosefiguera y asi para el siguiente, busca que no tenga el 'good first issue' ;)

**Comment by ayosefiguera** [comment]
Claro, sin problemas.

**Comment by ayosefiguera** [comment]
Hola @cmaureir  al intentar pasar pospell y powrap me da error. Intentare buscar la forma de solucionarlo.

**Comment by cmaureir** [comment]
Pero ese Pull request está en tu repositorio, no en este

**Comment by ayosefiguera** [comment]
Lo siento, no todo podía salir bien, lo arreglo

**Comment by cmaureir** [comment]
no te preocupes :+1:

**Comment by cmaureir** [comment]
como va esto @ayosefiguera ? veo que hay un par de commits a tu repositorio, pero no a este repositorio. Te podemos ayudar en algo?

**Comment by ayosefiguera** [comment]
Todo bien,solo he estado trasteando un poco.
