### ISSUE TITLE
Translate 'library/allos.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#902]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/allos.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/allos.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 2
* Untranslated: 2

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by Letram** [comment]
Me gustaría poder hacer esta! Estoy esperando una review de un PR, sería posible?

**Comment by cmaureir** [comment]
Claro, una fácil y rápida ;) te la asigno pues ya terminaste la otra, pero ahora toca la parte de mirar por qué fallan los builds y lograr hacer el merge de ambas :) Gracias!
