### ISSUE TITLE
Translate 'library/crypto.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#907]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/crypto.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/crypto.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 2
* Untranslated: 2

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by AdeshChoudhar19** [comment]
Translate to which language?

**Comment by cmaureir** [comment]
Hey @AdeshChoudhar19, this is the python-docs-es repository, and as you can see on the README file https://github.com/python/python-docs-es  the 'es' comes from Spanish. Are you learning or know spanish?

**Comment by AdeshChoudhar19** [comment]
Ok, thanks for replying.
I was learning Spanish few months back, then it got discontinued. I think I have to start learning again.

**Comment by drawsoek** [comment]
I an do this.

**Comment by cmaureir** [comment]
Te asigné la otra para que puedas comenzar.

**Comment by mekare7** [comment]
I can do this, if you want.

**Comment by cmaureir** [comment]
Ok @mekare7 mucho éxito con la traducción, cualquier cosa estamos en telegram!

**Comment by mekare7** [comment]
Perfecto gracias!

Missatge de Cristián Maureira-Fredes <notifications@github.com> del dia
dt., 6 d’oct. 2020 a les 13:28:

**Comment by cmaureir** [comment]
Te podemos ayudar en algo @mekare7 ? Si tienes problemas con Git o las otras herramientas avisanos

**Comment by cmaureir** [comment]
dejando libre este issue

**Comment by framorac** [comment]
quisiera ayudar me asignan este issue, por favor?

**Comment by cmaureir** [comment]
Genial!, mucho éxito @framorac

**Comment by framorac** [comment]
Gracias.!!

**Comment by framorac** [comment]
Mandé PR para revisión, no sé cómo continuar, podrían orientarme por favor cuales son los pasos siguientes?

**Comment by cmaureir** [comment]
Los pasos siguientes son que algún revisor le dará un vistazo a tu archivo y dejará comentarios, cuando esté listo alguien le dará approve y se integrará.
