### ISSUE TITLE
Translate 'library/syslog.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#908]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/syslog.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/syslog.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 27
* Untranslated: 27

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by PaoloTorregroza** [comment]
Hello, I want to contribute, Spanish is my native language. :D

**Comment by cmaureir** [comment]
Hola @PaoloTorregroza, muchas gracias por tu interés.
El grupo está oficialmente en Telegram, pero para el hacktoberfest tendremos un servidor Discord.
Ojalá puedas obtener tu entrada para participar: https://hacktoberfest.es.python.org/

Recuerda que si te interesa el Hacktoberfest, los Pull-requests cuentan desde el 1 de Octubre.
éxito!

**Comment by PaoloTorregroza** [comment]
Muchas gracias, necesito una entrada para poder hacer un pull request a este repo? o las entradas son solamente para participar en las meeting que realizaran?

**Comment by cmaureir** [comment]
Las entradas son solo para el evento que comienza este Domingo, donde estamos preparando un servidor con varios otros proyectos y así poder contribuir a mas de uno! :)

**Comment by PaoloTorregroza** [comment]
Compartiré el link que me pasaste en una comunidad en la que modero. Sin embargo lo que busco es colaborar en un proyecto en el que pueda ir un poco mas a mi bola. Muchísimas gracias.

**Comment by cmaureir** [comment]
Hola @PaoloTorregroza, no entendí mucho. Las entradas son para el evento, pero se aceptan Pull requests independiente del Hacktoberfest. Por tu pregunta, parecía que eso es lo que buscabas?

**Comment by PaoloTorregroza** [comment]
Ohhh vale gracias. Aún así se me presento una situación que impide que participe en el hacktoberfest en general :( compartiré el repo y los eventos en la comunidad de Fazt Tech, me parece genial lo que hacen

**Comment by cmaureir** [comment]
Si, igual lo decía por si quieres pasar por acá en... no sé...Diciembre? aún el proyecto estará acá, así que no te preocupes.

**Comment by PaoloTorregroza** [comment]
Tienes Twitter? O algun lado en el que te pueda seguir?

**Comment by fsenx** [comment]
Hi, I would like to collaborate, my native language is Portuguese (Brazil).

**Comment by clacri** [comment]
Hi @fsenx , and thanks for your interest. This project is for the translation of the python documentation from english to spanish, so we expect that collaborators have either spanish as their mother tongue or at least they have a good knowledge of the language.

**Comment by cmaureir** [comment]
@fsenx talvez você possa ajudar com a tradução do português brasileiro https://github.com/python/python-docs-pt-br

**Comment by jartigag** [comment]
hola otra vez! esta librería me interesa. puedo ponerme a traducirla?

**Comment by cmaureir** [comment]
Adelante @jartigag buena suerte! :tada:
