### ISSUE TITLE
Translate 'library/pyclbr.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#909]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/pyclbr.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/pyclbr.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 24
* Untranslated: 24

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by ktowen** [comment]
Hello, I would like to work in this issue.

**Comment by cmaureir** [comment]
@ktowen genial! te vamos a dejar solo 1 issue asignada, ya que es mejor para organizar las tareas del hacktoberfest.
Si mal no recuerdo tu ya tienes experiencia traduciendo! con lo que mejor te puedas enfocar en tareas con muchas mas entradas, ya que las otras donde comentaste son bastante cortas, asi se las dejamos a gente que recién comience. Te parece?

**Comment by ktowen** [comment]
Perfecto 👍
