### ISSUE TITLE
Translate 'library/aifc.po'

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#911]
This needs to reach 100% translated.

The rendered version of this file will be available at https://docs.python.org/es/3.8/library/aifc.html once translated.
Meanwhile, the English version is shown.

Current stats for `library/aifc.po`:

* Fuzzy: 0
* Percent translated: 0.0%
* Entries: 0 / 38
* Untranslated: 38

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by devil-cyber** [comment]
Hey! Can I work on this

**Comment by cmaureir** [comment]
Hola @devil-cyber, claro ;) Si te interesa la participación para el hacktoberfest, recuerda que los PR cuentan desde el 1 de Octubre. Mucho éxito! Cualquiera cosa, estamos en telegram.

**Comment by devil-cyber** [comment]
Gracias😀

**Comment by paaaron** [comment]
Yo podria trabajar tambien en la traducción

**Comment by cmaureir** [comment]
Tenemos varias issues abierta aún @paaaron, te recomiendo mirar otra ;) https://github.com/python/python-docs-es/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee+label%3A%22good+first+issue%22

**Comment by cmaureir** [comment]
Como va la traducción @devil-cyber ? te podemos ayudar en algo?

**Comment by elnaquete** [comment]
Buenas! Si puedo dar una mano con esta traducción, estoy disponible :)

**Comment by cmaureir** [comment]
Por inactividad te la asignamos a ti @elnaquete, éxito!
