### ISSUE TITLE
Entradas en archivos .po sin referencias al archivo .rst original

### ISSUE THREAD

**Issue by cmaureir** [python/python-docs-es#928]
Durante la revisión de https://github.com/python/python-docs-es/pull/498

Se encontró el siguiente problema

```
#: ../Doc/library/sys.rst:1580
msgid "See also :func:`excepthook` which handles uncaught exceptions."
msgstr ""

msgid ""
"Raises an :ref:`auditing event <auditing>` ``sys.unraisablehook`` with "
"arguments ``hook``, ``unraisable``."
msgstr ""
```

Donde la segunda entrada no tiene asociada una ubicación en el archivo `sys.rst` original.

Esto genera que al momento de construir la documentación exista una advertencia que no permite
la correcta generación de archivos.

Al momento de actualizar los archivos `.po` cuando Python 3.9 esté disponible, se tendría que poner especial cuidado
en estos casos especiales.

**Comment by humitos** [comment]
Este problema es porque el texto viene de un archivo `.py` y no de un `.rst`. Lo tienen que arreglar upstream (https://github.com/python/cpython/pull/19470). Cuando esté arreglado, a nosotros nos va a hacer la vida más fácil. Vamos a traducir esto solo una vez y listo.

**Comment by cmaureir** [comment]
Gracias por la aclaración ;)

**Comment by cmaureir** [comment]
dependemos de la docu oficial, voy a cerrar esta issue
