### ISSUE TITLE
Crear nueva rama de `3.9`

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#967]
Ya se hizo oficialmente la release de Python 3.9 y tiene sus docs online: https://docs.python.org/es/3.9/

Necesitamos coordinar este esfuerzo para:

- [ ] reducir la cantidad de PRs que tenemos abiertos
- [ ] actualizar la guia de colaboración para que usen la rama `3.9`
- [ ] seguir los pasos de https://python-docs-es.readthedocs.io/es/3.8/upgrade-python-version.html
- [ ] marcar 3.9 como default version en Read the Docs

Personalmente, creo que el mejor momento para esto es cuando termine el Hacktoberfest, tengamos menos flujo de gente activa simultáneamente, y menos PR abiertas (ya que hay que cambiarle la base y puede haber conflictos)

**Comment by raulcd** [comment]
:+1: a esperar a terminar Octubre para hacerlo.

**Comment by cmaureir** [comment]
Hoy he hecho varios merge y también pings en los issues/pr sin actividad.
Quizás estaría bueno poder hacer la actualización pronto.

**Comment by cmaureir** [comment]
Pues veo que ya hemos cubierto todos los puntos para este issue, asi que la cierro (pensaba que la docu no estaba actualizada, pero si :P) Gracias :tada:
